### ISSUE TITLE
Podcast/station error

### ISSUE THREAD

**Issue by cr3pt** [LibreTime/libretime#1042]
After fresh install (build 8498029cd) after try go to 'My Podcast' I got "Oops! Something went wrong!". In log:

```
2020-05-13T22:57:37+02:00 ERR (3): [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: PodcastNotFoundException in /usr/share/airtime/php/airtime_mvc/application/services/PodcastService.php:286
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/PodcastController.php(31): Application_Service_PodcastService::getPodcastById('1')
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): PodcastController->stationAction()
#2 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('stationAction')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
```
OS: Ubuntu 18.04 LTS (updated)

**Comment by Robbt** [comment]
So we definitely need to test the My Podcast functionality before we release LibreTime as a beta. Most of our effort has gone towards podcast-ingest and this feature has been neglected.

Also see this possibly related issue - https://discourse.libretime.org/t/my-podcasts-wont-pubish/559

**Comment by Robbt** [comment]
This was removed from the master branch and so therefore is no longer an issue.
