### ISSUE TITLE
Broker connection error, trying again in 2.0 seconds: ConnectionRefusedError(111, 'Connection refused').

### ISSUE THREAD

**Issue by itcrowdsource** [libretime/libretime#1059]
**Describe the bug**
The server doesn't playout sound.
```
May 30 06:59:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 06:59:56,582 [pypofetch] [INFO ]  Loop #113
May 30 06:59:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 06:59:56,584 [pypoliqqueue] [INFO ]  New schedule received: {'2020-05-30-23-59-59': {'start': datetime.datetime(2020, 5, 30, 23, 59, 59), 'end': datetime.datetime(2020, 5, 30, 23, 59, 59), 'uri': 'https://play.fnoobtechno.com:2199/tunein32/', 'type'
May 30 06:59:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 06:59:56,584 [pypoliqqueue] [INFO ]  waiting 61202.415254s until next scheduled item
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:03:38,646 [mixins] [WARNI]  Connection to broker lost, trying to re-establish connection...
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: Traceback (most recent call last):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/mixins.py", line 175, in run
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     for _ in self.consume(limit=None, **kwargs):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/mixins.py", line 197, in consume
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     conn.drain_events(timeout=safety_interval)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/connection.py", line 323, in drain_events
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     return self.transport.drain_events(self.connection, **kwargs)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/transport/pyamqp.py", line 103, in drain_events
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     return connection.drain_events(**kwargs)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 505, in drain_events
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     while not self.blocking_read(timeout):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 511, in blocking_read
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     return self.on_inbound_frame(frame)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/method_framing.py", line 55, in on_frame
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     callback(channel, method_sig, buf, None)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 518, in on_inbound_method
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     method_sig, payload, content,
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/abstract_channel.py", line 145, in dispatch_method
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     listener(*args)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 646, in _on_close
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self._x_close_ok()
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 661, in _x_close_ok
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/abstract_channel.py", line 59, in send_method
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     conn.frame_writer(1, self.channel_id, sig, args, content)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/method_framing.py", line 172, in write_frame
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     write(view[:offset])
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/transport.py", line 284, in write
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self._write(s)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: ConnectionResetError: [Errno 104] Connection reset by peer
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:03:38,651 [mixins] [WARNI]  Broker connection error, trying again in 2.0 seconds: ConnectionRefusedError(111, 'Connection refused').
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: Traceback (most recent call last):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/transport.py", line 137, in _connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     host, port, family, socket.SOCK_STREAM, SOL_TCP)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: socket.gaierror: [Errno -9] Address family for hostname not supported
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: During handling of the above exception, another exception occurred:
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: Traceback (most recent call last):
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/utils/functional.py", line 344, in retry_over_time
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     return fun(*args, **kwargs)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/connection.py", line 283, in connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     return self.connection
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/connection.py", line 839, in connection
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self._connection = self._establish_connection()
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/connection.py", line 794, in _establish_connection
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     conn = self.transport.establish_connection()
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/kombu-4.6.8-py3.6.egg/kombu/transport/pyamqp.py", line 130, in establish_connection
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     conn.connect()
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/connection.py", line 311, in connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self.transport.connect()
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/transport.py", line 77, in connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self._connect(self.host, self.port, self.connect_timeout)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/transport.py", line 148, in _connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     "failed to resolve broker hostname"))
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.5.2-py3.6.egg/amqp/transport.py", line 161, in _connect
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]:     self.sock.connect(sa)
May 30 07:03:38 streamfnoobtechno airtime-playout[1426]: ConnectionRefusedError: [Errno 111] Connection refused
May 30 07:03:40 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:03:40,675 [mixins] [INFO ]  Connected to amqp://airtime:**@127.0.0.1:5672//airtime
May 30 07:07:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:07:56,583 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
May 30 07:07:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:07:56,666 [pypofetch] [INFO ]  Loop #114
May 30 07:07:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:07:56,668 [pypoliqqueue] [INFO ]  New schedule received: {'2020-05-30-23-59-59': {'start': datetime.datetime(2020, 5, 30, 23, 59, 59), 'end': datetime.datetime(2020, 5, 30, 23, 59, 59), 'uri': 'https://play.fnoobtechno.com:2199/tunein32/', 'type'
May 30 07:07:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:07:56,668 [pypoliqqueue] [INFO ]  waiting 60722.331401s until next scheduled item
May 30 07:15:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:15:56,666 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
May 30 07:15:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:15:56,699 [pypofetch] [INFO ]  Loop #115
May 30 07:15:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:15:56,700 [pypoliqqueue] [INFO ]  New schedule received: {'2020-05-30-23-59-59': {'start': datetime.datetime(2020, 5, 30, 23, 59, 59), 'end': datetime.datetime(2020, 5, 30, 23, 59, 59), 'uri': 'https://play.fnoobtechno.com:2199/tunein32/', 'type'
May 30 07:15:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:15:56,700 [pypoliqqueue] [INFO ]  waiting 60242.299716s until next scheduled item
May 30 07:23:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:23:56,699 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
May 30 07:23:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:23:56,845 [pypofetch] [INFO ]  Loop #116
May 30 07:23:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:23:56,848 [pypoliqqueue] [INFO ]  New schedule received: {'2020-05-30-23-59-59': {'start': datetime.datetime(2020, 5, 30, 23, 59, 59), 'end': datetime.datetime(2020, 5, 30, 23, 59, 59), 'uri': 'https://play.fnoobtechno.com:2199/tunein32/', 'type'
May 30 07:23:56 streamfnoobtechno airtime-playout[1426]: 2020-05-30 07:23:56,848 [pypoliqqueue] [INFO ]  waiting 59762.151302s until next scheduled item
```
**To Reproduce**
1. Clean install of Liberitime
2. Created a schedule with webstreams
3. Configured Icecast and Shoutcast
4. No sound on both streams

**Expected behavior**
Sound on both streams

**LibreTime version:**
16bff4ff9

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04 LTS
 - Method: ./install
 - Details: GIT source
**Screenshots**

**Client (please complete the following information if applicable):**
 - OS: Windows
 - BrowserChrome, Firefox, Edge
 - Version latest versions

**Additional context**

**Comment by paddatrapper** [comment]
It seems like the analyser is cannot connect to rabbitMQ. Have you changed the password for rabbitMQ?

**Comment by ffalpha** [comment]
I have the same issue
