### ISSUE TITLE
Libretime refuses to import certain audio files

### ISSUE THREAD

**Issue by zklosko** [libretime/libretime#1105]
**Describe the bug**
We've been noticing certain audio files can't be imported into Libretime. This morning we had an error with a file with a variable bit rate (VBR) encoding and previously we've had errors with files encoded at 44000 Hz. I'm not sure if this is an expected error or something we can fix.

**To Reproduce**
1. Upload file
2. Wait for it to process
3. Processing fails

**Expected behavior**
The file would import successfully and would be able to be scheduled.

**LibreTime version:**
2ed4bd07d

**Installation method:**
 - OS: Ubuntu Server
 - OS Version 18.0.5 
 - Method: sudo bash install -fiap
 - Details: Scripts pulled from Github repo

**Client (please complete the following information if applicable):**
 - OS: MacOS
 - Browser: Chrome
 - Version: unknown, probably latest

**Additional context**
This is probably also a feature request, to make it so more types of files can be compatible.

**Comment by paddatrapper** [comment]
What are the airtime analyzer logs?

**Comment by zklosko** [comment]
```
2020-11-10 08:36:01,270 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/srv\/airtime\/stor\/organize\/2020.11.10 AGOS Edward Harden Peeples V Garden of Liberation Part 1 FINAL.mp3","storage_backend":"file","import_directory":"\/srv\/airtime\/stor\/\/imported\/4","original_filename":"2020.11.10 AGOS Edward Harden Peeples V Garden of Liberation Part 1 FINAL.mp3","callback_url":"http:\/\/192.168.200.26\/\/rest\/media\/2600","api_key":"7WX2TUYB0RS3QXQSP3FU","file_prefix":""}' on routing_key ''
2020-11-10 08:36:01,272 [analyzer_pipeline] [ERROR]  can't sync to MPEG frame
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 66, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 53, in analyze
    audio_file = mutagen.File(filename, easy=True)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/_util.py", line 148, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/_file.py", line 300, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/id3/_file.py", line 423, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.43.0-py2.7.egg/mutagen/mp3/__init__.py", line 403, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
HeaderNotFoundError: can't sync to MPEG frame
2020-11-10 08:36:01,273 [message_listener] [ERROR]  Analyzer pipeline exception: can't sync to MPEG frame
2020-11-10 08:36:01,407 [status_reporter] [INFO ]  HTTP request sent successfully.
```

**Comment by paddatrapper** [comment]
And do you have an example audio file that triggers this error?

**Comment by zklosko** [comment]
![Screen Shot 2020-11-11 at 11 28 14 AM](https://user-images.githubusercontent.com/31484611/98837487-01500f00-2411-11eb-8f7d-2486cb0c928b.png)

This is the information from the audio file. I don't know if Github would appreciate me uploading the actual audio file.

**Comment by paddatrapper** [comment]
hmm... It would be very helpful to have a file that I can test with while trying to fix the issue. Maybe email it to me - paddatrapper@debian.org?

**Comment by zklosko** [comment]
Sure!

You contribute to Debian too? That's so cool!

**Comment by paddatrapper** [comment]
Thanks. Will take a look

Yeah - I maintain Liquidsoap (and it's dependencies) and silan amongst other things

**Comment by paddatrapper** [comment]
I haven't had a chance to look into this, but the file for reference is https://drive.google.com/file/d/1Sos7ZUVc0uj8LWe3bbRFAoEIFe7C4NsT/view?usp=drive_web

**Comment by zklosko** [comment]
I just noticed something that I didn't pick up on before: the file in question has a variable bit rate encoding. @paddatrapper, do you think that could be tripping up the analyzer?

**Comment by paddatrapper** [comment]
Could be a limitation in one of the analyzer libraries we are using or a limitation in liquidsoap. If it is liquidsoap, things may be fixed with v2 where they use ffmpeg in the background

**Comment by jooola** [comment]
You can use liquidsoap v1.4.4, which support ffmpeg. Here you can find a .deb https://github.com/savonet/liquidsoap/releases/tag/v1.4.4

**Comment by paddatrapper** [comment]
1.4.4 is in Ubuntu 22.04 currently and v2 is in Debian testing and unstable if you don't want to download a random deb

**Comment by jooola** [comment]
Is this issue still actual after upgrading to the latest version of LibreTime ?
