### ISSUE TITLE
Problem: Silnece with filled program

### ISSUE THREAD

**Issue by yarik2720** [LibreTime/libretime#113]
Radio not going in status On Air.
Tried to restart services and nothing made work
![virtualbox_2017-03-22_21-19-50](https://cloud.githubusercontent.com/assets/1839978/24214057/68d6c0cc-0f45-11e7-9292-b3d97f17a12b.png)

**Comment by hairmare** [comment]
Weird, is there anything in `/var/log/airtime/pypo-liquidsoap/ls_script.log`?

**Comment by yarik2720** [comment]
[ls_script.log.txt](https://github.com/LibreTime/libretime/files/862580/ls_script.log.txt)

**Comment by Robbt** [comment]
I had the same problem. I believe the issue is with airtime-playout. If I start it via the /etc/init.d/airtime-playout start it fails to work correctly or produce logs. But if I start airtime playout via the command line
`sudo -u www-data airtime-playout `
It immediately appears to work.

**Comment by hairmare** [comment]
I see a couple of `Source failed (no more tracks) stopping output...` errors in the log file. 

I've seen this happen before when LibreTime is not able to store cached tracks in `/var/tmp/airtime/pypo/cache/scheduler`. What does that folder look like and does it contain any file? 

In my case I had run pypo as root and it had changed the ownership of the folder making it impossible for `www-data` to write to it. A `chown -R www-data:www-data /var/tmp/airtime/pypo/cache/scheduler` was the fix in that case.

**Comment by yarik2720** [comment]
```
/var/tmp/airtime/pypo/cache/scheduler$ ls
56.mp3  59.mp3  63.mp3  66.mp3  69.mp3  71.mp3  74.mp3  79.mp3  84.mp3
57.mp3  62.mp3  64.mp3  67.mp3  70.mp3  73.mp3  76.mp3  82.mp3  85.mp3

```
owner is www-data

**Comment by hairmare** [comment]
That looks sane 😟 

I've also had some issues with airtime-playout when I was hacking on the recorder. When individual threads of pypo die, the only way to resurrect them is to restart pypo. The logs don't always reflect this in a way that helped me figure it out.

Other than that I'm pretty much stumped on what could be wrong here. You're on Ubuntu 14.04, right? Does a reboot help? 😒

**Comment by yarik2720** [comment]
Yes, Ubuntu 14.04. Since I testing it on VirtualBox it is always new machine start

**Comment by Robbt** [comment]
Did you try manually starting airtime-playout via the command I mentioned above ? I have a feeling there is a bug here with the way we are starting airtime-playout but I need to test further. If it works for you while starting it manually this can confirm that the issue is with how the startup commands are working. Also I've noticed that airtime-playout doesn't produce correct logs so that is another issue. I'll try to duplicate this from a fresh install as I've noticed it but haven't fully confirmed it..

**Comment by Robbt** [comment]
Ok I tried this from a completely fresh ubuntu vagrant install and the on air came on without issues so I wasn't able to replicate the issue. /var/log/airtime/pypo/notify.log is still pretty empty though.

**Comment by yarik2720** [comment]
Here is output: 
[new 1.txt](https://github.com/LibreTime/libretime/files/870633/new.1.txt)

**Comment by yarik2720** [comment]
I found the reason. After upgrade it removed setuped location with music.
I think this issue can be closed (or make saving path with music during upgrade)

**Comment by hairmare** [comment]
I can't seem to find any code that tries to delete the storage dir. You are talking about `/srv/airtime/stor` aren't you? Do you know at which stage of the update it was removed? Or is it only missing in your config? This is absolutely a bug we should fix.

**Comment by yarik2720** [comment]
I'm running upgrade as ./install, on 4 step it asks to set-up folder (my previous folder was at /home/username/music/libretime/ and this field is empty)

**Comment by hairmare** [comment]
The 4. step is already the one in the web-interface's setup routine?

**Comment by yarik2720** [comment]
Yes

**Comment by hairmare** [comment]
I can't seem to find any code in the setup that removed the music dir, maybe it's happening after the setup is already finished.

What does the following return after setup? 

```bash
sudo -u postgres psql -c "
    SELECT * from cc_mount_name;
" airtime
```

I think it should look as follows but with a different directory entry.
```
 id |     directory      | type | exists | watched 
----+--------------------+------+--------+---------
  1 | /srv/airtime/stor/ | stor | t      | t
(1 row)
```

**Comment by yarik2720** [comment]
cc_mount_name shows mount_points for streams

**Comment by hairmare** [comment]
Sorry, copy paste error on my side:
```bash
sudo -u postgres psql -c "
    SELECT *
    FROM cc_music_dirs;
" airtime
```

**Comment by yarik2720** [comment]
Before filling step 4 all gone, but if i Leave that field empty, it rewrites
```
modi@modi-VirtualBox:~$ sudo -u postgres psql -c "
    SELECT *
    FROM cc_music_dirs;
" airtime
 id |          directory          | type | exists | watched 
----+-----------------------------+------+--------+---------
  1 | /home/modi/Music/libretime/ | stor | t      | t
(1 row)

modi@modi-VirtualBox:~$ sudo -u postgres psql -c "
    SELECT *
    FROM cc_music_dirs;
" airtime
 id |     directory      | type | exists | watched 
----+--------------------+------+--------+---------
  1 | /srv/airtime/stor/ | stor | t      | t
(1 row)

modi@modi-VirtualBox:~$ 

```
![virtualbox_2017-03-26_18-48-01](https://cloud.githubusercontent.com/assets/1839978/24332779/201aba38-1255-11e7-99f9-3412d38dfc41.png)

**Comment by hairmare** [comment]
It may well be that using a different path is broken somehow. I'll have to do some serious testing with a path different to `/srv/airtime`.

**Comment by hairmare** [comment]
I tried to reproduce this on a trusty box using the 3.0.0-alpha.1 tarball as follows:

```bash
mkdir -p /tmp/my/music/lib/libretime
cd
curl -O -L https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.1/libretime-3.0.0-alpha.1.tar.gz
tar xvf libretime-3.0.0-alpha.1.tar.gz
cd libretime-3.0.0-alpha.1/
./install -fiap
```

I then used `/tmp/my/music/lib/libretime` as the stor directory in step 4 and the setup didn't complete properly. Ignoring that I was able to login but `cc_music_dirs` was still empty.

I retried again with a properly chowned `/tmp/my/music/lib/libretime` and was able to finish the setup and everything worked as expected (ie. `/tmp/my/music/lib/libretime` was the only entry in `cc_music_dirs`)

I'll have to do some additional tests with an install of 3.0.0-alpha that I try upgrading to 3.0.0-alpha.1. I suspect that the installer might be the culprit since it handles things slightly different when LibreTime already was already configured in `/etc/airtime` before running the installer.

**Comment by AViSource** [comment]
Hi. I am a new LibreTime user and Linux "convert". I have no sound and the On-Air button does not come on. So, I issued the following command. 

**systemctl stop airtime-playout**

**Here are the results:**
root@radio:/# systemctl stop airtime-playout root@radio:/# sudo -u www-data airtime-playout 2018-03-03 15:45:08,515 [__main__] [INFO ]  New locale set to: C Traceback (most recent call last):   File "/usr/bin/airtime-playout", line 4, in <module>     __import__('pkg_resources').run_script('airtime-playout==1.0', 'airtime-playout')   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script     self.require(requires)[0].run_script(script_name, ns)   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1527, in run_script     exec(code, namespace, namespace)   File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/EGG-INFO/scripts/airtime-playout", line 4, in <module>     runpy.run_module("pypo", run_name="__main__")   File "/usr/lib/python2.7/runpy.py", line 192, in run_module     fname, loader, pkg_name)   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code     exec code in run_globals   File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/__main__.py", line 154, in <module>     configure_locale()   File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/__main__.py", line 144, in configure_locale     current_locale_encoding = locale.getlocale()[1].lower() AttributeError: 'NoneType' object has no attribute 'lower' root@radio:/#           

Then I issued the following command:
**sudo -u www-data airtime-playout** 

**Here is the result:**
root@radio:/#  sudo -u www-data airtime-playout 
2018-03-03 16:14:20,566 [__main__] [INFO ]  New locale set to: C 
Traceback (most recent call last): 
 File "/usr/bin/airtime-playout", line 4, in <module> 
   __import__('pkg_resources').run_script('airtime-playout==1.0', 'airtime-playout') 
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script 
   self.require(requires)[0].run_script(script_name, ns) 
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1527, in run_script 
   exec(code, namespace, namespace) 
 File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/EGG-INFO/scripts/airtime-playout", line 4, in <
module> 
   runpy.run_module("pypo", run_name="__main__") 
 File "/usr/lib/python2.7/runpy.py", line 192, in run_module 
   fname, loader, pkg_name) 
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code 
   exec code in run_globals 
 File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/__main__.py", line 154, in <module> 
   configure_locale() 
 File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/__main__.py", line 144, in configure_locale 
   current_locale_encoding = locale.getlocale()[1].lower() 
AttributeError: 'NoneType' object has no attribute 'lower' 
root@radio:/#  

**Finally, I issued the following:**
root@radio:/# sudo -u postgres psql -c " 
>     SELECT * 
>     FROM cc_music_dirs; 
> " airtime 

**And this is what I got.**

id | directory | type | exists | watched  
----+-----------+------+--------+--------- 
(0 rows)

That's weird. It appears that somehow the audio content I've uploaded is not being copied into the right place or database? Or is something else going on?

One more thing. I see from a green check mark in LibretTime that I am using a pre Alpha 4 release. What are the specific steps to upgrading my current LibreTime installation to the latest release? Would doing the upgrade fix the sound issue? Or should the sound issue be fixed first before attempting to do the upgrade to 3.0.0-alpha.4? My current installation is on a VPS Ubuntu 16.04 Server.

**Comment by Robbt** [comment]
It looks like you might be having a problem with locales. This is under the known issues of the release - see https://github.com/LibreTime/libretime/releases#issues-no-locale-3.0.0-alpha.4 for steps on how to fix it.

**Comment by AViSource** [comment]
Thanks for your response Robbt. I have fixed the locales issue.(I believe) But, here is what I get when I  issued the following command: "sudo -u www-data airtime-playout"
file:///home/sowahakai/Pictures/Screenshot%20from%202018-03-12%2023-06-55.png
I can't get liquidsoap to run.

**Comment by Robbt** [comment]
Unfortunately the pictures didn't post. I'm interested in seeing what the response to airtime-playout is.

**Comment by AViSource** [comment]
Here is the information that the pictures should have shown.
**sudo -u www-data airtime-playout**
● airtime-playout.service - Airtime Playout Service
   Loaded: loaded (/etc/systemd/system/airtime-playout.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2018-03-12 22:45:05 EDT; 12h ago
 Main PID: 227 (code=killed, signal=TERM)

Mar 12 22:45:02 radio airtime-playout[227]: 2018-03-12 22:45:02,438 [__main__] [ERROR]  [Errno 111] Connection refused
Mar 12 22:45:02 radio airtime-playout[227]: 2018-03-12 22:45:02,441 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleep
Mar 12 22:45:03 radio airtime-playout[227]: 2018-03-12 22:45:03,443 [__main__] [ERROR]  [Errno 111] Connection refused
Mar 12 22:45:03 radio airtime-playout[227]: 2018-03-12 22:45:03,443 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleep
Mar 12 22:45:04 radio airtime-playout[227]: 2018-03-12 22:45:04,448 [__main__] [ERROR]  [Errno 111] Connection refused
Mar 12 22:45:04 radio airtime-playout[227]: 2018-03-12 22:45:04,450 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleep
Mar 12 22:45:05 radio airtime-playout[227]: 2018-03-12 22:45:05,452 [__main__] [ERROR]  [Errno 111] Connection refused
Mar 12 22:45:05 radio airtime-playout[227]: 2018-03-12 22:45:05,453 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleep
Mar 12 22:45:05 radio systemd[1]: Stopping Airtime Playout Service...
Mar 12 22:45:05 radio systemd[1]: Stopped Airtime Playout Service.
lines 1-15/15 (END)


**sudo invoke-rc.d airtime-liquidsoap**
● airtime-liquidsoap.service - Airtime Liquidsoap Service
   Loaded: loaded (/etc/systemd/system/airtime-liquidsoap.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sun 2018-03-04 13:58:55 EST; 1 weeks 1 days ago
 Main PID: 951 (code=killed, signal=TERM)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
invoke-rc.d: initscript airtime-liquidsoap, action "status" failed.


**sudo invoke-rc.d airtime-analyzer**
● airtime-analyzer.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
invoke-rc.d: initscript airtime-analyzer, action "status" failed.

**sudo invoke-rc.d apache2**
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: active (running) since Sun 2018-03-04 13:54:37 EST; 1 weeks 1 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20724 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/apache2.service
           ├─  470 /usr/sbin/apache2 -k start
           ├─20742 /usr/sbin/apache2 -k start
           ├─21195 /usr/sbin/apache2 -k start
           ├─22062 /usr/sbin/apache2 -k start
           ├─23869 /usr/sbin/apache2 -k start
           └─23873 /usr/sbin/apache2 -k start

Mar 13 05:38:02 radio systemd[1]: Reloading LSB: Apache2 web server.
Mar 13 05:38:02 radio apache2[20724]:  * Reloading Apache httpd web server apache2
Mar 13 05:38:02 radio apache2[20724]:  *
Mar 13 05:38:02 radio systemd[1]: Reloaded LSB: Apache2 web server.
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**sudo invoke-rc.d rabbitmq-server**
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-03-04 14:40:34 EST; 1 weeks 1 days ago
 Main PID: 2728 (beam.smp)
   Status: "Initialized"
   CGroup: /system.slice/rabbitmq-server.service
           ├─2728 /usr/lib/erlang/erts-9.2/bin/beam.smp -W w -A 64 -P 1048576 -t 5000000 -stbt db -zdbbl 128000 -K true -- -root /usr/l
           ├─2817 /usr/lib/erlang/erts-9.2/bin/epmd -daemon
           ├─2980 erl_child_setup 1024
           ├─3065 inet_gethost 4
           └─3066 inet_gethost 4

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by Robbt** [comment]
Ok, so the problem is with liquidsoap starting. Try manually starting it with sudo -u www-data airtime-playout if you don't see any errors in the /var/log/airtime/pypo/pypo-liquidsoap logs.
