### ISSUE TITLE
Set default for replay_gain key in airtime_playout

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1258]
```
Jun 29 09:02:03 mantra airtime-playout[260]: Exception in thread Thread-712:
Jun 29 09:02:03 mantra airtime-playout[260]: Traceback (most recent call last):
Jun 29 09:02:03 mantra airtime-playout[260]: File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Jun 29 09:02:03 mantra airtime-playout[260]: self.run()
Jun 29 09:02:03 mantra airtime-playout[260]: File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/timeout.py", line 13, in run
Jun 29 09:02:03 mantra airtime-playout[260]: self.result = func(*args, **kwargs)
Jun 29 09:02:03 mantra airtime-playout[260]: File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/telnetliquidsoap.py", line 111, in queue_push
Jun 29 09:02:03 mantra airtime-playout[260]: annotation = create_liquidsoap_annotation(media_item)
Jun 29 09:02:03 mantra airtime-playout[260]: File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/telnetliquidsoap.py", line 22, in create_liquidsoap_annotation
Jun 29 09:02:03 mantra airtime-playout[260]: media["replay_gain"],
Jun 29 09:02:03 mantra airtime-playout[260]: KeyError: 'replay_gain'
```

It definitely shouldn't fail on being unable to find 'replay_gain' key, there should be a default to fall back on

_Originally posted by @paddatrapper in https://github.com/LibreTime/libretime/issues/1172#issuecomment-871231888_

**Comment by matias-tecnosoul** [comment]
Do you mean that the failure is because the tracks don't have a "replay gain" value set?. The failing tracks show a "replay gain" value in LT's dashboard. 
![replaygain](https://user-images.githubusercontent.com/19720454/123971666-a283d980-d990-11eb-9f3f-4288c78fc739.jpg)
thanks

**Comment by paddatrapper** [comment]
> Do you mean that the failure is because the tracks don't have a "replay gain" value set?

Need to dig into the code to work if that is the case. It depends on how the dictionary is created
