### ISSUE TITLE
Liquidsoap/Icecast configuration panel seems broken

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1274]
**Describe the bug**
After a fresh install from master (d58fe19ae3cd01f6339e8f25d76b607e5d6b3716), I am able to configure the streaming sources, but somehow the liquidsoap service reports that some problem is here.

![image](https://user-images.githubusercontent.com/19195485/127645013-8c8cd35a-6e32-422d-8177-7d0a81be890a.png)

**To Reproduce**

1. Install Libretime on fresh Debian Buster
2. Configure your Icecast streaming sources
3. See the error message and go check the pypo/notify logs

**Expected behavior**
No error, should be working flawlessly.

**LibreTime version:** d58fe19ae3cd01f6339e8f25d76b607e5d6b3716
**Installation method:** ./install -fiap
**OS:** Debian Buster

Some logs (seems like the client or the notifier has some troubles):
```
2021-07-30 13:07:26,159 [pypomessagehandler] [INFO ]  Received event from RabbitMQ: {"setting":{"s1_enable":"true","s1_output":"icecast","s1_type":"ogg","s1_user":"","s1_admin_user":"admin","s1_channels":"stereo","s1_pass":"[REDACTED]","s1_admin_pass":"[REDACTED]","s1_mobile":"0","s1_host":"localhost","s1_port":8000,"s1_url":"[REDACTED]","s1_genre":"","s1_mount":"master.ogg","s1_name":"Aioli Radio","s1_description":"Aioli Radio master.ogg","s1_liquidsoap_error":null,"s1_bitrate":192,"s2_output":"icecast","s2_user":"","s2_admin_user":"admin","s2_genre":"","s2_channels":"stereo","s2_pass":"[REDACTED]","s2_admin_pass":"[REDACTED]","s2_mobile":"0","s2_enable":"true","s2_type":"mp3","s2_bitrate":192,"s2_url":"[REDACTED]","s2_mount":"master.mp3","s2_host":"localhost","s2_port":8000,"s2_description":"Aioli Radio master.mp3","s2_name":"Aioli Radio","s2_liquidsoap_error":null,"s3_enable":"false","s3_output":"icecast","s3_user":"","s3_admin_user":"admin","s3_url":"","s3_description":"","s3_genre":"","s3_name":"","s3_channels":"stereo","s3_pass":"[REDACTED]","s3_admin_pass":"[REDACTED]","s3_mobile":"0","s3_type":"ogg","s3_bitrate":48,"s3_host":"station.aioli-radio.org","s3_port":8000,"s3_mount":"airtime_128","s3_liquidsoap_error":"waiting","s4_enable":"false","s4_output":"icecast","s4_name":"","s4_type":"","s4_bitrate":0,"s4_user":"","s4_admin_user":"admin","s4_admin_pass":"","s4_url":"","s4_description":"","s4_genre":"","s4_channels":"stereo","s4_host":"station.aioli-radio.org","s4_port":8000,"s4_pass":"[REDACTED]","s4_mount":"airtime_128","s4_liquidsoap_error":"waiting","s4_mobile":"","master_live_stream_port":"8001","master_live_stream_mp":"\/master","dj_live_stream_port":"8002","dj_live_stream_mp":"\/show","off_air_meta":"A\u00efoli Radio - Silence","icecast_vorbis_metadata":"false","output_sound_device":"false","output_sound_device_type":"ALSA"},"event_type":"update_stream_setting"}
2021-07-30 13:07:26,159 [pypomessagehandler] [INFO ]  Handling command: update_stream_setting
2021-07-30 13:07:26,159 [pypomessagehandler] [INFO ]  Updating stream setting...
2021-07-30 13:07:26,160 [pypofetch] [INFO ]  Received event from Pypo Message Handler: {"setting":{"s1_enable":"true","s1_output":"icecast","s1_type":"ogg","s1_user":"","s1_admin_user":"admin","s1_channels":"stereo","s1_pass":"[REDACTED]","s1_admin_pass":"[REDACTED]","s1_mobile":"0","s1_host":"localhost","s1_port":8000,"s1_url":"[REDACTED]","s1_genre":"","s1_mount":"master.ogg","s1_name":"Aioli Radio","s1_description":"Aioli Radio master.ogg","s1_liquidsoap_error":null,"s1_bitrate":192,"s2_output":"icecast","s2_user":"","s2_admin_user":"admin","s2_genre":"","s2_channels":"stereo","s2_pass":"[REDACTED]","s2_admin_pass":"[REDACTED]","s2_mobile":"0","s2_enable":"true","s2_type":"mp3","s2_bitrate":192,"s2_url":"[REDACTED]","s2_mount":"master.mp3","s2_host":"localhost","s2_port":8000,"s2_description":"Aioli Radio master.mp3","s2_name":"Aioli Radio","s2_liquidsoap_error":null,"s3_enable":"false","s3_output":"icecast","s3_user":"","s3_admin_user":"admin","s3_url":"","s3_description":"","s3_genre":"","s3_name":"","s3_channels":"stereo","s3_pass":"[REDACTED]","s3_admin_pass":"[REDACTED]","s3_mobile":"0","s3_type":"ogg","s3_bitrate":48,"s3_host":"station.aioli-radio.org","s3_port":8000,"s3_mount":"airtime_128","s3_liquidsoap_error":"waiting","s4_enable":"false","s4_output":"icecast","s4_name":"","s4_type":"","s4_bitrate":0,"s4_user":"","s4_admin_user":"admin","s4_admin_pass":"","s4_url":"","s4_description":"","s4_genre":"","s4_channels":"stereo","s4_host":"station.aioli-radio.org","s4_port":8000,"s4_pass":"[REDACTED]","s4_mount":"airtime_128","s4_liquidsoap_error":"waiting","s4_mobile":"","master_live_stream_port":"8001","master_live_stream_mp":"\/master","dj_live_stream_port":"8002","dj_live_stream_mp":"\/show","off_air_meta":"A\u00efoli Radio - Silence","icecast_vorbis_metadata":"false","output_sound_device":"false","output_sound_device_type":"ALSA"},"event_type":"update_stream_setting"}
2021-07-30 13:07:26,160 [pypofetch] [INFO ]  Handling command: update_stream_setting
2021-07-30 13:07:26,160 [pypofetch] [INFO ]  Updating stream setting...
2021-07-30 13:07:26,161 [pypofetch] [INFO ]  Restarting Liquidsoap
2021-07-30 13:07:26,176 [pypofetch] [INFO ]  Waiting for Liquidsoap to start
2021-07-30 13:07:27,184 [pypofetch] [INFO ]  Liquidsoap is up and running
2021-07-30 13:07:27,200 [pypofetch] [INFO ]  b'vars.bootup_time 1627643247.2006736\n'
2021-07-30 13:07:27,201 [pypofetch] [INFO ]  b'streams.connection_status\n'
2021-07-30 13:07:27,202 [pypofetch] [INFO ]  New timeout: 392.49246621131897
2021-07-30 13:07:27,203 [pypofetch] [INFO ]  Loop #16
2021-07-30 13:07:27,214 [pypomessagehandler] [INFO ]  Received event from RabbitMQ: {"event_type":"reset_liquidsoap_bootstrap"}
2021-07-30 13:07:27,215 [pypomessagehandler] [INFO ]  Handling command: reset_liquidsoap_bootstrap
2021-07-30 13:07:27,215 [pypomessagehandler] [INFO ]  Resetting bootstrap vars...
2021-07-30 13:07:27,215 [pypofetch] [INFO ]  Received event from Pypo Message Handler: {"event_type":"reset_liquidsoap_bootstrap"}
2021-07-30 13:07:27,215 [pypofetch] [INFO ]  Handling command: reset_liquidsoap_bootstrap
2021-07-30 13:07:27,265 [telnetliquidsoap] [INFO ]  streams.live_dj_stop

2021-07-30 13:07:27,265 [telnetliquidsoap] [INFO ]  streams.master_dj_stop

2021-07-30 13:07:27,266 [telnetliquidsoap] [INFO ]  streams.scheduled_play_start

2021-07-30 13:07:27,266 [telnetliquidsoap] [INFO ]  b'vars.stream_metadata_type 0\n'
2021-07-30 13:07:27,267 [telnetliquidsoap] [INFO ]  b'vars.station_name A\xc3\xafoli Radio\n'
2021-07-30 13:07:27,267 [telnetliquidsoap] [INFO ]  b'vars.default_dj_fade 0.000\n'
2021-07-30 13:07:27,269 [pypofetch] [INFO ]  New timeout: 392.42556524276733
2021-07-30 13:07:27,269 [pypofetch] [INFO ]  Loop #17
2021-07-30 13:07:27,315 [pypomessagehandler] [INFO ]  Received event from RabbitMQ: {"schedule":{"media":{}},"event_type":"update_schedule"}
2021-07-30 13:07:27,315 [pypomessagehandler] [INFO ]  Handling command: update_schedule
2021-07-30 13:07:27,315 [pypomessagehandler] [INFO ]  Updating schedule...
2021-07-30 13:07:27,315 [pypofetch] [INFO ]  Received event from Pypo Message Handler: {"schedule":{"media":{}},"event_type":"update_schedule"}
2021-07-30 13:07:27,315 [pypofetch] [INFO ]  Handling command: update_schedule
2021-07-30 13:07:27,315 [pypofetch] [INFO ]  New timeout: 400
2021-07-30 13:07:27,315 [pypofetch] [INFO ]  Loop #18
2021-07-30 13:07:27,316 [pypoliqqueue] [INFO ]  New schedule received: {}
2021-07-30 13:07:27,316 [pypoliqqueue] [INFO ]  waiting indefinitely for schedule
2021-07-30 13:07:44,051 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:07:44,090 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:07:44,121 [listenerstat] [ERROR]  Exception: Extra data: line 1 column 119 (char 118)
2021-07-30 13:09:44,341 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:09:44,368 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:09:44,395 [listenerstat] [ERROR]  Exception: Extra data: line 1 column 119 (char 118)
2021-07-30 13:11:44,548 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:11:44,581 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:11:44,612 [listenerstat] [ERROR]  Exception: Extra data: line 1 column 119 (char 118)
2021-07-30 13:13:44,817 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:13:44,848 [version1] [ERROR]  Extra data: line 1 column 119 (char 118)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/version1.py", line 525, in update_stream_setting_table
    _post_data={"data": json.dumps(data)}
  File "/usr/local/lib/python3.7/dist-packages/api_clients-2.0.0-py3.7.egg/api_clients/utils.py", line 113, in __call__
    return response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 119 (char 118)
2021-07-30 13:13:44,874 [listenerstat] [ERROR]  Exception: Extra data: line 1 column 119 (char 118)
2021-07-30 13:14:07,316 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
2021-07-30 13:14:07,721 [pypofetch] [INFO ]  Loop #19
2021-07-30 13:14:07,723 [pypoliqqueue] [INFO ]  New schedule received: {}
2021-07-30 13:14:07,723 [pypoliqqueue] [INFO ]  waiting indefinitely for schedule
```

**Comment by paddatrapper** [comment]
Looks like the same error @matias-tecnosoul is experiencing in #1172. I suggest we move the discussion here, as the error is easier to see.

**Comment by jooola** [comment]
Ok, but the issue you mentioned seem to compile a hole bunch of issues, are we sure it is related ?

**Comment by paddatrapper** [comment]
The logs in the last section of that issue have the same error log as here

**Comment by matias-tecnosoul** [comment]
Let me know how can I help...

**Comment by jooola** [comment]
So back to my issue, it seems it is related to #465 and #749.

I also have the following logs, and I might have overlooked them:

```
2021-08-05T14:48:44+02:00 WARN (4): [REDACTED]radio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
```

We probably have multiple issues at once, on the one hand we have airtime_mvc not properly handling the stream settings update, on the other hand the pypo is not sending the appropriate data to airtime_mvc. I'll keep digging.

**Comment by jooola** [comment]
What a nightmare, just found the tricky bug.
After I my complain about how difficult it is to change some setting such as logging in this project, I finally got some useful logs:
```
2021-08-05 18:05:04,126 [utils] [DEBUG]  http://[REDACTED]radio.org:80/api/update-stream-setting-table/api_key/[REDACTED]/format/json
2021-08-05 18:05:04,126 [utils] [DEBUG]  {'data': '{"master.ogg_listener_stat_error": "OK"}'}
2021-08-05 18:05:04,127 [utils] [DEBUG]  making a POST request
2021-08-05 18:05:04,127 [connectionpool] [DEBUG]  Starting new HTTP connection (1): [REDACTED]radio.org:80
2021-08-05 18:05:04,129 [connectionpool] [DEBUG]  http://[REDACTED]radio.org:80 "POST /api/update-stream-setting-table/api_key/[REDACTED]/format/json HTTP/1.1" 301 0
2021-08-05 18:05:04,130 [connectionpool] [DEBUG]  Starting new HTTPS connection (1): [REDACTED]radio.org:443
2021-08-05 18:05:04,162 [connectionpool] [DEBUG]  https://[REDACTED]radio.org:443 "GET /api/update-stream-setting-table/api_key/[REDACTED]/format/json HTTP/1.1" 400 2
2021-08-05 18:05:04,164 [utils] [ERROR]  GET https://[REDACTED]radio.org/api/update-stream-setting-table/api_key/[REDACTED]/format/json request failed '400':
Payload: None
Response: []
```
In the `api_client`, we created a `POST` request, `airtime_mvc` server redirects the request with a 301, and the requests library continue with a new `GET` request. I don't think this should happen, and will open a ticket in the requests library.

Still we shouldn't hit a redirect in the first place, and the construction of the server base url seems to be our trouble maker.

I propose to set it once and for all during the installation phase, and store it in the configuration. We don't need to build it from many parts spread in the config file.

**Comment by jooola** [comment]
After changing the listening port of `airtime_mvc` in the configuration file, the error I had went away:

![image](https://user-images.githubusercontent.com/19195485/128387210-03261d04-14b7-4ca2-8845-8b6fdaea5d92.png)

**Comment by jooola** [comment]
Seems like I am wrong again, discarding POST data after a redirect is normal behavior https://github.com/psf/requests/issues/5494#issuecomment-644314490

**Comment by jooola** [comment]
I had a similar issue with the analyzer, in the logs the following is being spammed:
```
2021-08-05 20:55:21,904 [status_reporter] [DEBUG]  PUT http://[REDACTED]radio.org:443//rest/media/7:
Payload: {"file_prefix": "", "ftype": "audioclip", "hidden": false, "filesize": 7818309, "md5": "957fbc50715ef41020d5ca26f26f84bb", "mime": "audio/mp3", "sample_rate": 48000, "length_seconds": 252.984, "length": "0:04:12.984000", "cueout": "252.960958", "cuein": "0.145979", "bit_rate": 247227, "channels": 2, "replay_gain": -3.16, "full_path": "/mnt/libretime/data/imported/1/Acid Pauli - Edda's Cumbia ( 2017 )_08-05-2021-20-49-36.mp3", "import_status": 0}
2021-08-05 20:55:21,906 [connectionpool] [DEBUG]  Starting new HTTP connection (1): [REDACTED]radio.org:443
2021-08-05 20:55:21,908 [status_reporter] [ERROR]  HTTP request failed due to a connection error. Retrying later. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

I reproduced the request locally and the problem is the mismatch between http and the port 443. Setting force https in the config file fixed it.

**Comment by paddatrapper** [comment]
So is the api_client not using https when the port is 443?

**Comment by jooola** [comment]
Nope, doesn't seem to be the case for the analyzer callback urls

**Comment by paddatrapper** [comment]
Analyser needs to be updated to use the same logic as the utils in api_client then. Not sure if it should depend on api_client and call it directly or duplicate the logic though

**Comment by paddatrapper** [comment]
I've opened #1283 to track the issue
