### ISSUE TITLE
HTTP 500 while creating new User

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1326]
I need to create a user, but the POST request is either responding HTTP 500, or `No token was provided to match against`.

From the logs, I see that the duplicate ID constraint is raised from the DB.

During the installation of this setup, I imported a set of user running a SQL query extracted from an old SQL backup.

Either I ran a bad SQL query, or the ID where not incremented in the DB when I ran the query.

So I wonder if this is my fault, or if we have a possible bug ?

After each HTTP 500 the ID in the DB get incremented by 1, so after a few tries the ID available is not duplicate and finally gets inserted.

**To Reproduce**

1. Fresh install
2. Extract user SQL insert statement from sql backup.
3. Rn the above query
4. Try to create a new user.
5. Check the zendphp logs

**LibreTime version:**
main branch from 3/09/21

Some logs:
```
Next PropelException: Unable to execute INSERT statement [INSERT INTO "cc_subjs" ("id", "login", "pass", "type", "first_name", "last_name", "skype_contact", "jabber_contact", "email", "cell_phone") VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9)] [wrapped: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "cc_subjs_id_idx"
D?TAIL : Key (id)=(9) already exists.] in /usr/share/airtime/php/airtime_mvc/application/models/airtime/om/BaseCcSubjs.php:1336
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/models/airtime/om/BaseCcSubjs.php(1026): BaseCcSubjs->doInsert(Object(PropelPDO))
#1 /usr/share/airtime/php/airtime_mvc/application/models/airtime/om/BaseCcSubjs.php(986): BaseCcSubjs->doSave(Object(PropelPDO))
#2 /usr/share/airtime/php/airtime_mvc/application/models/User.php(212): BaseCcSubjs->save()
#3 /usr/share/airtime/php/airtime_mvc/application/controllers/UserController.php(80): Application_Model_User->save()
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): UserController->addUserAction()
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addUserAction')
#6 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#8 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#9 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#10 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#11 {main}

```

**Comment by paddatrapper** [comment]
Was your sql dump the entire DB or just the users?

**Comment by jooola** [comment]
I extracted the user insert query from the entire DB dump and ran that in the fresh database.

**Comment by jooola** [comment]
This is the query I ran, (I obviously redacted most of the data):
```sql
```sql
INSERT INTO cc_subjs(id, login, pass, type, first_name, email)
VALUES
(2, 'jonas', 'redactedpasswordhash', 'A', 'Jonas', 'redacted@email.com'),
(3, 'faust', 'redactedpasswordhash', 'A', 'Faustin', 'redacted@email.com'),
(4, 'klaus', 'redactedpasswordhash', 'A', 'Klaus', 'redacted@email.com'),
(5, 'mathieu', 'redactedpasswordhash', 'P', 'Mahieu', 'redacted@email.com'),
(6, 'johannes', 'redactedpasswordhash', 'P', 'Johannes', 'redacted@email.com'),
(7, 'helene', 'redactedpasswordhash', 'P', 'Hélène', 'redacted@email.com'),
(8, 'amandine', 'redactedpasswordhash', 'P', 'Amandine', 'redacted@email.com'),
(9, 'mathilde', 'redactedpasswordhash', 'P', 'Mathilde', 'redacted@email.com')
;
```

**Comment by jooola** [comment]
And a side note, I saw that the password are poorly hashed in the DB this is a security problem, not the most urgent I know, but should be taken care of.

**Comment by paddatrapper** [comment]
Yeah... It is just an MD5 hash, you can see the re-implementation in the API - https://github.com/LibreTime/libretime/blob/master/api/libretimeapi/models/authentication.py#L78

**Comment by jooola** [comment]
It seems like one has to alter the ID sequence manually to make this work. I didn't knew that about postgresql.

Something like:
```sql
ALTER SEQUENCE cc_subj_id_seq RESTART WITH 9; 
```
