### ISSUE TITLE
The scheduled broadcast does not start at the scheduled time

### ISSUE THREAD

**Issue by Sergey0892** [LibreTime/libretime#1333]
Radio broadcasting planned for the whole day. The beginning is at 7 am, the end is at 22. Sometimes the broadcast does not start until you update the program in the calendar. I don’t change any parameters in the calendar, just update the program.

Version  509f680e6

**Installation method:**

Ubuntu 18.04.5 LTS
- OS Version [e.g. 18.04.5 LTS (Bionic Beaver)]
- Method git clone https://github.com/LibreTime/libretime.git
- .Install

The broadcast did not start at 7 a.m., at 7:09 a.m. I updated the calendar
```
2021-09-08 06:58:06,617 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 06:58:06,617 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T03%3A58%3A06Z%2C2021-09-09T03%3A58%3A06Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T03%3A58%3A06Z%2C2021-09-09T03%3A58%3A06Z
2021-09-08 06:58:06,641 [utils] [ERROR]  GET http://10.252.20.10:80/api/v2/schedule/?ends__range=2021-09-08T03%3A58%3A06Z%2C2021-09-09T03%3A58%3A06Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 06:58:06,642 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 06:58:06,642 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T03%3A58%3A06Z%2C2021-09-09T03%3A58%3A06Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T03%3A58%3A06Z%2C2021-09-09T03%3A58%3A06Z
2021-09-08 06:58:06,642 [pypofetch] [INFO ]  Loop #940
2021-09-08 07:04:46,642 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
2021-09-08 07:04:46,696 [utils] [ERROR]  GET http://10.252.250.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:04:46,696 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:04:46,697 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
2021-09-08 07:04:46,725 [utils] [ERROR]  GET http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:04:46,726 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:04:46,726 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
2021-09-08 07:04:46,750 [utils] [ERROR]  GET http://10.252.250.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:04:46,750 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:04:46,750 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
2021-09-08 07:04:46,774 [utils] [ERROR]  GET http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:04:46,775 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:04:46,775 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
2021-09-08 07:04:46,796 [utils] [ERROR]  GET http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:04:46,796 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:04:46,796 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A04%3A46Z%2C2021-09-09T04%3A04%3A46Z
2021-09-08 07:04:46,797 [pypofetch] [INFO ]  Loop #941
2021-09-08 07:09:22,823 [pypomessagehandler] [INFO ]  Received event from RabbitMQ: {"schedule":{"media":{"2021-09-08-04-00-00":{"start":"2021-09-08-03-59-55","end":"2021-09-08-03-59-55","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","row_id":774,"type":"stream_buffer_start","independent_event":true},"2021-09-08-04-00-00_0":{"id":2,"type":"stream_output_start","row_id":774,"uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","start":"2021-09-08-04-00-00","end":"2021-09-08-19-00-00","show_name":"Radioboss","independent_event":true},"2021-09-08-18-59-59":{"start":"2021-09-08-18-59-59","end":"2021-09-08-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_buffer_end","row_id":774,"independent_event":true},"2021-09-08-18-59-59_0":{"start":"2021-09-08-18-59-59","end":"2021-09-08-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_output_end","independent_event":true},"2021-09-09-04-00-00":{"start":"2021-09-09-03-59-55","end":"2021-09-09-03-59-55","uri":"http:\/\/eu2.radioboss.fm\/proxy\/u10619?mp=\/stream","row_id":776,"type":"stream_buffer_start","independent_event":true},"2021-09-09-04-00-00_0":{"id":2,"type":"stream_output_start","row_id":776,"uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","start":"2021-09-09-04-00-00","end":"2021-09-09-19-00-00","show_name":"Radioboss","independent_event":true},"2021-09-09-18-59-59":{"start":"2021-09-09-18-59-59","end":"2021-09-09-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_buffer_end","row_id":776,"independent_event":true},"2021-09-09-18-59-59_0":{"start":"2021-09-09-18-59-59","end":"2021-09-09-18-59-59","uri":"http:\/\/eu2.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_output_end","independent_event":true}}},"event_type":"update_schedule"}
2021-09-08 07:09:22,824 [pypomessagehandler] [INFO ]  Handling command: update_schedule
2021-09-08 07:09:22,824 [pypomessagehandler] [INFO ]  Updating schedule...
2021-09-08 07:09:22,824 [pypofetch] [INFO ]  Received event from Pypo Message Handler: {"schedule":{"media":{"2021-09-08-04-00-00":{"start":"2021-09-08-03-59-55","end":"2021-09-08-03-59-55","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","row_id":774,"type":"stream_buffer_start","independent_event":true},"2021-09-08-04-00-00_0":{"id":2,"type":"stream_output_start","row_id":774,"uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","start":"2021-09-08-04-00-00","end":"2021-09-08-19-00-00","show_name":"Radioboss","independent_event":true},"2021-09-08-18-59-59":{"start":"2021-09-08-18-59-59","end":"2021-09-08-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_buffer_end","row_id":774,"independent_event":true},"2021-09-08-18-59-59_0":{"start":"2021-09-08-18-59-59","end":"2021-09-08-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_output_end","independent_event":true},"2021-09-09-04-00-00":{"start":"2021-09-09-03-59-55","end":"2021-09-09-03-59-55","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","row_id":776,"type":"stream_buffer_start","independent_event":true},"2021-09-09-04-00-00_0":{"id":2,"type":"stream_output_start","row_id":776,"uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","start":"2021-09-09-04-00-00","end":"2021-09-09-19-00-00","show_name":"Radioboss","independent_event":true},"2021-09-09-18-59-59":{"start":"2021-09-09-18-59-59","end":"2021-09-09-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_buffer_end","row_id":776,"independent_event":true},"2021-09-09-18-59-59_0":{"start":"2021-09-09-18-59-59","end":"2021-09-09-18-59-59","uri":"http:\/\/eu.radioboss.fm\/proxy\/u10619?mp=\/stream","type":"stream_output_end","independent_event":true}}},"event_type":"update_schedule"}
2021-09-08 07:09:22,825 [pypofetch] [INFO ]  Handling command: update_schedule
2021-09-08 07:09:22,825 [pypofetch] [INFO ]  New timeout: 400
2021-09-08 07:09:22,825 [pypofetch] [INFO ]  Loop #942
2021-09-08 07:09:23,299 [pypoliqqueue] [INFO ]  New schedule received: {'2021-09-08-18-59-59': {'start': datetime.datetime(2021, 9, 8, 18, 59, 59), 'end': datetime.datetime(2021, 9, 8, 18, 59, 59), 'uri': 'http://eu2.radioboss.fm/proxy/u10619?mp=/stream', 'type': 'stream_buffer_end', 'row_id': 774, 'independent_event': True}, '2021-09-08-18-59-59_0': {'start': datetime.datetime(2021, 9, 8, 18, 59, 59), 'end': datetime.datetime(2021, 9, 8, 18, 59, 59), 'uri': 'http://eu2.radioboss.fm/proxy/u10619?mp=/stream', 'type': 'stream_output_end', 'independent_event': True}, '2021-09-09-04-00-00': {'start': datetime.datetime(2021, 9, 9, 3, 59, 55), 'end': datetime.datetime(2021, 9, 9, 3, 59, 55), 'uri': 'http://eu2.radioboss.fm/proxy/u10619?mp=/stream', 'row_id': 776, 'type': 'stream_buffer_start', 'independent_event': True}, '2021-09-09-04-00-00_0': {'id': 2, 'type': 'stream_output_start', 'row_id': 776, 'uri': 'http://eu.radioboss.fm/proxy/u10619?mp=/stream', 'start': datetime.datetime(2021, 9, 9, 4, 0), 'end': datetime.datetime(2021, 9, 9, 19, 0), 'show_name': 'Radioboss', 'independent_event': True}, '2021-09-09-18-59-59': {'start': datetime.datetime(2021, 9, 9, 18, 59, 59), 'end': datetime.datetime(2021, 9, 9, 18, 59, 59), 'uri': 'http://eu.radioboss.fm/proxy/u10619?mp=/stream', 'type': 'stream_buffer_end', 'row_id': 776, 'independent_event': True}, '2021-09-09-18-59-59_0': {'start': datetime.datetime(2021, 9, 9, 18, 59, 59), 'end': datetime.datetime(2021, 9, 9, 18, 59, 59), 'uri': 'http://eu.radioboss.fm/proxy/u10619?mp=/stream', 'type': 'stream_output_end', 'independent_event': True}}
2021-09-08 07:09:23,299 [pypoliqqueue] [INFO ]  waiting 53435.700569s until next scheduled item
2021-09-08 07:16:02,825 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
2021-09-08 07:16:02,852 [utils] [ERROR]  GET http://10.252.250.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A16%3A02Z%2C2021-09-09T04%3A16%3A02Z request failed '401':
Payload: None
Response: You are not allowed to access this resource.
2021-09-08 07:16:02,853 [pypofetch] [ERROR]  Unable to fetch schedule
2021-09-08 07:16:02,853 [pypofetch] [ERROR]  401 Client Error: Unauthorized for url: http://10.25.25.101:80/api/v2/schedule/?ends__range=2021-09-08T04%3A16%3A02Z%2C2021-09-09T04%3A16%3A02Z
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 460, in manual_schedule_fetch
    self.schedule_data = self.api_client.get_schedule()
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 56, in get_schedule
    "ends__range": ("{}Z,{}Z".format(str_current, str_end)),
  File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 121, in __call__
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

**Comment by jooola** [comment]
Pro-tip, next time put your logs between 3 back ticks to format at code.

This is probably related to the Unauthorized call you are having, could you post the api logs please ?
Also did you check that the api_key is properly set in the config file ?

**Comment by Sergey0892** [comment]
> Совет: в следующий раз поместите свои журналы между 3 обратными галочками для форматирования в коде.
> 
> Вероятно, это связано с вашим Несанкционированным вызовом. Не могли бы вы опубликовать журналы API?
> Также вы проверили, что api_key правильно установлен в файле конфигурации?

**Comment by Sergey0892** [comment]
> Pro-tip, next time put your logs between 3 back ticks to format at code.
> 
> This is probably related to the Unauthorized call you are having, could you post the api logs please ?
> Also did you check that the api_key is properly set in the config file ?

api_log is empty for me. Everything seems to be correct in the configuration file. Tell me where else could there be a mistake?

**Comment by jooola** [comment]
Please provide more information about your setup.

**Comment by Sergey0892** [comment]
> Please provide more information about your setup.

```
The ignore() lines are to squash unused variable warnings
s1_output = "icecast"
ignore(s1_output)
s1_port = 8000
ignore(s1_port)
s1_url = "http://airtime.sourcefabric.org"
ignore(s1_url)
s1_description = "LibreTime Radio! Stream #1"
ignore(s1_description)
s1_mobile = "0"
ignore(s1_mobile)
s1_liquidsoap_error = "OK"
ignore(s1_liquidsoap_error)
s1_name = "RDV Stream KST"
ignore(s1_name)
s1_enable = true
ignore(s1_enable)
s1_host = "10.252.250."
ignore(s1_host)
s1_admin_pass = "Flad"
ignore(s1_admin_pass)
s1_type = "mp3"
ignore(s1_type)
s1_bitrate = 128
ignore(s1_bitrate)
s1_genre = "radio"
ignore(s1_genre)
s1_pass = "Fld"
ignore(s1_pass)
s1_mount = "vl"
ignore(s1_mount)
s1_channels = "stereo"
ignore(s1_channels)
s1_user = ""
ignore(s1_user)
s1_admin_user = "admin"
ignore(s1_admin_user)
s2_output = "icecast"
ignore(s2_output)
s2_url = ""
ignore(s2_url)
s2_description = ""
ignore(s2_description)
s2_mobile = "0"
ignore(s2_mobile)
s2_port = 8000
ignore(s2_port)
s2_host = "10.252.250."
ignore(s2_host)
s2_pass = "Fdgi0"
ignore(s2_pass)
s2_admin_pass = "Fla"
ignore(s2_admin_pass)
s2_name = "RDV-mp3"
ignore(s2_name)
s2_mount = "vl-1"
ignore(s2_mount)
s2_enable = false
ignore(s2_enable)
s2_liquidsoap_error = "could not write data to host: No route to host in write()"
ignore(s2_liquidsoap_error)
s2_type = "mp3"
ignore(s2_type)
s2_genre = "radio"
ignore(s2_genre)
s2_user = ""
ignore(s2_user)
s2_channels = "stereo"
ignore(s2_channels)
s2_bitrate = 128
ignore(s2_bitrate)
s2_admin_user = "admin"
ignore(s2_admin_user)
s3_enable = false
ignore(s3_enable)
s3_output = "icecast"
ignore(s3_output)
s3_user = ""
ignore(s3_user)
s3_admin_user = ""
ignore(s3_admin_user)
s3_admin_pass = ""
ignore(s3_admin_pass)
s3_url = ""
ignore(s3_url)
s3_description = ""
ignore(s3_description)
s3_genre = ""
ignore(s3_genre)
s3_name = ""
ignore(s3_name)
s3_channels = "stereo"
ignore(s3_channels)
s3_liquidsoap_error = "waiting"
ignore(s3_liquidsoap_error)
s3_mobile = "0"
ignore(s3_mobile)
s3_type = "ogg"
ignore(s3_type)
s3_bitrate = 48
ignore(s3_bitrate)
s3_port = 8000
ignore(s3_port)
s3_pass = "hackme"
ignore(s3_pass)
s3_mount = "_c"
ignore(s3_mount)
s3_host = "10.252.250."
ignore(s3_host)
s4_enable = false
ignore(s4_enable)
s4_output = "icecast"
ignore(s4_output)
s4_name = ""
ignore(s4_name)
s4_type = ""
ignore(s4_type)
s4_bitrate = 0
ignore(s4_bitrate)
s4_user = ""
ignore(s4_user)
s4_admin_user = ""
ignore(s4_admin_user)
s4_admin_pass = ""
ignore(s4_admin_pass)
s4_url = ""
ignore(s4_url)
s4_description = ""
ignore(s4_description)
s4_genre = ""
ignore(s4_genre)
s4_channels = "stereo"
ignore(s4_channels)
s4_port = 8000
ignore(s4_port)
s4_pass = "hackme"
ignore(s4_pass)
s4_mount = "_d"
ignore(s4_mount)
s4_host = "10.252.250."
ignore(s4_host)
s4_liquidsoap_error = "waiting"
ignore(s4_liquidsoap_error)
s4_mobile = ""
ignore(s4_mobile)
master_live_stream_port = 8001
ignore(master_live_stream_port)
master_live_stream_mp = "/master"
ignore(master_live_stream_mp)
dj_live_stream_port = 8002
ignore(dj_live_stream_port)
dj_live_stream_mp = "/show"
ignore(dj_live_stream_mp)
off_air_meta = "LibreTime - offline"
ignore(off_air_meta)
icecast_vorbis_metadata = false
ignore(icecast_vorbis_metadata)
output_sound_device = false
ignore(output_sound_device)
output_sound_device_type = "ALSA"
ignore(output_sound_device_type)
log_file = "/var/log/airtime/pypo-liquidsoap/<script>.log"
auth_path = "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/liquidsoap_auth.py"
```
