### ISSUE TITLE
Some migrations are broken on fresh install

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1377]
**Describe the bug**

On fresh installs, the first logs for zend are from error raised in the `application/upgrade/Upgrades.php`.

It looks like some migrations does not run properly and the errors aren't logged properly.

**To Reproduce**

1. On a fresh install
2. Run the setup form
3. Check the logs

**Expected behavior**

We should have errors in the logs. This might be related to #1300 

**LibreTime version:** main branch the 2021 10 05

**Installation method:** Vagrant up
- OS: buster/bullseye
- Method: ./install -fap

**Additional context**

```
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-view/library/Zend/View/Helper/Json.php(87): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(73): Zend_View_Helper_Json->json()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(102): Zend_Controller_Action_Helper_Json->encodeJson()
#4 /vagrant/airtime_mvc/application/controllers/ApiController.php(122): Zend_Controller_Action_Helper_Json->sendJson()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->versionAction()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#8 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#10 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#11 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#12 {main}
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243 in /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-view/library/Zend/View/Helper/Json.php(87): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(73): Zend_View_Helper_Json->json()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(102): Zend_Controller_Action_Helper_Json->encodeJson()
#4 /vagrant/airtime_mvc/application/controllers/ApiController.php(122): Zend_Controller_Action_Helper_Json->sendJson()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->versionAction()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#8 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#10 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#11 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#12 {main}
2021-10-05T15:34:27+00:00 WARN (4): Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243)
2021-10-05T15:34:27+00:00 ERR (3): localhost [Logging.php:165 - loggingShutdownCallback()] - Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#4 {main}
  thrown at /vagrant/airtime_mvc/application/airtime-boot.php:93
array (
  'type' => 1,
  'message' => 'Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once(\'/vagrant/airtim...\')
#4 {main}
  thrown',
  'file' => '/vagrant/airtime_mvc/application/airtime-boot.php',
  'line' => 93,
)
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ContextSwitch.php(283): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/application/controllers/ApiController.php(80): Zend_Controller_Action_Helper_ContextSwitch->initContext()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(133): ApiController->init()
#4 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#8 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#10 {main}
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243 in /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ContextSwitch.php(283): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/application/controllers/ApiController.php(80): Zend_Controller_Action_Helper_ContextSwitch->initContext()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(133): ApiController->init()
#4 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#8 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#10 {main}
2021-10-05T15:34:27+00:00 WARN (4): Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243)
2021-10-05T15:34:27+00:00 ERR (3): localhost [Logging.php:165 - loggingShutdownCallback()] - Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#4 {main}
  thrown at /vagrant/airtime_mvc/application/airtime-boot.php:93
array (
  'type' => 1,
  'message' => 'Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once(\'/vagrant/airtim...\')
#4 {main}
  thrown',
  'file' => '/vagrant/airtime_mvc/application/airtime-boot.php',
  'line' => 93,
)
```

**Comment by jooola** [comment]
```
[Sat Feb 05 04:59:46.415896 2022] [php7:error] [pid 30757] [client 192.168.10.100:35356] PHP Fatal error:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/legacy/application/upgrade/Upgrades.php:263) in /vagrant/legacy/application/airtime-boot.php:89\nStack trace:\n#0 /vagrant/legacy/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()\n#1 [internal function]: Zend_Log->errorHandler()\n#2 /vagrant/legacy/application/airtime-boot.php(89): header()\n#3 /vagrant/legacy/public/index.php(53): require_once('/vagrant/legacy...')\n#4 {main}\n  thrown in /vagrant/legacy/application/airtime-boot.php on line 89
[Sat Feb 05 04:59:46.482253 2022] [php7:error] [pid 30756] [client 192.168.10.100:35350] PHP Fatal error:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/legacy/application/upgrade/Upgrades.php:263) in /vagrant/legacy/application/airtime-boot.php:89\nStack trace:\n#0 /vagrant/legacy/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()\n#1 [internal function]: Zend_Log->errorHandler()\n#2 /vagrant/legacy/application/airtime-boot.php(89): header()\n#3 /vagrant/legacy/public/index.php(53): require_once('/vagrant/legacy...')\n#4 {main}\n  thrown in /vagrant/legacy/application/airtime-boot.php on line 89


```

**Comment by jooola** [comment]
It looks like the migration should not run on fresh installations, as the schema was upgraded each time a migration was introduced. At first, I though the schema was created and updated using the migrations.

We should probably define how we want to handle this in the future, as django starts with a schema, and applies migrations on top of it. And I think we should handle it like django do. Either way we should fix the sql migrations files to reflect that. 

From a fresh installation on focal:
```
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.1/upgrade.sql:1: ERROR: column "album_override" of relation "imported_podcast" already exists
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.1/upgrade.sql:4: ERROR: column "autoplaylist_repeat" of relation "cc_show" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.7.1/upgrade.sql:1: ERROR: column "episode_title" of relation "podcast_episodes" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.7.1/upgrade.sql:2: ERROR: column "episode_description" of relation "podcast_episodes" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.7.2/upgrade.sql:1: ERROR: column "criteriagroup" of relation "cc_blockcriteria" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.1/upgrade.sql:1: ERROR: column "artwork" of relation "cc_files" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:1: ERROR: column "track_type" of relation "cc_files" already exists 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:12: NOTICE: relation "cc_track_types" already exists, skipping 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:14: ERROR: invalid input syntax for type boolean: "Music" LINE 1: INSERT INTO cc_track_types VALUES (1, 'MUS', 'Music', 'This ... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:15: ERROR: invalid input syntax for type boolean: "Station ID" LINE 1: INSERT INTO cc_track_types VALUES (2, 'SID', 'Station ID', '... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:16: ERROR: invalid input syntax for type boolean: "Show Intro" LINE 1: INSERT INTO cc_track_types VALUES (3, 'INT', 'Show Intro', '... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:17: ERROR: invalid input syntax for type boolean: "Show Outro" LINE 1: INSERT INTO cc_track_types VALUES (4, 'OUT', 'Show Outro', '... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:18: ERROR: invalid input syntax for type boolean: "Sweeper" LINE 1: INSERT INTO cc_track_types VALUES (5, 'SWP', 'Sweeper', 'Thi... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:19: ERROR: invalid input syntax for type boolean: "Jingle" LINE 1: INSERT INTO cc_track_types VALUES (6, 'JIN', 'Jingle', 'A sh... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:20: ERROR: invalid input syntax for type boolean: "Promo" LINE 1: INSERT INTO cc_track_types VALUES (7, 'PRO', 'Promo', 'For p... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:21: ERROR: invalid input syntax for type boolean: "Shout Out" LINE 1: INSERT INTO cc_track_types VALUES (8, 'SHO', 'Shout Out', 'A... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:22: ERROR: invalid input syntax for type boolean: "News" LINE 1: INSERT INTO cc_track_types VALUES (9, 'NWS', 'News', 'This i... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:23: ERROR: invalid input syntax for type boolean: "Commercial" LINE 1: INSERT INTO cc_track_types VALUES (10, 'COM', 'Commercial', ... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:24: ERROR: invalid input syntax for type boolean: "Interview" LINE 1: INSERT INTO cc_track_types VALUES (11, 'ITV', 'Interview', '... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql:25: ERROR: invalid input syntax for type boolean: "Voice Tracking" LINE 1: INSERT INTO cc_track_types VALUES (12, 'VTR', 'Voice Trackin... ^ 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.3/upgrade.sql:1: NOTICE: table "cc_smemb" does not exist, skipping 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.4/upgrade.sql:1: ERROR: column "soundcloud_id" of relation "cc_files" does not exist 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.4/upgrade.sql:2: ERROR: column "soundcloud_error_code" of relation "cc_files" does not exist 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.4/upgrade.sql:3: ERROR: column "soundcloud_error_msg" of relation "cc_files" does not exist 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.4/upgrade.sql:4: ERROR: column "soundcloud_link_to_file" of relation "cc_files" does not exist 
psql:/usr/share/libretime/legacy/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.4/upgrade.sql:5: ERROR: column "soundcloud_upload_time" of relation "cc_files" does not exist

```
