### ISSUE TITLE
Cannot edit or schedule a playlist

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1448]
**Describe the bug**

After migrating to Debian bullseye and upgrading to the latest commit on the main branch. But I don't know if this has to do with this.

The Playlists cannot be edited or scheduled.

When editing a playlist I get a page with undefined as title:
![image](https://user-images.githubusercontent.com/19195485/142627579-682d2e80-772e-484d-b10e-c0fefda0357a.png)

```
2021-11-19T14:09:21+01:00 INFO (6): radio.org Trying to access array offset on value of type null
```

When scheduling a playlist in a show, I get the following:
![image](https://user-images.githubusercontent.com/19195485/142627660-cfbde747-85ff-450f-a42f-bb489325091c.png)

```
2021-11-19T14:10:05+01:00 ERR (3): radio.org [ErrorController.php:28 - errorAction()] - Trying to access array offset on value of type null
2021-11-19T14:10:05+01:00 ERR (3): radio.org [ErrorController.php:29 - errorAction()] - #0 /usr/share/airtime/php/legacy/application/models/Playlist.php(269): exception_error_handler()
#1 /usr/share/airtime/php/legacy/application/models/Scheduler.php(249): Application_Model_Playlist->getContents()
#2 /usr/share/airtime/php/legacy/application/models/Scheduler.php(844): Application_Model_Scheduler->retrieveMediaFiles()
#3 /usr/share/airtime/php/legacy/application/models/Scheduler.php(1154): Application_Model_Scheduler->insertAfter()
#4 /usr/share/airtime/php/legacy/application/models/ShowInstance.php(252): Application_Model_Scheduler->scheduleAfter()
#5 /usr/share/airtime/php/legacy/application/common/AutoPlaylistManager.php(54): Application_Model_ShowInstance->addPlaylistToShow()
#6 /usr/share/airtime/php/legacy/application/common/TaskManager.php(257): AutoPlaylistManager::buildAutoPlaylist()
#7 /usr/share/airtime/php/legacy/application/common/TaskManager.php(64): AutoPlaylistTask->run()
#8 /usr/share/airtime/php/legacy/application/common/TaskManager.php(111): TaskManager->runTask()
#9 /usr/share/airtime/php/legacy/application/controllers/plugins/PageLayoutInitPlugin.php(71): TaskManager->runTasks()
#10 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(260): PageLayoutInitPlugin->routeShutdown()
#11 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(923): Zend_Controller_Plugin_Broker->routeShutdown()
#12 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#13 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#14 /usr/share/airtime/php/legacy/application/airtime-boot.php(90): Zend_Application->run()
#15 /usr/share/airtime/php/legacy/public/index.php(72): require_once('/usr/share/airt...')
#16 {main}
2021-11-19T14:10:05+01:00 ERR (3): radio.org [ErrorController.php:62 - errorAction()] - An internal application error has occurred.: ErrorException: Trying to access array offset on value of type null in /usr/share/airtime/php/legacy/application/models/Playlist.php:269
Stack trace:
#0 /usr/share/airtime/php/legacy/application/models/Playlist.php(269): exception_error_handler()
#1 /usr/share/airtime/php/legacy/application/models/Scheduler.php(249): Application_Model_Playlist->getContents()
#2 /usr/share/airtime/php/legacy/application/models/Scheduler.php(844): Application_Model_Scheduler->retrieveMediaFiles()
#3 /usr/share/airtime/php/legacy/application/models/Scheduler.php(1154): Application_Model_Scheduler->insertAfter()
#4 /usr/share/airtime/php/legacy/application/models/ShowInstance.php(252): Application_Model_Scheduler->scheduleAfter()
#5 /usr/share/airtime/php/legacy/application/common/AutoPlaylistManager.php(54): Application_Model_ShowInstance->addPlaylistToShow()
#6 /usr/share/airtime/php/legacy/application/common/TaskManager.php(257): AutoPlaylistManager::buildAutoPlaylist()
#7 /usr/share/airtime/php/legacy/application/common/TaskManager.php(64): AutoPlaylistTask->run()
#8 /usr/share/airtime/php/legacy/application/common/TaskManager.php(111): TaskManager->runTask()
#9 /usr/share/airtime/php/legacy/application/controllers/plugins/PageLayoutInitPlugin.php(71): TaskManager->runTasks()
#10 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(260): PageLayoutInitPlugin->routeShutdown()
#11 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(923): Zend_Controller_Plugin_Broker->routeShutdown()
#12 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#13 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#14 /usr/share/airtime/php/legacy/application/airtime-boot.php(90): Zend_Application->run()
#15 /usr/share/airtime/php/legacy/public/index.php(72): require_once('/usr/share/airt...')
#16 {main}
```

It feels like the playlist propel model is not working properly.

**To Reproduce**

1. Create playlist
2. Try edit the playlist
3. Try to schedule the playlist

**LibreTime version:** 04ea316cab1d5928d758632afef679e7ace6cb4f
**Installation method:** ./install -fap
**OS**: Debian Bullseye

**Comment by cr3pt** [comment]
Any solution for that error???

**Comment by jooola** [comment]
Only bullseye from what I am experiencing

**Comment by cr3pt** [comment]
I set:
```
            //format the fades in format 00(.000000)
            //$fades = $this->getFadeInfo($row['position']);
            $row['fadein'] = 0.5;
            $row['fadeout'] = 0.5;
```
but this is for play... When I find solution, I prepare fix...

**Comment by jooola** [comment]
Some hints If you are digging in this, you might want to take a look into the propel ORM stuff, and any compatibility problem between php7.3 and php7.4.

https://github.com/jooola/propel1

Would be great if you tackle this one

**Comment by jooola** [comment]
I merged some code from another propel fork, I will do some testing.

If someone wants to test this as well, feel free to pull from https://github.com/jooola/libretime/tree/deps/propel_upgradex

**Comment by jooola** [comment]
This is not solved, propel upgrade in only an extra step towards php 7.4 compatibility.
