### ISSUE TITLE
api schedules psycopg2.InterfaceError: cursor already closed

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1576]
**Describe the bug**

The api is sometimes raising 500 errors when fetching the schedules.

I see 2 different errors in the logs.

**To Reproduce**

I don't know how to reproduce yet.

**Expected behavior**

Should not raise HTTP 500

**LibreTime version:** 9fc4552cfe20c057d63e72b644976b4d20d0e581

**Installation method:** ./install -fap

- OS: Debian buster

cable, add screenshots to help explain your problem.

**Additional context**
```
2022-02-08 06:14:31,088 log ERROR Internal Server Error: /api/v2/schedule/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/drf_spectacular/drainage.py", line 144, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1208, in execute_sql
    return list(result)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1646, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1646, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
django.db.utils.InterfaceError: cursor already closed
```
```
2022-02-08 10:14:39,453 log ERROR Internal Server Error: /api/v2/show-instances/2999/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/djangorestframework-3.12.4-py3.7.egg/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1208, in execute_sql
    return list(result)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1646, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/models/sql/compiler.py", line 1646, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/Django-3.2.7-py3.7.egg/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
django.db.utils.InterfaceError: cursor already closed

```

**Comment by jooola** [comment]
Now that uwsgi has been replaced with Gunicorn + Uvicorn, this issue should not happen again.

I've been running without uwsgi for months, and didn't have this error log.
