### ISSUE TITLE
Cannot import any podcast episodes

### ISSUE THREAD

**Issue by galen-elfert** [libretime/libretime#1636]
**Describe the bug**
Selecting a podcast episode and clicking the Import button produces no result. Reloading the podcast list shows a perpetual spinning wheel next to the episode, even days later. 
Immediately after clicking import, network console shows a POST request returned 400 (“an unknown error occurred”). I think the request is supposed to create the podcast episode placeholder on the server.
The legacy.log file shows:
```
2022-02-10T15:07:03-08:00 ERR (3): libretime.cjly.net [ThirdPartyCeleryService.php:37 - _executeTask()] - Invalid request: Unknown extension name unknown
2022-02-10T15:07:03-08:00 ERR (3): libretime.cjly.net [PodcastEpisodesController.php:122 - postAction()] - Unknown extension name unknown
```
I have tried this with 8 different podcasts, all with the same result. 

**To Reproduce**
1. Go to 'Podcasts'
2. Add a podcast RSS feed
3. Double click the podcast to edit it
4. Click the check box next to an episode and click "Import"

**Expected behavior**
The podcast should finish downloading after a few minutes. 

**LibreTime version:**
From the installer: 07c0029d6
From libretime-api: 3.2.12

**Installation method:**
- Installed on two different servers; one physical machine and one Linode VPS. Both exhibited the same problem. 
- OS: Ubuntu 20.04 LTS
- Method: ./install script

**Client:**
- OS: Ubuntu
- Browser: Tried both Firefox and Chrome, latest versions

**Additional Context:**
On the server, the exception (“Unknown extension name unknown”) that is caught by the postAction() method of the Rest_PodcastEpisodesController appears to originate with the GetConcreteByName() method of the AbstractAMQPConnector. The name that has been given to the method is literally the string “unknown”.
On my first installation this exception appears in zendphp.log. In the latest installation it appears in legacy.log

Here is an example of a failed POST request:
```
{“csrf_token”:“059869b64ff194ad0789364f567a6c5dc42db81f”,“episode”:{“podcast_id”:5,“guid”:“37207 at https://www.thisamericanlife.org/”,“ingested”:0,“title”:“466: Blackjack”,“author”:“This American Life”,“description”:"The casino game everyone thinks they can beat. ",“pub_date”:“20 February 2022, 11:00 pm”,“link”:“[https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e",“enclosure”:{“bitrate”:null,“captions”:null,“categories”:[{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:"Society](https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e%22,%22enclosure%22:%7B%22bitrate%22:null,%22captions%22:null,%22categories%22:%5B%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Society) & Culture”,“type”:null},{“term”:null,“scheme”:“[http://www.itunes.com/dtds/podcast-1.0.dtd",“label”:“Arts”,“type”:null},{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:“News”,“type”:null},{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:“Politics”,“type”:null}],“channels”:null,“copyright”:null,“credits”:null,“description”:null,“duration”:3784,“expression”:null,“framerate”:null,“handler”:“mp3”,“hashes”:null,“height”:null,“javascript”:null,“keywords”:null,“lang”:null,“length”:null,“link”:“https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e”,“medium”:null,“player”:null,“ratings”:null,“restrictions”:[{“relationship”:“allow”,“type”:null,“value”:“default”}],“samplingrate”:null,“thumbnails”:null,“title”:null,“type”:“audio/mpeg”,“width”:null},“file”:[],“importIcon”:"](http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Arts%22,%22type%22:null%7D,%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22News%22,%22type%22:null%7D,%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Politics%22,%22type%22:null%7D%5D,%22channels%22:null,%22copyright%22:null,%22credits%22:null,%22description%22:null,%22duration%22:3784,%22expression%22:null,%22framerate%22:null,%22handler%22:%22mp3%22,%22hashes%22:null,%22height%22:null,%22javascript%22:null,%22keywords%22:null,%22lang%22:null,%22length%22:null,%22link%22:%22https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e%22,%22medium%22:null,%22player%22:null,%22ratings%22:null,%22restrictions%22:%5B%7B%22relationship%22:%22allow%22,%22type%22:null,%22value%22:%22default%22%7D%5D,%22samplingrate%22:null,%22thumbnails%22:null,%22title%22:null,%22type%22:%22audio/mpeg%22,%22width%22:null%7D,%22file%22:%5B%5D,%22importIcon%22:%22)”}}
```

**Comment by paddatrapper** [comment]
Could be related to #510?

**Comment by jooola** [comment]
I've come across this issue myself, and we have a need for this features. I'll dedicate some time to this, don't know when exactly.

Maybe it's worth starting to move the podcast import features to the new API ?

**Comment by galen-elfert** [comment]
I was pretty careful to look for the actual RSS links for the podcasts I tried. When I fetch them they return XML, with a top-level tag that says '<rss version="2.0"...', and the episode list is populated with the correct metadata.

**Comment by jooola** [comment]
This bug comes from the abandoned php-celery library. The php amqp library has changed it's connector name and the php-celery library rely on this name to guess which connector to use.

I'll fork the php-celery lib and fix this.

**Comment by galen-elfert** [comment]
I've pulled the changes and updated my server. Unfortunately, I'm now seeing a different error from the CeleryManager when I try to add an episode, this time returning 500 to the POST request. 
```
2022-03-08T04:39:59+00:00 ERR (3): my.domain.net [Logging.php:165 - loggingShutdownCallback()] - Uncaught Error: Class 'Celery\Celery' not found in /usr/share/airtime/php/legacy/application/common/CeleryManager.php:40
Stack trace:
#0 /usr/share/airtime/php/legacy/application/common/CeleryManager.php(67): CeleryManager::_setupCeleryExchange()
#1 /usr/share/airtime/php/legacy/application/services/ThirdPartyCeleryService.php(30): CeleryManager::sendCeleryMessage()
#2 /usr/share/airtime/php/legacy/application/services/PodcastEpisodeService.php(194): Application_Service_ThirdPartyCeleryService->_executeTask()
#3 /usr/share/airtime/php/legacy/application/services/PodcastEpisodeService.php(53): Application_Service_PodcastEpisodeService->_download()
#4 /usr/share/airtime/php/legacy/application/modules/rest/controllers/PodcastEpisodesController.php(112): Application_Service_PodcastEpisodeService->importEpisode()
#5 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): Rest_PodcastEpisodesController->postAction()
#6 /usr/share/airtime/php/legacy/vendor/zf1s/zend-control at /usr/share/airtime/php/legacy/application/common/CeleryManager.php:40
array (
  'type' => 1,
  'message' => 'Uncaught Error: Class \'Celery\\Celery\' not found in /usr/share/airtime/php/legacy/application/common/CeleryManager.php:40
Stack trace:
#0 /usr/share/airtime/php/legacy/application/common/CeleryManager.php(67): CeleryManager::_setupCeleryExchange()
#1 /usr/share/airtime/php/legacy/application/services/ThirdPartyCeleryService.php(30): CeleryManager::sendCeleryMessage()
#2 /usr/share/airtime/php/legacy/application/services/PodcastEpisodeService.php(194): Application_Service_ThirdPartyCeleryService->_executeTask()
#3 /usr/share/airtime/php/legacy/application/services/PodcastEpisodeService.php(53): Application_Service_PodcastEpisodeService->_download()
#4 /usr/share/airtime/php/legacy/application/modules/rest/controllers/PodcastEpisodesController.php(112): Application_Service_PodcastEpisodeService->importEpisode()
#5 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): Rest_PodcastEpisodesController->postAction()
#6 /usr/share/airtime/php/legacy/vendor/zf1s/zend-control',
  'file' => '/usr/share/airtime/php/legacy/application/common/CeleryManager.php',
  'line' => 40,
)
```

**Comment by jooola** [comment]
The vendors didn't get updated by your procedure, be sure to properly reinstall the composer libraries

**Comment by galen-elfert** [comment]
So I figured out how to update composer libraries (running 'composer install' from inside /legacy). That worked great on my test server. Podcasts are fixed. 
Unfortunately when I did the same upgrade procedure on our station server, which was running a slightly earlier version, everything broke. Services were stopping because log files were in the wrong place, and database connections were failing. Eventually I just did an uninstall and re-install, and now the server is running, but podcasts are broken again. The POST request succeeds, but the download seems to fail. 
If necessary I can completely wipe the server and just do a fresh install, but I'm hoping there's a simpler fix. 
This is the log file after start up:
```
2022-03-15T14:37:12-07:00 WARN (4): libretime.cjly.net SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2022-03-15T14:41:08-07:00 INFO (6): libretime.cjly.net Registered Component: pypo@10.0.12.132
2022-03-15T14:41:13-07:00 INFO (6): libretime.cjly.net Registered Component: show-recorder@10.0.12.132
2022-03-15T14:41:13-07:00 INFO (6): libretime.cjly.net Notifying RabbitMQ to send message to pypo
2022-03-15T14:41:13-07:00 ERR (3): libretime.cjly.net [ErrorController.php:28 - errorAction()] - stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)
2022-03-15T14:41:13-07:00 ERR (3): libretime.cjly.net [ErrorController.php:29 - errorAction()] - #0 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(253): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(236): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(63): PhpAmqpLib\Connection\AbstractConnection->__construct()
#3 /usr/share/airtime/php/legacy/application/models/RabbitMq.php(24): PhpAmqpLib\Connection\AMQPStreamConnection->__construct()
#4 /usr/share/airtime/php/legacy/application/models/RabbitMq.php(57): Application_Model_RabbitMq::sendMessage()
#5 /usr/share/airtime/php/legacy/application/controllers/ApiController.php(1259): Application_Model_RabbitMq::SendMessageToPypo()
#6 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->rabbitmqDoPushAction()
#7 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#8 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#9 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#10 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#11 /usr/share/airtime/php/legacy/application/airtime-boot.php(80): Zend_Application->run()
#12 /usr/share/airtime/php/legacy/public/index.php(53): require_once('/usr/share/airt...')
#13 {main}
2022-03-15T14:41:13-07:00 ERR (3): libretime.cjly.net [ErrorController.php:62 - errorAction()] - An internal application error has occurred.: PhpAmqpLib\Exception\AMQPIOException: stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused) in /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:108
Stack trace:
#0 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(253): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(236): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /usr/share/airtime/php/legacy/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(63): PhpAmqpLib\Connection\AbstractConnection->__construct()
#3 /usr/share/airtime/php/legacy/application/models/RabbitMq.php(24): PhpAmqpLib\Connection\AMQPStreamConnection->__construct()
#4 /usr/share/airtime/php/legacy/application/models/RabbitMq.php(57): Application_Model_RabbitMq::sendMessage()
#5 /usr/share/airtime/php/legacy/application/controllers/ApiController.php(1259): Application_Model_RabbitMq::SendMessageToPypo()
#6 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->rabbitmqDoPushAction()
#7 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#8 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#9 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#10 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#11 /usr/share/airtime/php/legacy/application/airtime-boot.php(80): Zend_Application->run()
#12 /usr/share/airtime/php/legacy/public/index.php(53): require_once('/usr/share/airt...')
#13 {main}
```
This line appears when I try to add an episode:
```
2022-03-15T14:43:51-07:00 INFO (6): libretime.cjly.net json_decode() expects parameter 1 to be string, object given
```

**Comment by jooola** [comment]
@galen-elfert Hello, you didn't describe how you upgraded your installation, but you cannot cherry-pick a fix in the main branch and apply it on top of an older version. A lot has changed and I cannot guess what could happen in your setup.

If you are working with git to install LibreTime, be sure to clean the cloned repo before upgrading.

**Comment by galen-elfert** [comment]
I was originally just pulling the latest changes, running composer, then running the install script. I think I got lucky on my test server because the changes were relatively small. 
On the non-working server, I've now tried doing a full 'git clean -fxd' and then running the install script again. Unfortunately I'm still seeing the same php-amqplib 'Connection refused' error after restarting.

**Comment by jooola** [comment]
In that case you should probably just backup, install fresh and restore.
