### ISSUE TITLE
pypo not found after upgrade from alpha.10 to main

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1683]
During my testing for the upgrade from alpha.10 to alpha.11 on Ubuntu 18.04, I got the following traceback. This is after running `git clean`, `./install -fiap` for the upgrade and updating the config file. Restarting `libretime-pypo` resulted in 

```
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,539 [__main__] [INFO ]  ###########################################
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,540 [__main__] [INFO ]  #             *** pypo  ***               #
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,540 [__main__] [INFO ]  #   Liquidsoap Scheduled Playout System   #
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,542 [__main__] [INFO ]  ###########################################
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,543 [__main__] [INFO ]  Timezone: ('UTC', 'UTC')
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,543 [__main__] [INFO ]  UTC time: 2022-03-18 10:59:55.543733
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,584 [version1] [INFO ]  Airtime API version found: 1.1
Mar 18 10:59:55 libretime-development libretime-playout[9725]: 2022-03-18 10:59:55,584 [version1] [INFO ]  pypo is only compatible with API version: 1.1
Mar 18 10:59:55 libretime-development libretime-playout[9725]: Traceback (most recent call last):
Mar 18 10:59:55 libretime-development libretime-playout[9725]:   File "/usr/local/bin/libretime-playout", line 5, in <module>
Mar 18 10:59:55 libretime-development libretime-playout[9725]:     runpy.run_module("pypo", run_name="__main__")
Mar 18 10:59:55 libretime-development libretime-playout[9725]:   File "/usr/lib/python3.6/runpy.py", line 208, in run_module
Mar 18 10:59:55 libretime-development libretime-playout[9725]:     return _run_code(code, {}, init_globals, run_name, mod_spec)
Mar 18 10:59:55 libretime-development libretime-playout[9725]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Mar 18 10:59:55 libretime-development libretime-playout[9725]:     exec(code, run_globals)
Mar 18 10:59:55 libretime-development libretime-playout[9725]:   File "/usr/local/lib/python3.6/dist-packages/pypo/__main__.py", line 244, in <module>
Mar 18 10:59:55 libretime-development libretime-playout[9725]:     ls_host = config["pypo"]["ls_host"]
Mar 18 10:59:55 libretime-development libretime-playout[9725]:   File "/usr/lib/python3/dist-packages/configobj.py", line 554, in __getitem__
Mar 18 10:59:55 libretime-development libretime-playout[9725]:     val = dict.__getitem__(self, key)
Mar 18 10:59:55 libretime-development libretime-playout[9725]: KeyError: 'pypo'
```

Which looks like it isn't running the correct playout code (that should be using the shared module)

**Comment by paddatrapper** [comment]
An interesting note - the upgrade was fine on Debian Buster. This issue seems only to be happening on Ubuntu

**Comment by paddatrapper** [comment]
Solution in #1684 and the same root cause, so merging into that issue

**Comment by jooola** [comment]
The `libretime-pypo` tool does not exists, it is either `libretime-playout` or `libretime-liquidsoap`, is that a typo ?
