### ISSUE TITLE
Write Loguru output to stdout

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1757]
For the docker images, we need to write logs out to stdout. Using the usual trick of `ln -s /dev/stdout /var/log/libretime/analyzer.log` doesn't work. It fails with the following error:

```
liquidsoap_1  | Traceback (most recent call last):                                                                                                                                                                
liquidsoap_1  |   File "/usr/local/lib/python3.10/site-packages/loguru/_handler.py", line 289, in _queued_writer
liquidsoap_1  |     self._sink.write(message)                                                            
liquidsoap_1  |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 172, in write 
liquidsoap_1  |     if self._rotation_function is not None and self._rotation_function(message, self._file):                                                                                                      liquidsoap_1  |   File "/usr/local/lib/python3.10/site-packages/loguru/_file_sink.py", line 116, in __call__                                                                                                      
liquidsoap_1  |     creation_time = get_ctime(filepath)                                                                                                                                                           
liquidsoap_1  |   File "/usr/local/lib/python3.10/site-packages/loguru/_ctime_functions.py", line 34, in get_ctime                                                                                                
liquidsoap_1  |     return os.stat(filepath).st_mtime                                                    
liquidsoap_1  | FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/fd/pipe:[2036246]'                                                                                                               liquidsoap_1  | --- End of logging error ---
```

**Comment by jooola** [comment]
Loguru always logs to stdout (or stderr I don't remember ) by default, you should not specify a logfile.
