### ISSUE TITLE
alpha 12 can not upload files above a certain size

### ISSUE THREAD

**Issue by ldog0121** [libretime/libretime#1765]
files above approx 180mb fail on upload 
Clean install of Alpha 12 on Ubuntu 20.4 replaced DB and Stor from a working server 

**Expected behavior**
drag file to upload window after pending it is able to be scheduled

**LibreTime version:**
Alpha 12

**Installation method:**

- OS: 20.4
- Method: [e.g. `./install` script

Error log 
```
FileNotFoundError: [Errno 2] No such file or directory: '/srv/airtime/stor/organize/BLues is the truth 599_mixdown.ogg'
2022-04-13 18:01:31.173 | ERROR    | libretime_analyzer.message_listener:spawn_analyzer_process:267 - Analyzer pipeline exception: [Errno 2] No such file or directory: '/srv/airtime/stor/organize/BLues is the truth 599_mixdown.ogg'
2022-04-13 18:01:31.312 | INFO     | libretime_analyzer.status_reporter:send_http_request:123 - HTTP request sent successfully.
2022-04-13 18:25:19.153 | INFO     | libretime_analyzer.message_listener:msg_received_callback:144 -  - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/Bluestestshow.mp3","storage_backend":"file","import_directory":"\\/srv\\/airtime\\/stor\\/\\/imported\\/1","original_filename":"Bluestestshow.mp3","callback_url":"http:\\/\\/?.?.?.?.?\\/\\/rest\\/media\\/1553","api_key":"GY4BP87WZ8H1IYYARX3R","file_prefix":""}'' on routing_key ''
2022-04-13 18:29:47.041 | ERROR    | libretime_analyzer.message_listener:__init__:85 - Connection to message queue failed. 
2022-04-13 18:29:47.044 | ERROR    | libretime_analyzer.message_listener:__init__:86 - Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')
2022-04-13 18:29:47.046 | INFO     | libretime_analyzer.message_listener:__init__:87 - Retrying in 5 seconds...
2022-04-13 18:29:47.230 | INFO     | libretime_analyzer.status_reporter:send_http_request:123 - HTTP request sent successfully.
2022-04-13 18:29:52.080 | INFO     | libretime_analyzer.message_listener:connect_to_messaging_server:116 -  Listening for messages...
2022-04-13 18:29:52.084 | INFO     | libretime_analyzer.message_listener:msg_received_callback:144 -  - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/Bluestestshow.mp3","storage_backend":"file","import_directory":"\\/srv\\/airtime\\/stor\\/\\/imported\\/1","original_filename":"Bluestestshow.mp3","callback_url":"http:\\/\\/?.?.?.?.?\\/\\/rest\\/media\\/1553","api_key":"GY4BP87WZ8H1IYYARX3R","file_prefix":""}'' on routing_key ''
2022-04-13 18:29:52.086 | ERROR    | libretime_analyzer.pipeline.pipeline:run_analysis:120 - [Errno 2] No such file or directory: '/srv/airtime/stor/organize/Bluestestshow.mp3'
Traceback (most recent call last):

  File "/usr/local/bin/libretime-analyzer", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f3922aa4310>
           └ <Command cli>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f3922d1c430>
         │    └ <function Command.invoke at 0x7f3922aa4dc0>
         └ <Command cli>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/airtim...
           │   │      │    │           └ <click.core.Context object at 0x7f3922d1c430>
           │   │      │    └ <function cli at 0x7f39215aa700>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x7f3922aa1b80>
           └ <click.core.Context object at 0x7f3922d1c430>

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/airtim...
                       └ ()

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/main.py", line 45, in cli
    _msg_listener = MessageListener(config.rabbitmq)
                    │               │      └ RabbitMQConfig(host='127.0.0.1', port=5672, name='libretime', user='airtime', password='airtime', vhost='/airtime')
                    │               └ Config(rabbitmq=RabbitMQConfig(host='127.0.0.1', port=5672, name='libretime', user='airtime', password='airtime', vhost='/air...
                    └ <class 'libretime_analyzer.message_listener.MessageListener'>

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/message_listener.py", line 77, in __init__
    self.wait_for_messages()
    │    └ <function MessageListener.wait_for_messages at 0x7f39215aa310>
    └ <libretime_analyzer.message_listener.MessageListener object at 0x7f3921574850>

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/message_listener.py", line 121, in wait_for_messages
    self._channel.start_consuming()
    │    │        └ <function BlockingChannel.start_consuming at 0x7f39218e5dc0>
    │    └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
    └ <libretime_analyzer.message_listener.MessageListener object at 0x7f3921574850>

  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 1865, in start_consuming
    self._process_data_events(time_limit=None)
    │    └ <function BlockingChannel._process_data_events at 0x7f39218e5f70>
    └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...

  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 2026, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
    │    │                                         └ None
    │    └ <property object at 0x7f39218ddae0>
    └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...

  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 833, in process_data_events
    self._dispatch_channel_events()
    │    └ <function BlockingConnection._dispatch_channel_events at 0x7f39218de670>
    └ <BlockingConnection impl=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport obj...

  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
    │            └ <function Channel._get_cookie at 0x7f39219ce040>
    └ <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport ...

  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 1492, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
    │             │                   │     │   └ <member 'method' of '_ConsumerDeliveryEvt' objects>
    │             │                   │     └ <pika.adapters.blocking_connection._ConsumerDeliveryEvt object at 0x7f3920134bd0>
    │             │                   └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
    │             └ <member 'on_message_callback' of '_ConsumerInfo' objects>
    └ <pika.adapters.blocking_connection._ConsumerInfo object at 0x7f39223404a0>

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/message_listener.py", line 176, in msg_received_callback
    audio_metadata = MessageListener.spawn_analyzer_process(
                     │               └ <staticmethod object at 0x7f3921af48e0>
                     └ <class 'libretime_analyzer.message_listener.MessageListener'>

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/message_listener.py", line 257, in spawn_analyzer_process
    Pipeline.run_analysis(
    │        └ <staticmethod object at 0x7f3921985820>
    └ <class 'libretime_analyzer.pipeline.pipeline.Pipeline'>

> File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/pipeline/pipeline.py", line 96, in run_analysis
    metadata = analyze_metadata(audio_file_path, metadata)
               │                │                └ {'file_prefix': '', 'ftype': 'audioclip', 'hidden': False}
               │                └ '/srv/airtime/stor/organize/Bluestestshow.mp3'
               └ <function analyze_metadata at 0x7f39218ec310>

  File "/usr/local/lib/python3.8/dist-packages/libretime_analyzer/pipeline/analyze_metadata.py", line 21, in analyze_metadata
    metadata["filesize"] = filepath.stat().st_size
    │                      │        └ <function Path.stat at 0x7f3922cbc5e0>
    │                      └ PosixPath('/srv/airtime/stor/organize/Bluestestshow.mp3')
    └ {'file_prefix': '', 'ftype': 'audioclip', 'hidden': False}

  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
           │    │              └ PosixPath('/srv/airtime/stor/organize/Bluestestshow.mp3')
           │    └ <member '_accessor' of 'Path' objects>
           └ PosixPath('/srv/airtime/stor/organize/Bluestestshow.mp3')

FileNotFoundError: [Errno 2] No such file or directory: '/srv/airtime/stor/organize/Bluestestshow.mp3'
2022-04-13 18:29:52.112 | ERROR    | libretime_analyzer.message_listener:spawn_analyzer_process:267 - Analyzer pipeline exception: [Errno 2] No such file or directory: '/srv/airtime/stor/organize/Bluestestshow.mp3'
2022-04-13 18:29:52.263 | INFO     | libretime_analyzer.status_reporter:send_http_request:123 - HTTP request sent successfully.
```

**Comment by jooola** [comment]
Does the `/srv/airtime/stor/organize/` directory exists and have the proper permission / ownership ?

**Comment by jooola** [comment]
And does it work with files below 180mb ?

**Comment by ldog0121** [comment]
yes it does work with sub 180mb files 
output from organize is 
> ls -l /srv/airtime/stor/organize/
total 1168
-rwxrwxrwx 1 www-data www-data 596033 Apr 13 01:14 ANOTHER DAY ANOTHER DOLLAR SWEEPER.mp3
-rwxrwxrwx 1 www-data www-data 595963 Apr 13 01:14 WOLF-LIVE-DJS-SWEEPER.mp3

**Comment by jooola** [comment]
Does the upload fail or does the analyzer fail to scan the file ?

Could you please paste legacy logs from `legacy.log` ? 

I'll try to replicate this.

**Comment by jooola** [comment]
I cannot replicate this on a vagrant focal setup, using a 500Mb file.

The legacy logs and the webserver logs will tell use more what happen to file during the upload procedure.

**Comment by ldog0121** [comment]
[legacy.zip](https://github.com/libretime/libretime/files/8488196/legacy.zip)

**Comment by jooola** [comment]
Can you reproduce your issue and send me the logs of that particular moment ? It seem like you are doing a lot of stuff while this error happen I cannot isolate a particular error message.

From the logs you initially send, it looks like the analyzer processed the file and somehow tried to process the same file again hence the `file not found`.

**Comment by ldog0121** [comment]
yes even files that fail will play

**Comment by ldog0121** [comment]
Solved this by doing a total clean install and not doing an upgrade

**Comment by esbobkov** [comment]
Got same issue, when setup cheapest CPU with 5% vCPU on VM.

**Comment by jooola** [comment]
> Got same issue, when setup cheapest CPU with 5% vCPU on VM.

Could you open a new issue with logs and details, so we can reproduce and fix the issue ?
