### ISSUE TITLE
Legacy logs 'Undefined variable: totalDisplayRows'

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2111]
**Describe the bug**

I don't experience any issue in the UI, but I have those logs showing up sometimes, and it feels like something that should be fixed.

**To Reproduce**

1. Browse the Dashboard and call 'POST /Library/contents-feed'

**Expected behavior**

No errrr should be logged. 

**LibreTime version:**

main branch dead0a3429e866958439eb2fe6e1fa40cac47cfd

**Installation method:**

Both vagrant setup and docker-compose

**Additional context**
```
libretime-postgres-1    | 2022-09-08 20:15:46.846 UTC [3386] ERROR:  UNION types text and integer cannot be matched at character 2149
libretime-postgres-1    | 2022-09-08 20:15:46.846 UTC [3386] STATEMENT:  SELECT COUNT(*)  FROM ((SELECT PL.id AS id,name AS track_title,login AS artist_name,NULL::text AS album_title,NULL::text AS genre,length,EXTRACT(YEAR FROM utime)::varchar AS year,utime,mtime,'playlist'::varchar AS ftype,NULL::int AS track_number,NULL::text AS mood,NULL::int AS bpm,NULL::text AS composer,NULL::text AS info_url,NULL::int AS bit_rate,NULL::int AS sample_rate,NULL::text AS isrc_number,NULL::text AS encoded_by,NULL::text AS label,NULL::text AS copyright,NULL::VARCHAR AS mime,NULL::text AS language,NULL::VARCHAR AS filepath,login AS owner_id,NULL::text AS conductor,NULL::NUMERIC AS replay_gain,NULL::TIMESTAMP AS lptime,NULL::boolean AS is_playlist,NULL::boolean AS is_scheduled,NULL::INTERVAL AS cuein,NULL::INTERVAL AS cueout,NULL::text AS description,NULL::text AS artwork,NULL::text AS track_type_id FROM cc_playlist AS PL LEFT JOIN cc_subjs AS sub ON (sub.id = PL.creator_id)) UNION (SELECT BL.id AS id,name AS track_title,login AS artist_name,NULL::text AS album_title,NULL::text AS genre,length,EXTRACT(YEAR FROM utime)::varchar AS year,utime,mtime,'block'::varchar AS ftype,NULL::int AS track_number,NULL::text AS mood,NULL::int AS bpm,NULL::text AS composer,NULL::text AS info_url,NULL::int AS bit_rate,NULL::int AS sample_rate,NULL::text AS isrc_number,NULL::text AS encoded_by,NULL::text AS label,NULL::text AS copyright,NULL::VARCHAR AS mime,NULL::text AS language,NULL::VARCHAR AS filepath,login AS owner_id,NULL::text AS conductor,NULL::NUMERIC AS replay_gain,NULL::TIMESTAMP AS lptime,NULL::boolean AS is_playlist,NULL::boolean AS is_scheduled,NULL::INTERVAL AS cuein,NULL::INTERVAL AS cueout,NULL::text AS description,NULL::text AS artwork,NULL::text AS track_type_id FROM cc_block AS BL LEFT JOIN cc_subjs AS sub ON (sub.id = BL.creator_id)) UNION (SELECT FILES.id AS id,track_title,artist_name,album_title,genre,(cueout - cuein)::INTERVAL AS length,year AS year,utime,mtime,ftype,track_number,mood,bpm,composer,info_url,bit_rate,sample_rate,isrc_number,encoded_by,label,copyright,mime,language,filepath,sub.login AS owner_id,conductor,replay_gain,lptime,is_playlist,is_scheduled,cuein,cueout,description,artwork,track_type_id FROM cc_files AS FILES LEFT JOIN cc_subjs AS sub ON (sub.id = FILES.owner_id) WHERE file_exists = 'TRUE' AND hidden='FALSE') UNION (SELECT ws.id AS id,name AS track_title,login AS artist_name,NULL::text AS album_title,NULL::text AS genre,length,EXTRACT(YEAR FROM utime)::varchar AS year,utime,mtime,'stream'::varchar AS ftype,NULL::int AS track_number,NULL::text AS mood,NULL::int AS bpm,NULL::text AS composer,NULL::text AS info_url,NULL::int AS bit_rate,NULL::int AS sample_rate,NULL::text AS isrc_number,NULL::text AS encoded_by,NULL::text AS label,NULL::text AS copyright,mime,NULL::text AS language,url AS filepath,login AS owner_id,NULL::text AS conductor,NULL::NUMERIC AS replay_gain,lptime,NULL::boolean AS is_playlist,NULL::boolean AS is_scheduled,NULL::INTERVAL AS cuein,NULL::INTERVAL AS cueout,NULL::text AS description,NULL::text AS artwork,NULL::text AS track_type_id FROM cc_webstream AS ws LEFT JOIN cc_subjs AS sub ON (sub.id = ws.creator_id))) AS RESULTS
libretime-legacy-1      | 2022-09-08T20:15:46+00:00 INFO (6): SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  UNION types text and integer cannot be matched
libretime-legacy-1      | LINE 1: ...ist,is_scheduled,cuein,cueout,description,artwork,track_type...
libretime-legacy-1      |                                                              ^
libretime-legacy-1      | 2022-09-08T20:15:46+00:00 NOTICE (5): Undefined variable: totalDisplayRows
libretime-legacy-1      | 2022-09-08T20:15:46+00:00 ERR (3): [ErrorController.php:28 - errorAction()] - Undefined variable: totalDisplayRows
libretime-legacy-1      | 2022-09-08T20:15:46+00:00 ERR (3): [ErrorController.php:29 - errorAction()] - #0 /var/www/html/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
libretime-legacy-1      | #1 /var/www/html/application/models/Datatables.php(211): Zend_Log->errorHandler()
libretime-legacy-1      | #2 /var/www/html/application/models/StoredFile.php(818): Application_Model_Datatables::findEntries()
libretime-legacy-1      | #3 /var/www/html/application/controllers/LibraryController.php(328): Application_Model_StoredFile::searchLibraryFiles()
libretime-legacy-1      | #4 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LibraryController->contentsFeedAction()
libretime-legacy-1      | #5 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
libretime-legacy-1      | #6 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
libretime-legacy-1      | #7 /var/www/html/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
libretime-legacy-1      | #8 /var/www/html/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
libretime-legacy-1      | #9 /var/www/html/application/airtime-boot.php(77): Zend_Application->run()
libretime-legacy-1      | #10 /var/www/html/public/index.php(56): require_once('/var/www/html/a...')
libretime-legacy-1      | #11 {main}
libretime-legacy-1      | 2022-09-08T20:15:46+00:00 ERR (3): [ErrorController.php:62 - errorAction()] - An internal application error has occurred.: ErrorException: Undefined variable: totalDisplayRows in /var/www/html/application/models/Datatables.php:211
libretime-legacy-1      | Stack trace:
libretime-legacy-1      | #0 /var/www/html/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
libretime-legacy-1      | #1 /var/www/html/application/models/Datatables.php(211): Zend_Log->errorHandler()
libretime-legacy-1      | #2 /var/www/html/application/models/StoredFile.php(818): Application_Model_Datatables::findEntries()
libretime-legacy-1      | #3 /var/www/html/application/controllers/LibraryController.php(328): Application_Model_StoredFile::searchLibraryFiles()
libretime-legacy-1      | #4 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LibraryController->contentsFeedAction()
libretime-legacy-1      | #5 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
libretime-legacy-1      | #6 /var/www/html/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
libretime-legacy-1      | #7 /var/www/html/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
libretime-legacy-1      | #8 /var/www/html/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
libretime-legacy-1      | #9 /var/www/html/application/airtime-boot.php(77): Zend_Application->run()
libretime-legacy-1      | #10 /var/www/html/public/index.php(56): require_once('/var/www/html/a...')
libretime-legacy-1      | #11 {main}
libretime-legacy-1      | 192.168.240.11 -  08/Sep/2022:20:15:46 +0000 "POST /index.php" 500
libretime-nginx-1       | 192.168.240.1 - - [08/Sep/2022:20:20:10 +0000] "POST /Library/contents-feed HTTP/1.1" 500 1363 "http://localhost:8080/showbuilder" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"

```

**Comment by jooola** [comment]
The formatted SQL query:
```sql
select
	COUNT(*)
from
	((
	select
		PL.id as id,
		name as track_title,
		login as artist_name,
		null::text as album_title,
		null::text as genre,
		length,
		extract(year
	from
		utime)::varchar as year,
		utime,
		mtime,
		'playlist'::varchar as ftype,
		null::int as track_number,
		null::text as mood,
		null::int as bpm,
		null::text as composer,
		null::text as info_url,
		null::int as bit_rate,
		null::int as sample_rate,
		null::text as isrc_number,
		null::text as encoded_by,
		null::text as label,
		null::text as copyright,
		null::VARCHAR as mime,
		null::text as language,
		null::VARCHAR as filepath,
		login as owner_id,
		null::text as conductor,
		null::numeric as replay_gain,
		null::TIMESTAMP as lptime,
		null::boolean as is_playlist,
		null::boolean as is_scheduled,
		null::interval as cuein,
		null::interval as cueout,
		null::text as description,
		null::text as artwork,
		null::text as track_type_id
	from
		cc_playlist as PL
	left join cc_subjs as sub on
		(sub.id = PL.creator_id))
union (
select
	BL.id as id,
	name as track_title,
	login as artist_name,
	null::text as album_title,
	null::text as genre,
	length,
	extract(year
from
	utime)::varchar as year,
	utime,
	mtime,
	'block'::varchar as ftype,
	null::int as track_number,
	null::text as mood,
	null::int as bpm,
	null::text as composer,
	null::text as info_url,
	null::int as bit_rate,
	null::int as sample_rate,
	null::text as isrc_number,
	null::text as encoded_by,
	null::text as label,
	null::text as copyright,
	null::VARCHAR as mime,
	null::text as language,
	null::VARCHAR as filepath,
	login as owner_id,
	null::text as conductor,
	null::numeric as replay_gain,
	null::TIMESTAMP as lptime,
	null::boolean as is_playlist,
	null::boolean as is_scheduled,
	null::interval as cuein,
	null::interval as cueout,
	null::text as description,
	null::text as artwork,
	null::text as track_type_id
from
	cc_block as BL
left join cc_subjs as sub on
	(sub.id = BL.creator_id))
union (
select
FILES.id as id,
track_title,
artist_name,
album_title,
genre,
(cueout - cuein)::interval as length,
year as year,
utime,
mtime,
ftype,
track_number,
mood,
bpm,
composer,
info_url,
bit_rate,
sample_rate,
isrc_number,
encoded_by,
label,
copyright,
mime,
language,
filepath,
sub.login as owner_id,
conductor,
replay_gain,
lptime,
is_playlist,
is_scheduled,
cuein,
cueout,
description,
artwork,
track_type_id
from
cc_files as FILES
left join cc_subjs as sub on
(sub.id = FILES.owner_id)
where
file_exists = 'TRUE'
and hidden = 'FALSE')
union (
select
ws.id as id,
name as track_title,
login as artist_name,
null::text as album_title,
null::text as genre,
length,
extract(year
from
utime)::varchar as year,
utime,
mtime,
'stream'::varchar as ftype,
null::int as track_number,
null::text as mood,
null::int as bpm,
null::text as composer,
null::text as info_url,
null::int as bit_rate,
null::int as sample_rate,
null::text as isrc_number,
null::text as encoded_by,
null::text as label,
null::text as copyright,
mime,
null::text as language,
url as filepath,
login as owner_id,
null::text as conductor,
null::numeric as replay_gain,
lptime,
null::boolean as is_playlist,
null::boolean as is_scheduled,
null::interval as cuein,
null::interval as cueout,
null::text as description,
null::text as artwork,
null::text as track_type_id
from
cc_webstream as ws
left join cc_subjs as sub on
(sub.id = ws.creator_id))) as RESULTS;
```

**Comment by jooola** [comment]
Changing the `null::text as track_type_id` with `null::int as track_type_id` fixes it.
