### ISSUE TITLE
Analyzing playability of some flac files fails on bionic

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2218]
### Describe the bug

The analyzer filed to analyze the play-ability of a flac file using liquidsoap. Liquidsoap seem to crash violently (segfault).

I have tested to upload a mp3 file and it worked, so I guess the flac file was the problem.

### To reproduce

Install on bionic

Upload a flac file

`tail /var/log/syslog` 

### Expected behavior

Analyzer should not crash while analyzing the playability of a flac file

### Relevant log output or error messages

```shell
Oct 10 14:18:12 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:12.195 | INFO     | libretime_analyzer.message_listener:msg_received_callback:101 -  - Received 'b'{"file_id":1,"tmp_file_path":"\\/srv\\/libretime\\/organize\\/1-01-08-Mark_Guiliana-G-Man-LLS.flac","import_directory":"\\/srv\\/libretime\\/\\/imported\\/1","original_filename":"01-08-Mark_Guiliana-G-Man-LLS.flac"}'' on routing_key ''
Oct 10 14:18:13 vagrant kernel: [  406.833094] show_signal_msg: 6 callbacks suppressed
Oct 10 14:18:13 vagrant kernel: [  406.833097] liquidsoap[14163]: segfault at 0 ip 00007f15857f1461 sp 00007ffe9ee038d8 error 4 in libc-2.27.so[7f1585663000+1e7000]
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:13.722 | ERROR    | libretime_analyzer.pipeline._utils:run_:23 - Command '('liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac')' died with <Signals.SIGSEGV: 11>.
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:13.723 | WARNING  | libretime_analyzer.pipeline.analyze_playability:analyze_playability:25 - Command '('liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac')' died with <Signals.SIGSEGV: 11>.
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:13.723 | ERROR    | libretime_analyzer.pipeline.pipeline:run_analysis:97 -
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: Traceback (most recent call last):
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/analyze_playability.py", line 22, in analyze_playability
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_liquidsoap.py", line 9, in _liquidsoap
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return run_(LIQUIDSOAP, *args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │            │       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │            └ ('-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    └ 'liquidsoap'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <function run_ at 0x7f93df81d840>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_utils.py", line 24, in run_
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     raise exception
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_utils.py", line 14, in run_
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     **kwargs,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/lib/python3.6/subprocess.py", line 438, in run
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     output=stdout, stderr=stderr)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │              └ ''
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ ''
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: subprocess.CalledProcessError: Command '('liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac')' died with <Signals.SIGSEGV: 11>.
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: The above exception was the direct cause of the following exception:
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: Traceback (most recent call last):
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/bin/libretime-analyzer", line 33, in <module>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     sys.exit(load_entry_point('libretime-analyzer==3.0.0b2', 'console_scripts', 'libretime-analyzer')())
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │    └ <function importlib_load_entry_point at 0x7f93e46e8e18>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   └ <built-in function exit>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <module 'sys' (built-in)>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return self.main(*args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │     │       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │     └ ()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    └ <function BaseCommand.main at 0x7f93e18d9620>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1053, in main
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     rv = self.invoke(ctx)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          │    │      └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          │    └ <function Command.invoke at 0x7f93e18dd0d0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1395, in invoke
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return ctx.invoke(self.callback, **ctx.params)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    │           │   └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/libret...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    │           └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    └ <function cli at 0x7f93df3872f0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   └ <function Context.invoke at 0x7f93e18d6e18>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 754, in invoke
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return __callback(*args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                        │       └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/libret...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                        └ ()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/main.py", line 44, in cli
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     MessageListener(config)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │               └ Config(general=GeneralConfig(public_url=AnyHttpUrl('http://192.168.10.100:8080', scheme='http', host='192.168.10.100', host_t...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <class 'libretime_analyzer.message_listener.MessageListener'>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 37, in __init__
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self.wait_for_messages()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function MessageListener.wait_for_messages at 0x7f93df386ea0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <libretime_analyzer.message_listener.MessageListener object at 0x7f93dead1b00>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 81, in wait_for_messages
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._channel.start_consuming()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    │        └ <function BlockingChannel.start_consuming at 0x7f93df8257b8>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <libretime_analyzer.message_listener.MessageListener object at 0x7f93dead1b00>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1880, in start_consuming
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._process_data_events(time_limit=None)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function BlockingChannel._process_data_events at 0x7f93df825950>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 2041, in _process_data_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self.connection.process_data_events(time_limit=time_limit)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    │                                         └ None
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <property object at 0x7f93df894638>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 848, in process_data_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._dispatch_channel_events()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function BlockingConnection._dispatch_channel_events at 0x7f93df893488>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingConnection impl=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport obj...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     impl_channel._get_cookie()._dispatch_events()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │            └ <function Channel._get_cookie at 0x7f93df8e9378>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport ...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1508, in _dispatch_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     evt.properties, evt.body)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │           │   └ <member 'body' of '_ConsumerDeliveryEvt' objects>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │           └ <pika.adapters.blocking_connection._ConsumerDeliveryEvt object at 0x7f93df345e08>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   └ <member 'properties' of '_ConsumerDeliveryEvt' objects>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <pika.adapters.blocking_connection._ConsumerDeliveryEvt object at 0x7f93df345e08>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 124, in msg_received_callback
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     original_filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 173, in spawn_analyzer_process
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     original_filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: > File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/pipeline.py", line 83, in run_analysis
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     metadata = analyze_playability(audio_file_path, metadata)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                │                   │                └ {'ftype': 'audioclip', 'hidden': False, 'filesize': 47516861, 'md5': '4598bd6af17acfa26d784df31edeb43f', 'mime': 'audio/flac'...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                │                   └ '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                └ <function analyze_playability at 0x7f93df841268>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/analyze_playability.py", line 26, in analyze_playability
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     raise UnplayableFileError() from exception
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:           └ <class 'libretime_analyzer.pipeline.analyze_playability.UnplayableFileError'>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: libretime_analyzer.pipeline.analyze_playability.UnplayableFileError
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:13.736 | ERROR    | libretime_analyzer.message_listener:spawn_analyzer_process:177 - Analyzer pipeline exception:
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: Traceback (most recent call last):
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/analyze_playability.py", line 22, in analyze_playability
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_liquidsoap.py", line 9, in _liquidsoap
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return run_(LIQUIDSOAP, *args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │            │       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │            └ ('-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    └ 'liquidsoap'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <function run_ at 0x7f93df81d840>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_utils.py", line 24, in run_
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     raise exception
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/_utils.py", line 14, in run_
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     **kwargs,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/lib/python3.6/subprocess.py", line 438, in run
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     output=stdout, stderr=stderr)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │              └ ''
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ ''
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: subprocess.CalledProcessError: Command '('liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac')' died with <Signals.SIGSEGV: 11>.
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: The above exception was the direct cause of the following exception:
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: Traceback (most recent call last):
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/bin/libretime-analyzer", line 33, in <module>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     sys.exit(load_entry_point('libretime-analyzer==3.0.0b2', 'console_scripts', 'libretime-analyzer')())
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │    └ <function importlib_load_entry_point at 0x7f93e46e8e18>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   └ <built-in function exit>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <module 'sys' (built-in)>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return self.main(*args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │     │       └ {}
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    │     └ ()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │    └ <function BaseCommand.main at 0x7f93e18d9620>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1053, in main
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     rv = self.invoke(ctx)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          │    │      └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          │    └ <function Command.invoke at 0x7f93e18dd0d0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:          └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1395, in invoke
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return ctx.invoke(self.callback, **ctx.params)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    │           │   └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/libret...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    │           └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      │    └ <function cli at 0x7f93df3872f0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   │      └ <Command cli>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            │   └ <function Context.invoke at 0x7f93e18d6e18>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:            └ <click.core.Context object at 0x7f93e2fe1160>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 754, in invoke
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     return __callback(*args, **kwargs)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                        │       └ {'log_filepath': PosixPath('/var/log/libretime/analyzer.log'), 'log_level': 'info', 'config_filepath': PosixPath('/etc/libret...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                        └ ()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/main.py", line 44, in cli
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     MessageListener(config)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │               └ Config(general=GeneralConfig(public_url=AnyHttpUrl('http://192.168.10.100:8080', scheme='http', host='192.168.10.100', host_t...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <class 'libretime_analyzer.message_listener.MessageListener'>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 37, in __init__
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self.wait_for_messages()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function MessageListener.wait_for_messages at 0x7f93df386ea0>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <libretime_analyzer.message_listener.MessageListener object at 0x7f93dead1b00>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 81, in wait_for_messages
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._channel.start_consuming()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    │        └ <function BlockingChannel.start_consuming at 0x7f93df8257b8>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <libretime_analyzer.message_listener.MessageListener object at 0x7f93dead1b00>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1880, in start_consuming
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._process_data_events(time_limit=None)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function BlockingChannel._process_data_events at 0x7f93df825950>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 2041, in _process_data_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self.connection.process_data_events(time_limit=time_limit)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    │                                         └ None
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <property object at 0x7f93df894638>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingChannel impl=<Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._As...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 848, in process_data_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     self._dispatch_channel_events()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │    └ <function BlockingConnection._dispatch_channel_events at 0x7f93df893488>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <BlockingConnection impl=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport obj...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     impl_channel._get_cookie()._dispatch_events()
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │            └ <function Channel._get_cookie at 0x7f93df8e9378>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport ...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1508, in _dispatch_events
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     evt.properties, evt.body)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │           │   └ <member 'body' of '_ConsumerDeliveryEvt' objects>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   │           └ <pika.adapters.blocking_connection._ConsumerDeliveryEvt object at 0x7f93df345e08>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     │   └ <member 'properties' of '_ConsumerDeliveryEvt' objects>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ <pika.adapters.blocking_connection._ConsumerDeliveryEvt object at 0x7f93df345e08>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 124, in msg_received_callback
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     original_filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: > File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/message_listener.py", line 173, in spawn_analyzer_process
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     original_filename,
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     └ '01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/pipeline.py", line 100, in run_analysis
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     raise exception
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/pipeline.py", line 83, in run_analysis
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     metadata = analyze_playability(audio_file_path, metadata)
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                │                   │                └ {'ftype': 'audioclip', 'hidden': False, 'filesize': 47516861, 'md5': '4598bd6af17acfa26d784df31edeb43f', 'mime': 'audio/flac'...
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                │                   └ '/srv/libretime/organize/1-01-08-Mark_Guiliana-G-Man-LLS.flac'
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:                └ <function analyze_playability at 0x7f93df841268>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:   File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer/pipeline/analyze_playability.py", line 26, in analyze_playability
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:     raise UnplayableFileError() from exception
Oct 10 14:18:13 vagrant libretime-analyzer[13889]:           └ <class 'libretime_analyzer.pipeline.analyze_playability.UnplayableFileError'>
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: libretime_analyzer.pipeline.analyze_playability.UnplayableFileError
Oct 10 14:18:13 vagrant libretime-analyzer[13889]: 2022-10-10 14:18:13.771 | INFO     | libretime_analyzer.status_reporter:send_http_request:106 - HTTP request sent successfully.
```

### LibreTime version

3.0.0-beta.2

### Installation method and OS / Environment

Operating system:
Method:

### Client Environment

Operating system:
Browser:

**Comment by jooola** [comment]
This only happens on some specific FLAC files, not all.

@paddatrapper I don't think I'll be able to fix liquidsoap on bionic, should we ship this small bug in 3.0.0 ?

**Comment by jooola** [comment]
We do not support Bionic anymore, please upgrade.
