### ISSUE TITLE
"operator does not exist" error when filtering by track type

### ISSUE THREAD

**Issue by rjhelms** [libretime/libretime#2344]
### Describe the bug

Searching by track type from Dashboard > Tracks causes the panel to become unresponsive with a spinning load indicator.  Network tools reveals a 500 error is returned by `/Library/contents-feed`.

Everytime this happens, an error is logged in `legacy.log`. Example included below. The error seems similar to the one addressed in #2111, but from a different query, and does affect user interface.

### To reproduce

1. Go to Dashboard - Tracks
2. Click on dropdown in search box
3. Select a track type 
4. UI spins indefinitely, with 500 error received from `/Library/contents-feed`. Errors logged as listed below.

### Expected behavior

Tracks panel reloads filtered by selected track type.

### Relevant log output or error messages

```shell
postgres-12-main.log:

2023-01-06 21:03:15.492 UTC [41150] airtime@airtime ERROR:  operator does not exist: integer ~~* unknown at character 555
2023-01-06 21:03:15.492 UTC [41150] airtime@airtime HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
2023-01-06 21:03:15.492 UTC [41150] airtime@airtime STATEMENT:  SELECT COUNT(*)  FROM (SELECT FILES.id AS id,track_title,artist_name,album_title,genre,(cueout - cuein)::INTERVAL AS length,year AS year,utime,mtime,ftype,track_number,mood,bpm,composer,info_url,bit_rate,sample_rate,isrc_number,encoded_by,label,copyright,mime,language,filepath,sub.login AS owner_id,conductor,replay_gain,lptime,is_playlist,is_scheduled,cuein,cueout,description,artwork,track_type_id FROM cc_files AS FILES LEFT JOIN cc_subjs AS sub ON (sub.id = FILES.owner_id) WHERE file_exists = 'TRUE' AND hidden='FALSE') AS File WHERE track_type_id ILIKE $1


legacy.log:

2023-01-06T21:03:15+00:00 INFO (6): SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~* unknown
LINE 1: ...UE' AND hidden='FALSE') AS File WHERE track_type_id ILIKE $1
                                                               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
2023-01-06T21:03:15+00:00 NOTICE (5): Undefined variable: totalDisplayRows
2023-01-06T21:03:15+00:00 ERR (3): [ErrorController.php:28 - errorAction()] - Undefined variable: totalDisplayRows
2023-01-06T21:03:15+00:00 ERR (3): [ErrorController.php:29 - errorAction()] - #0 /usr/share/libretime/legacy/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 /usr/share/libretime/legacy/application/models/Datatables.php(211): Zend_Log->errorHandler()
#2 /usr/share/libretime/legacy/application/models/StoredFile.php(818): Application_Model_Datatables::findEntries()
#3 /usr/share/libretime/legacy/application/controllers/LibraryController.php(328): Application_Model_StoredFile::searchLibraryFiles()
#4 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LibraryController->contentsFeedAction()
#5 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#6 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#7 /usr/share/libretime/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#8 /usr/share/libretime/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#9 /usr/share/libretime/legacy/application/airtime-boot.php(77): Zend_Application->run()
#10 /usr/share/libretime/legacy/public/index.php(56): require_once('/usr/share/libr...')
#11 {main}
2023-01-06T21:03:15+00:00 ERR (3): [ErrorController.php:62 - errorAction()] - An internal application error has occurred.: ErrorException: Undefined variable: totalDisplayRows in /usr/share/libretime/legacy/application/models/Datatables.php:211
Stack trace:
#0 /usr/share/libretime/legacy/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 /usr/share/libretime/legacy/application/models/Datatables.php(211): Zend_Log->errorHandler()
#2 /usr/share/libretime/legacy/application/models/StoredFile.php(818): Application_Model_Datatables::findEntries()
#3 /usr/share/libretime/legacy/application/controllers/LibraryController.php(328): Application_Model_StoredFile::searchLibraryFiles()
#4 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LibraryController->contentsFeedAction()
#5 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#6 /usr/share/libretime/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#7 /usr/share/libretime/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#8 /usr/share/libretime/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#9 /usr/share/libretime/legacy/application/airtime-boot.php(77): Zend_Application->run()
#10 /usr/share/libretime/legacy/public/index.php(56): require_once('/usr/share/libr...')
#11 {main}
```

### LibreTime version

3.0.1

### Installation method and OS / Environment

Operating system: Ubuntu 20.04.5 LTS
Method: installed from 3.0.1 tarball, upgrading over 3.0.0-alpha12 install

### Client Environment

Operating system: Windows 10 x64
Browser: Chrome 108.0.5359.125

### Screenshots

UI after selecting a track type in search:
![image](https://user-images.githubusercontent.com/8541186/211100227-3df29b5a-048a-40b6-b27f-511e4df9abaf.png)

**Comment by rjhelms** [comment]
Seems like this is caused because `buildWhereClauseForAdvancedSearch` does not have any case to handle integer search fields, so comparison is being done with `ILIKE`:
https://github.com/libretime/libretime/blob/86ceac76d8e1c3da7eff186daa2b1bd76551bc26/legacy/application/models/Datatables.php#L52-L54

Hacky workaround working on my environment is to cast the DB value to text for this query, ie change line 53 to:
`$where['clause'][$dbname] = $dbname . '::text ILIKE :' . $dbname . '1';`

**Comment by jooola** [comment]
Yes, good catch ! The buildWhereClauseForAdvancedSearch function didn't support matching against the track type id!

Thanks for the ticket.
