### ISSUE TITLE
CORS error when running Apache on port other than 80

### ISSUE THREAD

**Issue by jesseward** [LibreTime/libretime#238]
I have configured Apache2 to run on a non-standard port (binding to TCP 2080).  When running as such the initial login fails with the following exception raised from https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/common/CORSHelper.php#L10  

I have added addition logging that dumps the origin that fails the conditional check.
`2017-06-17T15:20:39+00:00 ERR (3): x.x.x.x [CORSHelper.php:14 - enableCrossOriginRequests()] - CORS origin=http://X.X.X.X:2080` 

If i remove the CORS check and validate my session, Airtime operates without issue. 

Full stack for reference.

```2017-06-17T14:52:53+00:00 ERR (3): x.x.x.x[ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2017-06-17T14:52:53+00:00 ERR (3): x.x.x.x [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: exception 'Zend_Controller_Action_Exception' with message 'Forbidden' in /usr/share/airtime/php/airtime_mvc/application/common/CORSHelper.php:14
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}```

**Comment by hairmare** [comment]
That preg_match might need to be be more flexible as to what ports are used, it really only covers the basic default localhost cases ala "what the installer does out of the box".

I never saw any similar errors with the vagrant install that is using 8080 (a non default port).
Is this happening on an url containing `localhost`? Is your install behind a proxy or is there any kind of local NATing/port-rewriting going on that could interfere? 

Anyway, we should probably find a better regex than the current one. Please PR any improvements ;)

A quick work-around would be to use a different hostname (ie. libretime.vcap.me:2080) that resolves to 127.0.0.1. I'm still not 100% sure I can explain your issues 😞
