### ISSUE TITLE
RabbitMQ settings ignored from config

### ISSUE THREAD

**Issue by John2143** [LibreTime/libretime#245]
When configuring libretime, I tried to use a unique rabbitmq password for extra security, but when uploading a file the default settings are still used as seen by the line `__construct('airtime', 'airtime', '/airtime', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)`

```
2017-07-15T03:19:33-04:00 INFO (6): radm.additappamusic.com Checking autoplaylist poll
2017-07-15T03:19:38-04:00 INFO (6): radm.additappamusic.com Moving file /tmp/phpJRwDlZ to /srv/airtime/stor/organize/Silent.wav
2017-07-15T03:19:38-04:00 ERR (3): radm.additappamusic.com [MediaController.php:160 - postAction()] - ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '??oACCESS_REFUS...', NULL)
#3 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(213): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection->__construct('airtime', 'airtime', '/airtime', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#6 /usr/share/airtime/php/airtime_mvc/application/models/RabbitMq.php(108): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('127.0.0.1', '5672', 'airtime', 'airtime', '/airtime')
#7 /usr/share/airtime/php/airtime_mvc/application/services/MediaService.php(46): Application_Model_RabbitMq::SendMessageToAnalyzer('/srv/airtime/st...', '/srv/airtime/st...', 'Silent.wav', 'http://radm.add...', '36DGSRPMEGI7BWU...', 'file', '')
#8 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(160): Application_Service_MediaService::importFileToLibrary('http://radm.add...', '/tmp/phpJRwDlZ', 'Silent.wav', 1, false)
#9 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(99): CcFiles::createAndImport(Array, '/tmp/phpJRwDlZ', 'Silent.wav')
#10 /usr/share/airtime/php/airtime_mvc/application/modules/rest/controllers/MediaController.php(144): CcFiles::createFromUpload(Array)
#11 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#12 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#13 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#14 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#15 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#16 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#17 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#18 {main}
```

Heres the relevant bits of the /etc/airtime/airtime.conf

```
[rabbitmq]
host = 127.0.0.1
port = 5672
user = airtime
password = not_the_word_airtime
vhost = /airtime
````

In the end I just set my rabbitmq password back to airtime and it seems to work fine now. If it helps to trace, the error message I received when uploading was this: https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/modules/rest/controllers/MediaController.php#L276

**Comment by hairmare** [comment]
There is also `/etc/airtime/rabbitmq-analyzer.ini ` which seems to be used for [the connection to analyzer exclusively](https://github.com/LibreTime/libretime/blob/01a954481c3929b35c6b08bb7b7fab6619f68bff/airtime_mvc/application/models/RabbitMq.php#L91). This was probably part of SaaS running a centralized instance of analyzer on a separate rabbitmq instance.

Also, could the installer have been too eager and [changed](https://github.com/LibreTime/libretime/blob/6e2cb2b2a80442f5a5aa9e181649393bdabd6ea7/install#L1017) your secure password back?

**Comment by John2143** [comment]
I don't believe it is the installer changing it as I manually changed the password using rabbitmqctl, but the separate config is probably the issue here. Seems kinda strange to have two configs that seemingly do the same thing. I guess I'll go ahead and change both my configs and close the issue.

**Comment by hairmare** [comment]
>  Seems kinda strange to have two configs that seemingly do the same thing.

It is strange, yes. Rewriting the config parts is somewhere on the agenda. It's a bit of a cross cutting concern since both the php parts and the python parts need to be taken care of and tested.
