### ISSUE TITLE
Request entity too large when runnning `bulk_import`

### ISSUE THREAD

**Issue by Soneji** [libretime/libretime#2574]
### Describe the bug

I have just set up a new install of libretime using the docker installation instructions and I am trying to import my media but it says the file size is too large. I think it could be an issue in the `php` config which I can see is set as follows:

```ini
post_max_size = 8M
; http://php.net/upload-max-filesize
upload_max_filesize = 2M
max_file_uploads = 20
```
in `/usr/local/etc/php/php.ini` in the legacy container. 

I am not sure how to change it without restarting the container and then losing my config :(

The filesize is `127M` which is below the nginx so that's why I think the limit is being hit with php config. 

### To reproduce

```bash
dc exec -it api libretime-api bulk_import --path /srv/libretime/sbks
Traceback (most recent call last):
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 99, in _upload_file
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://radio.com/rest/media

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/libretime-api", line 8, in <module>
    sys.exit(main())
  File "/src/libretime_api/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 66, in handle
    importer.import_dir(Path(path).resolve(), library, allowed_extensions)
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 160, in import_dir
    self._walk_dir(path, library, allowed_extensions)
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 142, in _walk_dir
    self._handle_file(sub_path.resolve(), library)
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 120, in _handle_file
    self._upload_file(filepath, library)
  File "/src/libretime_api/storage/management/commands/bulk_import.py", line 102, in _upload_file
    raise RuntimeError(f"could not upload {filepath}") from exception
RuntimeError: could not upload /srv/libretime/sbks/myfile.mp3
```

### Expected behavior

File upload successfully

### LibreTime version

3.1.0

### Installation method and OS / Environment

Operating system: Ubuntu
Method: Docker compose

**Comment by jooola** [comment]
Hi,
This is weird, we do add an extra configuration to rise the upload limit to 512M:
https://github.com/libretime/libretime/blob/001466f8fd1074ecfb6dfdcfb94872effc3fc9e9/legacy/install/php/libretime-legacy.ini
https://github.com/libretime/libretime/blob/001466f8fd1074ecfb6dfdcfb94872effc3fc9e9/Dockerfile#L267

I'll try to reproduce.

**Comment by jooola** [comment]
Could you please paste the logs from the nginx container as well as the legacy container ?

**Comment by Soneji** [comment]
```log
sbks-legacy-1      | 172.22.0.11 -  31/May/2023:12:27:01 +0000 "POST /index.php" 200
sbks-nginx-1       | 172.22.0.5 - - [31/May/2023:12:27:01 +0000] "POST /api/push-stream-stats?format=json HTTP/1.1" 200 95 "-" "python-requests/2.31.0" "-"
sbks-legacy-1      | 172.22.0.11 -  31/May/2023:12:27:01 +0000 "GET /index.php" 200
sbks-nginx-1       | 172.22.0.5 - - [31/May/2023:12:27:01 +0000] "GET /api/update-metadata-on-tunein?format=json HTTP/1.1" 200 13 "-" "python-requests/2.31.0" "-"
```

**Comment by Soneji** [comment]
So for some reason there are no log entries being output when I run the api command. Strange
