### ISSUE TITLE
Can't upload file on a fresh install of alpha 2 on ubuntu-trusty

### ISSUE THREAD

**Issue by rafaeletc** [LibreTime/libretime#265]
Even on vagrant i can't upload no more, how can I debug this?
The files are showing up on "/srv/airtime/stor/organize/" but don't are populating the libretime's media list

**Comment by rafaeletc** [comment]
just figure out that all log files from services are located at /var/log/upstart
so, i found a error on airtime_analyzer.log, that i reproduce below:
> Airtime Analyzer 1.0
Traceback (most recent call last):
  File "/usr/bin/airtime_analyzer", line 4, in <module>
    __import__('pkg_resources').run_script('airtime-analyzer==0.1', 'airtime_analyzer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 73, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 51, in run
    debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/airtime_analyzer.py", line 45, in __init__
    self._msg_listener = MessageListener(rmq_config, cloud_storage_config)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 89, in __init__
    self.connect_to_messaging_server()
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 113, in connect_to_messaging_server
    self._channel.exchange_declare(exchange=EXCHANGE, type=EXCHANGE_TYPE, durable=True)
TypeError: exchange_declare() got an unexpected keyword argument 'type'

**Comment by rafaeletc** [comment]
just figured out with this closed issue: https://github.com/LibreTime/libretime/issues/256

**Comment by rafaeletc** [comment]
Now i'm stucked here:

> 2017-08-07 11:46:54,228 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/srv\/airtime\/stor\/organize\/Wild Sugar - Bring It Here.mp3","storage_backend":"file","import_directory":"\/srv\/airtime\/stor\/\/imported\/1","original_filename":"Wild Sugar - Bring It Here.mp3","callback_url":"http:\/\/radio.afroativismodigital.live\/\/rest\/media\/33","api_key":"PJCW9J08UDNQ7CQWFT6I","file_prefix":""}' on routing_key ''
2017-08-07 11:46:54,270 [analyzer_pipeline] [ERROR]  'module' object has no attribute 'open'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 70, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 44, in analyze
    ms = magic.open(magic.MIME_TYPE)
AttributeError: 'module' object has no attribute 'open'
2017-08-07 11:46:54,270 [message_listener] [ERROR]  Analyzer pipeline exception: 'module' object has no attribute 'open'
2017-08-07 11:46:54,360 [status_reporter] [INFO ]  HTTP request sent successfully.

**Comment by rafaeletc** [comment]
I think that is a problem with python-magic version

**Comment by hairmare** [comment]
#166 might be related to this. Is the `python-magic` package installed on your system?

It looks like we forgot to add the package to the installer's os package requirements.

I'm not sure why it wouldn't work with the `file-magic` pypi package that the installer probably installed on your system 😕 (it's newer than what the OS bundle but our code should support them both).

**Comment by rafaeletc** [comment]
Both the pypi and ubuntu-trusty versions have the same version of `file-magic`

After format and reinstall the server, everything goes ok, just installed the package `python-pika` before de libretime install (i'm using the git master branch)

**Comment by hairmare** [comment]
Yeah, file magic versioning can be a bit weird. 

Apt installs the python-magic package based on the version of magic it is bundled with (`5.11` or higher). WThe actual lib is published on pypi with it's "internal" version from [setup.py](https://github.com/file/file/blob/8ce3fbe21b065e00bb7f954578e343fa704bbce9/python/setup.py) (0.3.0 atm). That https://github.com/file/file has weird release tags and the docs are a pain to find doesn't help either 😒 

We should probably add `python-magic` to the installer even if they install the same thing. If it only guards against updates ala pika that seems fine as well.
