### ISSUE TITLE
RabbitMq settings are not saved if you return to the form and statuspage crashes

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#288]
I was performing a LibreTime install. Clicked through the rabbitmq page and then went back and changed the password. The new password was not saved by the installer and the systemstatus page crashes with the following error.

```
2017-09-06T16:11:23+00:00 ERR (3): x.x.x.x [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.' in /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:661
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '??oACCESS_REFUS...', NULL)
#3 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(213): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection->__construct('airtime', 'airtime', '/airtime', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#6 /usr/share/airtime/php/airtime_mvc/build/airtime-setup/load.php(105): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('127.0.0.1', '5672', 'airtime', 'airtime', '/airtime')
#7 /usr/share/airtime/php/airtime_mvc/build/airtime-setup/load.php(57): checkRMQConnection()
#8 /usr/share/airtime/php/airtime_mvc/application/views/scripts/systemstatus/index.phtml(7): checkExternalServices()
#9 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View.php(157): include('/usr/share/airt...')
#10 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/usr/share/airt...')
#11 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('systemstatus/in...')
#12 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('systemstatus/in...', NULL)
#13 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#17 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#18 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#19 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#20 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#21 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#22 {main}

```

**Comment by Robbt** [comment]
Been working on the install and I am able to move back and forth so I think this was fixed already with my previous commit.
