### ISSUE TITLE
Nginx listening port error

### ISSUE THREAD

**Issue by matias-tecnosoul** [libretime/libretime#2914]
### Describe the bug

In a fresh v4.0.0 install I couln´t import tracks. I was getting` [Errno 111] Connection refused messages`.
I saw that the port it was trying to access was 80 instead of the new default 8080.
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='domain.name', port=80`
So i added port 80 to the 8080 in nginx and the issue was solved (I have both ports listening).

### To reproduce

Install a fresh v4.0.0 and try to upload a new track.
The track stays in "pending import". 

### Expected behavior

Upload and import tracks correctly.

### Relevant log output or error messages

```shell
==> /var/log/libretime/analyzer.log <==
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/libretime/lib/python3.9/site-packages/libretime_analyzer/status_reporter.py", line 106, in send_http_request
    resp = session.send(
  File "/opt/libretime/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/libretime/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='domain.name', port=80): Max retries exceeded with url: /rest/media/2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd1dad5d00>: Failed to establish a new connection: [Errno 111] Connection refused'))

==> /var/log/libretime/liquidsoap.log <==
2024-01-25 07:55:03,116 | ERROR    | libretime_api_client._client:_request:93 - HTTPConnectionPool(host='domain.name', port=80): Max retries exceeded with url: /api/v2/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f810ded3250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-25 07:55:06,087 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a33ac40>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/info
2024-01-25 07:55:10,089 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a33adf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/info
2024-01-25 07:55:18,097 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a33a0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/info
2024-01-25 07:55:34,115 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a33a310>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/info
2024-01-25 07:56:06,148 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a33a430>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/info
2024-01-25 07:56:06,151 | ERROR    | libretime_api_client._client:_request:93 - HTTPConnectionPool(host='domain.name', port=80): Max retries exceeded with url: /api/v2/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc31a1de250>: Failed to establish a new connection: [Errno 111] Connection refused'))

==> /var/log/libretime/worker.log <==
[2024-01-24 22:11:40,987: ERROR/MainProcess] consumer: Cannot connect to amqp://libretime:**@127.0.0.1:5672//libretime: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

==> /var/log/libretime/playout.log <==
2024-01-25 07:56:30,804 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d771e7fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/version?format=json
2024-01-25 07:56:30,805 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d771ff4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/version?format=json
2024-01-25 07:56:30,807 | WARNING  | urllib3.connectionpool:urlopen:871 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d771ff400>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/version?format=json
2024-01-25 07:56:30,809 | ERROR    | libretime_api_client._client:_request:93 - HTTPConnectionPool(host='domain.name', port=80): Max retries exceeded with url: /api/version?format=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d77169520>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### LibreTime version

4.0.0

### Installation method and OS / Environment

Operating system: Debian bullseye in a LXC with LVM
Method: installer script

### Client Environment

Operating system:
Browser:

**Comment by jooola** [comment]
I cannot reproduce this, or you have a specific setup that you didn't describe in your ticket.

Note that you should setup a reverse proxy in front of libretime, as recommended by the docs.
