### ISSUE TITLE
Running database migration after importing Airtime database deletes the data 

### ISSUE THREAD

**Issue by HighTechHarmony** [libretime/libretime#3121]
### Describe the bug

When trying to migrate from airtime per [the migrate from airtime document ](https://libretime.org/docs/admin-manual/install/migrate-from-airtime/), I import the airtime database, run the migration, and I am then left with a blank, fresh install of libretime, with the restored data from airtime being totally absent.  I also checked to see if the airtime database was somehow present under a different name, such as ```airtime``` instead of ```libretime```, this did not appear to be the case.

### To reproduce

On the previous airtime server to be migrated, the airtime database is backed up using a command similar to the following:
``` sudo -u postgres pg_dump --no-owner --no-privileges airtime > airtime.sql ```

1. Do a plain install of Ubuntu 20.04.5-amd64 to a VM.  The aforementioned database dump file is copied to the file system somewhere on the new VM.
2. Set the timezone, configure static IP, setup a DNS entry for "libretime" to resolve to this host,
3. Do all system updates ```apt-get update && apt dist-upgrade``` and reboot
```sudo apt-get install postgresql-contrib```
4. Download https://github.com/libretime/libretime/releases/download/4.2.0/libretime-4.2.0.tar.gz and extract
```cd libretime``` and run the installer:
```sudo ./install --listen-port 8080 http://libretime:8080```
5. Wait for installation to complete, no errors are seen during the process
6. Restore the airtime database dump file, per the documentation: ``` sudo -u libretime libretime-api dbshell < airtime.sql```
7. Observe that this takes some time, and from the output that tables appear to be created and altered
NOTE: Despite being specified in the documentation, I skipped restoring the storage itself for brevity at this point, because I conjectured that it would have no impact on the particular issue I am dealing with. 
8. Verify that there is data present in the libretime database.  Specifiically, open the dbshell:
``` sudo -u libretime libretime-api dbshell ```
Connect to libretime database:
``` \c libretime ```
Select some know data from a table:
``` select * from cc_show limit 10```
Observe that there are shows in the table that were imported from the airtime database dump.  
9. Exit the dbshell and proceed with the documentation order to apply database migrations:
``` sudo -u libretime libretime-api migrate```
10. Reenter the dbshell and repeat the previous test to select from cc_show
``` select * from cc_show limit 10```
11. Observe that there are no shows in the table.

Furthermore it appears evident after proceeding with the remainder of the documented procedure, authenticating and browsing the web console, that the whole system is in an out-of-the-box state.

### Expected behavior

Expected the database data from airtime to be present but converted into a usable form for libretime to (mostly) begin functioning as a replacement for the airtime server being migrated.  For example, one could log into the libretime web interface and see upcoming show instances on the calendar that were created/present from the airtime system.  Instead, it appears to be a fresh install. If other steps are required to convert the airtime data, I would expect this to be in the documentation between the restore of the database and the application of the database migrations.  Otherwise I may be misunderstanding the point of this document.

I would expect this to be the case even if the storage was missing, and if operation was attempted, I would just see errors in the logs related to files not being found.

This issue appears to occur regardless of whether the libretime install is deployed on Ubuntu 20.04 or Debian 11.

### Relevant log output or error messages

```shell

root@libretimedeb:~# sudo -u libretime libretime-api migrate
Operations to perform:
  Apply all migrations: auth, contenttypes, legacy, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying legacy.0001_initial... OK
  Applying legacy.0003_2_5_2... OK
  Applying legacy.0004_2_5_3... OK
  Applying legacy.0005_2_5_4... OK
  Applying legacy.0006_2_5_5... OK
  Applying legacy.0007_2_5_9... OK
  Applying legacy.0008_2_5_10... OK
  Applying legacy.0009_2_5_11... OK
  Applying legacy.0010_2_5_12... OK
  Applying legacy.0011_2_5_13... OK
  Applying legacy.0012_2_5_14... OK
  Applying legacy.0013_2_5_15... OK
  Applying legacy.0014_2_5_16... OK
  Applying legacy.0015_2_5_17... OK
  Applying legacy.0016_3_0_0_alpha... OK
  Applying legacy.0017_3_0_0_alpha_1... OK
  Applying legacy.0018_3_0_0_alpha_6... OK
  Applying legacy.0019_3_0_0_alpha_7... OK
  Applying legacy.0020_3_0_0_alpha_7_1... OK
  Applying legacy.0021_3_0_0_alpha_7_2... OK
  Applying legacy.0022_3_0_0_alpha_7_3... OK
  Applying legacy.0023_3_0_0_alpha_9_1... OK
  Applying legacy.0024_3_0_0_alpha_9_2... OK
  Applying legacy.0025_3_0_0_alpha_9_3... OK
  Applying legacy.0026_3_0_0_alpha_9_4... OK
  Applying legacy.0027_3_0_0_alpha_13_1... OK
  Applying legacy.0028_3_0_0_alpha_13_2... OK
  Applying legacy.0029_3_0_0_alpha_13_3... OK
  Applying legacy.0030_3_0_0_alpha_13_4... OK
  Applying legacy.0031_3_0_0_alpha_13_5... OK
  Applying legacy.0032_3_0_0_alpha_13_6... OK
  Applying legacy.0033_3_0_0_alpha_13_7... OK
  Applying legacy.0034_3_0_0_alpha_13_8... OK
  Applying legacy.0035_3_0_0_alpha_13_9... OK
  Applying legacy.0036_3_0_0_alpha_13_10... OK
  Applying legacy.0037_move_stream_settings_to_preferences... OK
  Applying legacy.0038_remove_stream_settings_liquidsoap_status... OK
  Applying legacy.0039_remove_stream_settings_stats_status... OK
  Applying legacy.0040_bump_legacy_schema_version... OK
  Applying legacy.0041_drop_stream_setting_table... OK
  Applying legacy.0042_remove_stream_preferences... OK
  Applying legacy.0043_remove_cors_preference... OK
  Applying legacy.0044_add_track_types_analyzer_options... OK
  Applying legacy.0045_add_sessions_table... OK
  Applying sessions.0001_initial... OK



libretime=> \c postgres
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
You are now connected to database "postgres" as user "libretime".
postgres=> \list
                                  List of databases
   Name    |   Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+-----------+----------+-------------+-------------+-----------------------
 libretime | libretime | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |           |          |             |             | postgres=CTc/postgres
 template1 | postgres  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |           |          |             |             | postgres=CTc/postgres
(4 rows)

libretime=> select * from cc_show limit 10;
 id | name | url | genre | description | color | background_color | live_stream_using_airtime_auth | live_stream_using_custom_auth | live_stream_user | live_stream_pass | linked | is_linkable | image_path | has_autoplaylist | autoplaylist_id | autoplaylist_repeat 
----+------+-----+-------+-------------+-------+------------------+--------------------------------+-------------------------------+------------------+------------------+--------+-------------+------------+------------------+-----------------+---------------------
(0 rows)
```

### LibreTime version

4.2.0

### Installation method and OS / Environment

Operating system: Ubuntu 20.04.5
Method: manual installation from tarball

### Client Environment

Operating system: Linux Mint 21
Browser: Chrome

### Screenshots

![2024-12-08_23-32](https://github.com/user-attachments/assets/f5889bf4-c417-402e-9471-a06c50a8ad6a)

**Comment by HighTechHarmony** [comment]
I did a little more digging, and I believe this is what is actually happening:

1. In the migration 000_initial, there is a function called create_schema that calls get_schema
2. If the return value of this function is not "None", it does not attempt to load the schema apparently (because this is the indicator that there is already data present).
```
def create_schema(_apps, _schema_editor):
    schema_version = get_schema_version()

    # A schema already exists, don't overwrite !
    if schema_version is not None:
        return
```
3. If the return is None, it proceeds to load schema.sql and data.sql
```with connection.cursor() as cursor:
        for migration_filename in ("schema.sql", "data.sql"):
            raw = (here / "sql" / migration_filename).read_text(encoding="utf-8")
            cursor.execute(raw)
```
4. In this case, schema.sql **drops all the tables** and recreates them:
```
DROP TABLE IF EXISTS "cc_files" CASCADE;

CREATE TABLE "cc_files"
(
    "id" serial NOT NULL,
    "name" VARCHAR(255) DEFAULT '' NOT NULL,
    "mime" VARCHAR(255) DEFAULT '' NOT NULL,
    "ftype" VARCHAR(128) DEFAULT '' NOT NULL,
    "filepath" TEXT DEFAULT '',
```
etc.

6. Here's the crux:  The get_schema function looks for something called schema_version in cc_pref and returns None if it doesn't find it
```
def get_schema_version():
    """
    Get the schema version from a legacy database.

    Don't use django models as they might break in the future. Our concern is to upgrade
    the legacy database schema to the point where django is in charge of the migrations.
    """

    if "cc_pref" not in connection.introspection.table_names():
        return None

    with connection.cursor() as cursor:
        cursor.execute("SELECT valstr FROM cc_pref WHERE keystr = 'schema_version'")
        row = cursor.fetchone()
        return row[0] if row else None
```

7. I examined the database I loaded from my airtime server, and lo, there is no such entry:
```
libretime=> select * from cc_pref;
libretime=> SELECT valstr FROM cc_pref WHERE keystr = 'schema_version';
 valstr 
--------
(0 rows)
```

Ergo, the schema proceeds to blow away all of the data from the airtime restore.

So the (lack of) presence of a schema_version (which I believe to be a property of a libretime database, and post-dates the fork from airtime), is not being considered in the case of an airtime database load, in which it would actually be quite normal for a schema version not to exist in the table cc_pref.

If I'm correct, I believe the 0001_initial migration should probably check something else to properly identify an (unmigrated) airtime database load.  

Or I am missing something else entirely.  If so, apologies.

**Comment by HighTechHarmony** [comment]
Reviewing change logs, I discovered that this may be a duplicate of bug #2563.  That appears to have been marked fixed by updated documentation around upgrading from Airtime, but in my case the updated document is the one I am following, and yet the outcome appears to be the same for me.  I never saw a confirmation that this was in fact solved for the OP.  Is it possible that this is still an issue?

For giggles, I modified /opt/libretime/lib/python3.9/site-packages/libretime_api/legacy/migrations/_migrations.py as follows:
```
22c22
<         if row: return row[0]
---
>         return row[0] if row else None
24,32d23
<         # Check to see if this is an airtime 2.5.1 migration which will not return a schema_version
<         # We look for system_version to have a value of 2.5.1
<         with connection.cursor() as cursor:
<             cursor.execute("SELECT valstr FROM cc_pref WHERE keystr = 'system_version'")
<             row = cursor.fetchone()
<             if row and row[0] == '2.5.1':
<                 return '0'  # A low schema version that is not None
< 
<         return None
```

... And then reran the migration.  
It appears to run without deleting the data now, but fails at the point of doing legacy.0006_2_5_5 :
```
root@libretimedeb:~/libretime/api/build/lib/libretime_api/legacy/migrations# sudo -u libretime libretime-api migrate
Operations to perform:
  Apply all migrations: auth, contenttypes, legacy, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying legacy.0001_initial... OK
  Applying legacy.0003_2_5_2... OK
  Applying legacy.0004_2_5_3... OK
  Applying legacy.0005_2_5_4... OK
  Applying legacy.0006_2_5_5...Traceback (most recent call last):
  File "/opt/libretime/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/opt/libretime/lib/python3.9/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicateColumn: column "image_path" of relation "cc_show" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/libretime-api", line 8, in <module>
    sys.exit(main())
  File "/opt/libretime/lib/python3.9/site-packages/libretime_api/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/libretime/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/opt/libretime/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/libretime/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/libretime/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/libretime/lib/python3.9/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/opt/libretime/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/libretime/lib/python3.9/site-packages/libretime_api/legacy/migrations/_migrations.py", line 79, in inner
    cursor.execute(sql)
  File "/opt/libretime/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/libretime/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/libretime/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/libretime/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/libretime/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/opt/libretime/lib/python3.9/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column "image_path" of relation "cc_show" already exists
```

**Comment by HighTechHarmony** [comment]
Curious.  The migration 0006_2_5_5 attempts to add a column 'image_path' to cc_show:
```
UP = """
-- DELETE FROM cc_pref WHERE keystr = 'system_version';
-- INSERT INTO cc_pref (keystr, valstr) VALUES ('system_version', '2.5.5');

ALTER TABLE cc_show ADD COLUMN image_path varchar(255) DEFAULT '';
ALTER TABLE cc_show_instances ADD COLUMN description varchar(255) DEFAULT '';
"""
```

But a look back at migration 003_2_5_2 also appears to reveal a similar action:
```
UP = """
-- Replacing system_version with schema_version
DELETE FROM cc_pref WHERE keystr = 'system_version';
INSERT INTO cc_pref (keystr, valstr) VALUES ('schema_version', '2.5.2');

ALTER TABLE cc_show ADD COLUMN image_path varchar(255) DEFAULT '';
ALTER TABLE cc_show_instances ADD COLUMN description varchar(255) DEFAULT '';
"""
```

Since the migrations are applied incrementally, I can see why this would be failing for someone who is migrating from a version 2_5_2 or earlier.  I wonder if this is a separate bug?

**Comment by HighTechHarmony** [comment]
I fixed this by removing the redundant ADD COLUMNS, and reran the migration.  It got further, but then I continued to find (and fix) other failures in legacy migrations up to, and including 0023_3_0_0_alpha_9_1.  

So all told, I made the following changes to legacy migrations files:
**_migrations.py**
If schema_version is not found, then checks for system_version to have a value of '2.5.1' (in case this is an airtime 2.5.1 migration which will not have any schema_version in cc_pref)


**0006_2_5_5**
Removed a redundant addition of the image_path and description columns to cc_show (done in earlier migration 003_2_5_2)

**0015_2_5_17**
Fixed a syntax error with adding the artwork column to cc_files

**0023_3_0_0_alpha_9_1**
Removed a redundant addition of the artwork column to cc_files (done in earlier migration 0015_2_5_7)

After fixing these issues, I ran
`sudo -u libretime libretime-api migrate`

...and it was able to successfully migrate my Airtime database (without deleting my data!) and ultimately Libretime started up as I hoped.  I logged in using my familiar Airtime auth info, and I was able to see calendar entries and library contents from the old system, etc. Great Success!

Some thoughts:
I don't know how long this has been a problem, but AFAICT, no one could be successfully migrating from Airtime to Libretime while these issues exist.  

I am happy to make a PR.  I don't know if my approach to fixing these legacy migrations will be preferred by the maintainers, but FWIW I have attached my patch, in case someone out there is tearing their hair out (like I was).  I am guessing that in 99% of cases, people will only need this functionality once (to get them crossed over to Libretime).  After you clone the repo (but before installing), copy it in, and "git apply" it.  Example:
`git clone https://github.com/libretime/libretime`
`wget https://github.com/user-attachments/files/18086267/patch.diff.txt`
`cd libretime`
`git apply ../patch.diff.txt`

Verify the patch was applied with:
`git status`

You should see 4 files have been modified.
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/libretime_api/legacy/migrations/0006_2_5_5.py
	modified:   api/libretime_api/legacy/migrations/0015_2_5_17.py
	modified:   api/libretime_api/legacy/migrations/0023_3_0_0_alpha_9_1.py
	modified:   api/libretime_api/legacy/migrations/_migrations.py
```

Then proceed with the normal install.

[patch.diff.txt](https://github.com/user-attachments/files/18086267/patch.diff.txt)
