### ISSUE TITLE
Uploads sometimes failing

### ISSUE THREAD

**Issue by squiggleuk** [LibreTime/libretime#331]
Hi All,

_OS: Ubuntu 16.04 LTS (Libretime installed via git checkout and ./install around a week or so ago)_

I'm seeing problems with uploads failing sometimes... All looks ot be working ok initially, I can see file growing in /tmp/phpXXXXX,  but when the upload gets to 100%, I get a red box in the UI saying "An error occurred while processing your upload. Please try again in a few minutes".

In the airtime_analyzer.log I see:
```
2017-10-10T19:39:24+01:00 ERR (3): radio.station.com [MediaController.php:160 - postAction()] - invalid file uploaded
#0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#5 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#6 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#7 {main}
```
Seems to be files > 200MB affected by this? Is there a max upload size somewhere? All I could find was apache's:
php_value post_max_size 500M

**Comment by squiggleuk** [comment]
What a fool.

```
[root@radio:/srv# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            234M     0  234M   0% /dev
tmpfs            49M  3.2M   46M   7% /run
/dev/xvda1      3.9G  3.5G  206M  95% /
```
