### ISSUE TITLE
DB lock error when doing live stream

### ISSUE THREAD

**Issue by Power2All** [LibreTime/libretime#465]
Whenever I connect with Edcast for example to stream to port 8002, there is a DB error and then a lot of foreach errors, since the DB is locking up and erroring, making the streaming impossible to start.
This happens every time I try to connect with client to 8002 stream port.

```
2018-03-11T19:49:47+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:26 - errorAction()] - Invalid argument supplied for foreach()
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1301): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 1301, Array)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->updateStreamSettingTableAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('updateStreamSet...')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: ErrorException: Invalid argument supplied for foreach() in /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php:1301
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1301): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 1301, Array)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->updateStreamSettingTableAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('updateStreamSet...')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:26 - errorAction()] - Invalid argument supplied for foreach()
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1301): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 1301, Array)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->updateStreamSettingTableAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('updateStreamSet...')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: ErrorException: Invalid argument supplied for foreach() in /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php:1301
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1301): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 1301, Array)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->updateStreamSettingTableAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('updateStreamSet...')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:26 - errorAction()] - Invalid argument supplied for foreach()
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/models/ListenerStat.php(97): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 97, Array)
#1 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1293): Application_Model_ListenerStat::insertDataPoints(NULL)
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->pushStreamStatsAction()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('pushStreamStats...')
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#6 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#7 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#8 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#9 {main}
2018-03-11T19:49:56+00:00 ERR (3): www.aniradio.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: ErrorException: Invalid argument supplied for foreach() in /usr/share/airtime/php/airtime_mvc/application/models/ListenerStat.php:97
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/models/ListenerStat.php(97): exception_error_handler(2, 'Invalid argumen...', '/usr/share/airt...', 97, Array)
#1 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1293): Application_Model_ListenerStat::insertDataPoints(NULL)
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->pushStreamStatsAction()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('pushStreamStats...')
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#6 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#7 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#8 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#9 {main}
```

```
2018-03-11T20:02:04+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2018-03-11T20:02:16+00:00 INFO (6): www.aniradio.org Checking autoplaylist poll
2018-03-11T20:02:28+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2018-03-11T20:02:40+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2018-03-11T20:02:40+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2018-03-11T20:02:52+00:00 INFO (6): www.aniradio.org Checking autoplaylist poll
2018-03-11T20:02:52+00:00 INFO (6): www.aniradio.org Checking to run Auto Playlist
2018-03-11T20:02:52+00:00 WARN (4): www.aniradio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
```

**Comment by Robbt** [comment]
Ok, this is the pertinent code that is failing - I suspect the request isn't getting sent correctly.
    public function updateStreamSettingTableAction() {
        $request = $this->getRequest();
        $data = json_decode($request->getParam("data"), true);
        
        foreach ($data as $k=>$v) {
            Application_Model_StreamSetting::SetListenerStatError($k, $v);
        }
    }

Since I've been able to connect with other clients to port 8002 before this doesn't always fail and it most likely is something specific to your setup. We can't really trouble shoot it without being able to replicate it or getting more information such as what the API request is that is failing. 

I suspect that it is pulling request object from Zend - see this documentation link (https://framework.zend.com/manual/1.12/en/zend.controller.request.html)

If you are still interest in helping us troubleshoot this let me know.
