### ISSUE TITLE
LibreTime media analyzer service no start ?

### ISSUE THREAD

**Issue by premiumbe** [LibreTime/libretime#474]
![media analizer](https://user-images.githubusercontent.com/33802010/37986498-e98ae318-31fb-11e8-94ef-18cd8775de7b.png)
 hello it's normal?

**Comment by Robbt** [comment]
what happens when you try to manually start it by running
sudo -u www-data airtime_analyzer ?

**Comment by premiumbe** [comment]
![airtime](https://user-images.githubusercontent.com/33802010/38041601-78a3750e-32b2-11e8-87cb-8764834203a9.png)

**Comment by premiumbe** [comment]
this is what he tells me when I upload a music ....
![airtime2](https://user-images.githubusercontent.com/33802010/38042009-7b276528-32b3-11e8-932a-bf225fe82faa.png)

**Comment by Robbt** [comment]
It looks like an issue with using the IP as the hostname. For some reason your local computer isn't able to connect to itself check out the host configuation in /etc/airtime/airtime.conf, and make sure it is something you can reach from inside of the computer's terminal. Seems like it could be similar to the issue under #469

**Comment by Cysioland** [comment]
Tried the same on my install, got this:

```
Airtime Analyzer 1.0
Traceback (most recent call last):
  File "/usr/bin/airtime_analyzer", line 4, in <module>
    __import__('pkg_resources').run_script('airtime-analyzer==0.1', 'airtime_analyzer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 73, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 51, in run
    debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/airtime_analyzer.py", line 45, in __init__
    self._msg_listener = MessageListener(rmq_config, cloud_storage_config)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 89, in __init__
    self.connect_to_messaging_server()
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 113, in connect_to_messaging_server
    self._channel.exchange_declare(exchange=EXCHANGE, type=EXCHANGE_TYPE, durable=True)
TypeError: exchange_declare() got an unexpected keyword argument 'type'
```
