### ISSUE TITLE
audio file import fails if metadata or filename contain non-ascii characters

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#528]
this is another major issue for us, as accented vowels are extremely common in spanish. 

errors from airtime_analyzer.log:

filename:
```
2018-10-05 17:09:26,648 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/external-media\/organize\/14 - Una Chilena En Par\u00eds.mp3","storage_backend":"file","import_directory":"\/external-media\/\/imported\/1","original_filename":"14 - Una Chilena En Par\u00eds.mp3","callback_url":"http:\/\/frecuencialibre.mazorca.org\/\/rest\/media\/27","api_key":"6XXO6RG2MUBR038XA3UM","file_prefix":""}' on routing_key ''
2018-10-05 17:09:26,649 [analyzer_pipeline] [ERROR]  'ascii' codec can't encode character u'\xed' in position 48: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 70, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 32, in analyze
    metadata["filesize"] = os.path.getsize(filename)
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 48: ordinal not in range(128)
2018-10-05 17:09:26,650 [message_listener] [ERROR]  Analyzer pipeline exception: 'ascii' codec can't encode character u'\xed' in position 48: ordinal not in range(128)
```

metadata:
```
2018-10-05 16:16:46,957 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/external-media\/organize\/01 - Arauco Tiene Una Pena.mp3","storage_backend":"file","import_directory":"\/external-media\/\/imported\/1","original_filename":"01 - Arauco Tiene Una Pena.mp3","callback_url":"http:\/\/frecuencialibre.mazorca.org\/\/rest\/media\/24","api_key":"6XXO6RG2MUBR038XA3UM","file_prefix":""}' on routing_key ''
2018-10-05 16:16:52,200 [analyzer_pipeline] [ERROR]  'ascii' codec can't encode character u'\xf3' in position 62: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 79, in run_analysis
    metadata = FileMoverAnalyzer.move(audio_file_path, import_directory, original_filename, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/filemover_analyzer.py", line 66, in move
    if os.path.exists(final_file_path):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 62: ordinal not in range(128)
2018-10-05 16:16:52,200 [message_listener] [ERROR]  Analyzer pipeline exception: 'ascii' codec can't encode character u'\xf3' in position 62: ordinal not in range(128)
```

**Comment by frecuencialibre** [comment]
Closing this as it appears to only affect the [docker install](https://github.com/ned-kelly/docker-multicontainer-libretime/issues/8) i was using.
