### ISSUE TITLE
airtime-liquidsoap playout problem: SSL: CERTIFICATE_VERIFY_FAILED / Unable to get Airtime API version number.

### ISSUE THREAD

**Issue by itcrowdsource** [LibreTime/libretime#566]
Currently in the progress of moving to LibreTime. I managed to setup LibreTime successfully. After that I copied over the Airtime database to the LibreTime environment. Imported some MP3 files. All went smooth, until I started applying SSL to the site. After applying the SSL config the playout engine stopped working (the broadcast light isn't lit). I reverted all SSL related changes but now the problem still persists. Even after reinstalling the system over the existing configuration. I suspect there is a problem with handling the certificate which causes the "SSL: CERTIFICATE_VERIFY_FAILED" error. I'm currently using a signed certificate (not a self signed) on the web server itself. Probably this error results in the second error found in the syslog/pypo.log "Unable to get Airtime API version number."

syslog:

```

Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 145, in __call__
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     return opener.open(url, data, timeout)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     response = self._open(req, data)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     '_open', req)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     result = func(*args)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     context=self._context)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]:     raise URLError(err)
Oct 17 13:36:54 libretime airtime-liquidsoap[5209]: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Oct 17 13:36:55 libretime airtime-playout[1327]: 2018-10-17 13:36:55,968 [api_client] [INFO ]  Unable to get Airtime API version number.
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]: traceback: Traceback (most recent call last):
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/generate_liquidsoap_cfg.py", line 48, in run
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     ss = ac.get_stream_setting()
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 470, in get_stream_setting
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     return self.services.get_stream_setting()
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 145, in __call__
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     return opener.open(url, data, timeout)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     response = self._open(req, data)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     '_open', req)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     result = func(*args)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     context=self._context)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]:     raise URLError(err)
Oct 17 13:36:57 libretime airtime-liquidsoap[5209]: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

pypo log:
```
2018-10-17 13:50:17,478 [api_client] [INFO ]  Unable to get Airtime API version number.

2018-10-17 13:50:22,486 [api_client] [INFO ]  Unable to get Airtime API version number.

2018-10-17 13:50:27,496 [api_client] [INFO ]  Unable to get Airtime API version number.

2018-10-17 13:50:32,506 [api_client] [INFO ]  Unable to get Airtime API version number.
```

**Comment by frecuencialibre** [comment]
Welcome to the community!

Is your base_url accessible from the command-line?

```
ssh you@yourserver
ping your_base_url
```

**Comment by itcrowdsource** [comment]
I found the issue. It was an issue with the certificate chain. I recreated the certificate files and the problem was solved;-)
