### ISSUE TITLE
Problem: Podcasts failing to download from libsyn due to SSL error

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#57]
I was trying to download DemocracyNow's podcast and a number of errors cropped up in the log regarding SSL.

From the looks of the log here, there might be something we need to do.

[2017-03-10 15:22:39,352: WARNING/PoolWorker-2] /usr/local/lib/python2.7/dist-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[2017-03-10 15:22:40,042: ERROR/PoolWorker-2] Certificate did not match expected hostname: traffic.libsyn.com. Certificate: {'notAfter': 'Jan 23 21:04:38 2018 GMT', 'subjectAltName': (('DNS', '*.app.libsynpro.com'), ('DNS', 'app.libsynpro.com')), 'subject': ((('organizationalUnitName', u'Domain Control Validated'),), (('commonName', u'*.app.libsynpro.com'),))}
[2017-03-10 15:22:40,045: INFO/PoolWorker-2] podcast-download[php_58c30b0e82b7c9.35832819]: Error during file download: hostname 'traffic.libsyn.com' doesn't match either of '*.app.libsynpro.com', 'app.libsynpro.com'
[2017-03-10 15:22:40,052: ERROR/PoolWorker-2] Task podcast-download[php_58c30b0e82b7c9.35832819] raised unexpected: TypeError('SSLError(CertificateError("hostname \'traffic.libsyn.com\' doesn\'t match either of \'*.app.libsynpro.com\', \'app.libsynpro.com\'",),) is not JSON serializable',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.2-py2.7.egg/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.2-py2.7.egg/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airtime_celery-0.1-py2.7.egg/airtime-celery/tasks.py", line 173, in podcast_download
    return json.dumps(obj)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: SSLError(CertificateError("hostname 'traffic.libsyn.com' doesn't match either of '*.app.libsynpro.com', 'app.libsynpro.com'",),) is not JSON serializable

**Comment by Robbt** [comment]
This looks like it might be a fix - http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

**Comment by Robbt** [comment]
Ok, so this is a problem with the version of Python in Ubuntu 14.04.
The solution is to install pyOpenSSL, cryptography, idna, and certifi via pip install.
In order to install cryptography you need to install the headers as per https://cryptography.io/en/latest/installation/#building-cryptography-on-linux

I figure the solution for the install script is to add these packages via apt-get 
sudo apt-get install build-essential libssl-dev libffi-dev python-dev

and then add the various pip packages.

**Comment by hairmare** [comment]
*meh* 😒 Should we try running it under python3 maybe? SSL and py2 is a pain.

**Comment by Robbt** [comment]
Yeah this is specific to Ubuntu 14.04, Debian Jessie should has the minimum level of Python 2.7.9 which includes the SNI support. I'm not even sure where the specification of which pip packages to install  are installed. But it may make sense to check if they are running Ubuntu 14.04 and do an optional command line pip install of the required packages ?
