### ISSUE TITLE
rabbitmq-server not running anymore

### ISSUE THREAD

**Issue by sander816** [LibreTime/libretime#593]
without changes my rabbitmq-server is not running anymore:
Uploading files also stops with  An error occurred while processing your upload. Please try again in a few minutes.
Install has been running fine for a month or so.

vps3.xx.com stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)

```
root@customer:/srv/airtime/stor/organize# service rabbitmq-server status
â rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-11-11 16:42:13 CET; 7min ago
  Process: 5111 ExecStop=/usr/sbin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 4722 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=exited, status=0/SUCCESS)
  Process: 4721 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 4721 (code=exited, status=1/FAILURE)

Nov 11 16:42:13 customer rabbitmq[5111]:   * connected to epmd (port 4369) on customer
Nov 11 16:42:13 customer rabbitmq[5111]:   * epmd reports: node 'rabbit' not running at all
Nov 11 16:42:13 customer rabbitmq[5111]:                   no other nodes on customer
Nov 11 16:42:13 customer rabbitmq[5111]:   * suggestion: start the node
Nov 11 16:42:13 customer rabbitmq[5111]: current node details:
Nov 11 16:42:13 customer rabbitmq[5111]: - node name: 'rabbitmq-cli-14@customer'
Nov 11 16:42:13 customer rabbitmq[5111]: - home dir: .
Nov 11 16:42:13 customer rabbitmq[5111]: - cookie hash: yFF8QvqcKHJyInzoS6gImg==
Nov 11 16:42:13 customer systemd[1]: rabbitmq-server.service: Unit entered failed state.
Nov 11 16:42:13 customer systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.
root@customer:/srv/airtime/stor/organize# service rabbitmq-server start
root@customer:/srv/airtime/stor/organize# service rabbitmq-server status
â rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: deactivating (stop) (Result: exit-code) since Sun 2018-11-11 16:49:55 CET; 322ms ago
  Process: 5522 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=exited, status=0/SUCCESS)
  Process: 5521 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 5521 (code=exited, status=1/FAILURE); Control PID: 5908 (rabbitmqctl)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/rabbitmq-server.service
           ââ5707 /usr/lib/erlang/erts-8.2.1/bin/epmd -daemon
           ââcontrol
             ââ5908 /bin/sh /usr/sbin/rabbitmqctl stop
             ââ5915 /usr/lib/erlang/erts-8.2.1/bin/beam -B -- -root /usr/lib/erlang -progname erl -- -home . -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-0.0.0/ebin -noshell -noinput -
             ââ6000 erl_child_setup 65536

Nov 11 16:49:49 customer systemd[1]: Starting RabbitMQ Messaging Server...
Nov 11 16:49:51 customer rabbitmq[5522]: Waiting for rabbit@customer ...
Nov 11 16:49:51 customer rabbitmq[5522]: pid is 5539 ...
Nov 11 16:49:53 customer systemd[1]: Started RabbitMQ Messaging Server.
Nov 11 16:49:55 customer systemd[1]: rabbitmq-server.service: Main process exited, code=exited, status=1/FAILURE
```

uploading an mp3:
```
2018-11-11T16:53:57+01:00 INFO (6): vps3.xx.com Moving file /tmp/phpfvbVeS to /srv/airtime/stor/organize/DanceFm Dance Xtacy Week37-2017.mp3
2018-11-11T16:53:57+01:00 ERR (3): vps3.xx.com [MediaController.php:160 - postAction()] - stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(2, 'stream_socket_c...', '/usr/share/airt...', 134, Array)
#1 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(134): stream_socket_client('tcp://127.0.0.1...', 111, 'Connection refu...', 3, 4, Resource id #12)
#2 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(196): PhpAmqpLib\Wire\IO\StreamIO->connect()
#3 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(180): PhpAmqpLib\Connection\AbstractConnection->connect()
#4 /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(59): PhpAmqpLib\Connection\AbstractConnection->__construct('airtime', 'airtime', '/airtime', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#5 /usr/share/airtime/php/airtime_mvc/application/models/RabbitMq.php(90): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('127.0.0.1', '5672', 'airtime', 'airtime', '/airtime')
#6 /usr/share/airtime/php/airtime_mvc/application/services/MediaService.php(46): Application_Model_RabbitMq::SendMessageToAnalyzer('/srv/airtime/st...', '/srv/airtime/st...', 'DanceFm Dance X...', 'http://vps3.san...', 'CHJTHDTPRXCOZLV...', 'file', '')
#7 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(160): Application_Service_MediaService::importFileToLibrary('http://vps3.san...', '/tmp/phpfvbVeS', 'DanceFm Dance X...', 1, false)
#8 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(99): CcFiles::createAndImport(Array, '/tmp/phpfvbVeS', 'DanceFm Dance X...')
#9 /usr/share/airtime/php/airtime_mvc/application/modules/rest/controllers/MediaController.php(144): CcFiles::createFromUpload(Array)
#10 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#11 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#12 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#16 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#17 {main}


```

**Comment by Robbt** [comment]
So this probably isn't an issue with LibreTime (since you didn't update anything). 
But an issue with rabbitmq that needs to be resolved. In order to do that you will need to share your 
distro and the amount of resources your system has (for instance rabbitmq might be being killed if you don't have enough RAM).

**Comment by Robbt** [comment]
I suspect it might have something to do with your hostname being customer - but maybe you replaced that - see https://stackoverflow.com/questions/45328072/rabbitmq-failed-install-start-on-debian-stretch

**Comment by sander816** [comment]
no did not chnage hostname, already found that

```
[    0.000000] Linux version 4.9.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13)

root@customer:/home/customer# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@customer:/home/customer#


root@customer:/home/customer# free -m
              total        used        free      shared  buff/cache   available
Mem:            996         243         255          41         497         574
Swap:             0           0           0
root@customer:/home/customer#
```

**Comment by sander816** [comment]
i reinstalled a month ago, because i messed some things up, that i could not resolve. 
Before that it has been running for 6 months or so, without problems.

**Comment by sander816** [comment]
changed the hostname, now i get this:
`2018-11-11T18:48:13+01:00 INFO (6): vps3.xx.com ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.`

rabbitmq is running though:
```
â rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-11-11 18:26:39 CET; 43min ago
 
```

**Comment by sander816** [comment]
when i change the hostname back to what it was, i get the error again in my 1st post

**Comment by xabispacebiker** [comment]
It seems rabbitmq-server service is not correctly installed.  As this is not a Libretime bug I would recommend you to reinstall it again:
1- Backup your data (files and postgres database)
2- Uninstall by using the ./uninstall command provided in the source code. (Make sure that all services have been properly removed, taking special attention on the rabbitmq-server service)
3- Reinstall
4- Restore your data (if needed)

**Comment by hairmare** [comment]
Given that you are on stretch you should have a systemd based install. Could you post the output  of the following commands? Maybe they'll help narrow down what is wrong with your rabbitmq server.

```bash
systemctl status rabbitmq-server.service
journalctl -u rabbitmq-server.service
```

These usually dump some more info than `service rabbitmq-server status` does. If the output is to long you may want to upload it to a service like pastebin.com or similar.

**Comment by sander816** [comment]
```
root@customer:/home/sander# journalctl -u rabbitmq-server.service
-- No entries --
root@customer:/home/sander#



``````
root@customer:/home/sander# systemctl status rabbitmq-server.service
● rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-11-11 19:36:08 CET; 14h ago
  Process: 888 ExecStop=/usr/sbin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 278 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=exited, status=0/SUCCESS)
  Process: 277 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 277 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
root@customer:/home/sander#

```

**Comment by xabispacebiker** [comment]
nice catch! we can close the issue, right?

**Comment by hairmare** [comment]
Looks like the server didn't shutdown cleanly during a reboot. I'm closing this since it's clearly a RabbitMQ Ops issue.
