### ISSUE TITLE
Crash on import of certain mp3 files

### ISSUE THREAD

**Issue by nikmartin** [LibreTime/libretime#610]
Preface: I'm a DJ and have an extensive audio library that is pretty well curated. Certain tracks crash airtime_analyzer when importing, with this error:

```
2018-11-26 14:26:19,798 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/srv\/airtime\/stor\/organize\/TLC - Creep (BPM Supreme ReDrum) (Clean Short Edit).mp3","storage_backend":"file","import_directory":"\/srv\/airtime\/stor\/\/imported\/1","original_filename":"TLC - Creep (BPM Supreme ReDrum) (Clean Short Edit).mp3","callback_url":"http:\/\/35.192.238.53\/\/rest\/media\/25","api_key":"2PA4WDCTHECXHQR1FSML","file_prefix":""}' on routing_key ''
2018-11-26 14:26:19,814 [analyzer_pipeline] [ERROR]  u'replaygain_seratogain_gain'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 66, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 57, in analyze
    if audio_file == None:  # Don't use "if not" here. It is wrong due to mutagen's design.
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 192, in __eq__
    return dict(self.items()) == other
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 134, in items
    return list(izip(self.keys(), self.values()))
  File "/usr/lib/python2.7/dist-packages/mutagen/_util.py", line 128, in values
    return [self[k] for k in self.keys()]
  File "/usr/lib/python2.7/dist-packages/mutagen/_file.py", line 56, in __getitem__
    return self.tags[key]
  File "/usr/lib/python2.7/dist-packages/mutagen/easyid3.py", line 196, in __getitem__
    return func(self.__id3, key)
  File "/usr/lib/python2.7/dist-packages/mutagen/easyid3.py", line 385, in gain_get
    raise EasyID3KeyError(key)
EasyID3KeyError: u'replaygain_seratogain_gain'
2018-11-26 14:26:19,817 [message_listener] [ERROR]  Analyzer pipeline exception: u'replaygain_seratogain_gain'
2018-11-26 14:26:19,857 [connectionpool] [INFO ]  Starting new HTTP connection (1): 35.192.238.53
2018-11-26 14:26:20,004 [status_reporter] [INFO ]  HTTP request sent successfully.
```

The error seems to point to mutagen, but running:
```
mutagen-inspect /srv/airtime/stor/organize/TLC\ -\ Creep\ \(BPM\ Supreme\ ReDrum\)\ \(Clean\ Short\ Edit\).mp3 
-- /srv/airtime/stor/organize/TLC - Creep (BPM Supreme ReDrum) (Clean Short Edit).mp3 
- MPEG 1 layer 3, 320000 bps (CBR?), 44100 Hz, 2 chn, 123.90 seconds (audio/mp3)
APIC= (image/jpeg, 6834 bytes)
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
GEOB=[unrepresentable data]
RVA2=[unrepresentable data]
TBPM=93
TCON=Hip Hop
TDRC=2018
TIT2=Creep (BPM Supreme ReDrum) (Clean Short Edit)
TKEY=Fm
TPE1=TLC 
```
Yields good results and no crash.

**Comment by Robbt** [comment]
Looks like the issue is related to reading specifically the replay gain tag.

**Comment by nikmartin** [comment]
Yeah, I googled the stack trace and found a [few Mutagen bugs](https://github.com/quodlibet/mutagen/issues/215) related to tags being lower vs uppercase. This is probably upstream, but I filed it because it may be fixed in a more recent version.

**Comment by hairmare** [comment]
I remember seeing this

https://github.com/LibreTime/libretime/blob/87ac92102b879d4dafa5aa2c2139c3ea47866dc8/python_apps/airtime_analyzer/setup.py#L31

We should get rid of that and replace it with something that makes sense. The version we code against should probably also be influenced by what's available on the distros we want to support.

You stack trace looks like it's tripping in the following context:

https://github.com/LibreTime/libretime/blob/87ac92102b879d4dafa5aa2c2139c3ea47866dc8/python_apps/airtime_analyzer/airtime_analyzer/metadata_analyzer.py#L52-L60

I added mutagen to the [Distro Package](https://github.com/LibreTime/libretime/wiki/Distro-Packages#mutagen) wiki page to make it easier to get an overview of what's available. It looks like we currently have everything ranging from 1.20 (CentOS) to 1.38 (Ubuntu Bionic) to currently consider if we want to use distro packages.

Did you figure out when upstream fixed it to help us narrow down what distros this affects?

**Comment by Robbt** [comment]
I think that it currently installs via pip, so it should be easy enough for you to test it @nikmartin by removing the mutagen==1.31 restriction and just require mutagen and then running ```sudo python setup.py install``` inside of the airtime_analyzer directory and then try importing the file again. Evidently there were issues before with various mutagen versions but if there are bug fixes we want to incorporate we should try and upgrade to a later version and see if it breaks the code.

**Comment by nikmartin** [comment]
I'll test in a bit and reply with the results

**Comment by nikmartin** [comment]
updating to the package manager's version of mutagen (Ubunto 16.04.5) seems to have resolved the issue, and several MP3s I'v tested imported fine

**Comment by hairmare** [comment]
It looks like Ubuntu 16.04.5 has 1.31 like we were pinned to but with some patches.
