### ISSUE TITLE
Problem: playlist shuffle function broken

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#646]
as @Robbt observed, hitting the shuffle button on a playlist has broken.

```
2018-12-17T18:33:54+00:00 ERR (3): fl.local [Logging.php:166 - loggingShutdownCallback()] - Uncaught Error: Call to undefined method Application_Model_Playlist::getListofFilesMeetCriteria() in /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php:68
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php(656): PlaylistController->createUpdateResponse(Object(Application_Model_Playlist), true)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): PlaylistController->shuffleAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('shuffleAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend at /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php:68
array (
  'type' => 1,
  'message' => 'Uncaught Error: Call to undefined method Application_Model_Playlist::getListofFilesMeetCriteria() in /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php:68
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php(656): PlaylistController->createUpdateResponse(Object(Application_Model_Playlist), true)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): PlaylistController->shuffleAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch(\'shuffleAction\')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend',
  'file' => '/usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php',
  'line' => 68,
)
```

**Comment by hairmare** [comment]
Do we need to consider this a blocker for 3.0.0-alpha.6?

**Comment by Robbt** [comment]
I wouldn't consider it a blocker because it is more of a nuisance than anything else, it currently doesn't break the site but does require a refresh and the functionality or shuffling a playlist containing smartblock is probably not a critical or very common workflow for people. It might have been broken for a while without us realizing it or it could have been caused by recent changes related to implementing the "counter of files that match".

**Comment by hairmare** [comment]
It looks like `Application_Model_Playlist::getListofFilesMeetCriteria()` never existed... All I can find is `Application_Model_Block::getListofFilesMeetCriteria()`. Maybe fixing this is a case of making it call the block model instead of the playlist model.

**Comment by Robbt** [comment]
Ok, this is related to how smartblocks are also considered a type of playlists and designed to prevent it from showing the number of missing items for playlists etc. I'm going to try a quick check to see if I can determine if the object is a block and otherwise not run this.
