### ISSUE TITLE
ZF1s does not support PHP 7.3 (Debian Buster)

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#709]
**Describe the bug**
PHP 7.3 is not supported by ZF1s. 

**To Reproduce**
1. `vagrant up debian-buster`
2. Step through setup
3. Open login form

Running this on Buster using PHP 7.3, I get the following error:

```
compact(): Undefined variable: extras#0 [internal function]: exception_error_handler(8, 'compact(): Unde...', '/vagrant/vendor...', 404, Array) #1 /vagrant/vendor/zf1s/zend-view/library/Zend/View/Helper/HeadLink.php(404): compact('rel', 'type', 'href', 'media', 'conditionalStyl...', 'extras') #2 /vagrant/vendor/zf1s/zend-view/library/Zend/View/Helper/HeadLink.php(172): Zend_View_Helper_HeadLink->createDataStylesheet(Array) #3 /vagrant/airtime_mvc/application/controllers/ErrorController.php(68): Zend_View_Helper_HeadLink->__call('appendStyleshee...', Array) #4 /vagrant/airtime_mvc/application/controllers/ErrorController.php(9): ErrorController->setupCSS() #5 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(133): ErrorController->init() #6 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http), Array) #7 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #8 /vagrant/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch() #9 /vagrant/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run() #10 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run() #11 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...') #12 {main}

#0 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Object(Zend_Controller_Request_Http))
#1 /vagrant/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /vagrant/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#3 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#4 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#5 {main}
```

**Expected behavior**
Login form shows

**LibreTime version:**
17e69cf

**Installation method:**
 - OS: Debian
 - OS Version: Buser
 - Method: `./install`
 - Details: vagrant

**Additional context**
Explanation here: https://github.com/LibreTime/libretime/pull/670#issuecomment-453989369

PR against ZF1s: https://github.com/zf1s/zend-view/pull/1

**Comment by frecuencialibre** [comment]
so this is currently waiting on https://github.com/zf1s/zend-view/pull/1 ? anything else?

**Comment by paddatrapper** [comment]
More testing to find any other errors

**Comment by Robbt** [comment]
So https://github.com/zf1s/zend-view/pull/1 was closed because a fix was implemented a couple of days after @hairmare submitted the PR independent of said PR and so someone should test this with the master-dev branch of zf1s/zend-view and confirm that this now works because we should be able to close this issue.
