### ISSUE TITLE
Failed to import database from Airtime 2.5.1 to Libretime 3.0.0-alpha.6

### ISSUE THREAD

**Issue by b01xy** [LibreTime/libretime#771]
**Describe the bug**
On a fresh install of libretime from git on a unbuntu 18.04 which works, the database import from an airtime 2.5.3 instance (following http://libretime.org/manual/backing-up-the-server/) brings errors and gives "Oops!
something went wrong!" : 

```
sudo tail -f /var/log/postgresql/postgresql-10-main.log
2019-03-10 16:36:54.323 CET [23737] airtime@airtime ERROR:  relation "celery_tasks" does not exist at character 378
2019-03-10 16:36:54.323 CET [23737] airtime@airtime STATEMENT:  SELECT celery_tasks.id, celery_tasks.task_id, celery_tasks.track_reference, celery_tasks.name, celery_tasks.dispatch_time, celery_tasks.status, third_party_track_references.id, third_party_track_references.service, third_party_track_references.foreign_id, third_party_track_references.file_id, third_party_track_references.upload_time, third_party_track_references.status FROM celery_tasks INNER JOIN third_party_track_references ON (celery_tasks.track_reference=third_party_track_references.id) WHERE celery_tasks.status=$1 AND celery_tasks.task_id<>$2
2019-03-10 16:36:58.029 CET [23754] airtime@airtime ERROR:  column "import_status" does not exist at character 64
2019-03-10 16:36:58.029 CET [23754] airtime@airtime STATEMENT:  SELECT "id", "name", "mime", "ftype", "directory", "filepath", "import_status", "currentlyaccessing", "editedby", "mtime", "utime", "lptime", "md5", "track_title", "artist_name", "bit_rate", "sample_rate", "format", "length", "album_title", "genre", "comments", "year", "track_number", "channels", "url", "bpm", "rating", "encoded_by", "disc_number", "mood", "label", "composer", "encoder", "checksum", "lyrics", "orchestra", "conductor", "lyricist", "original_lyricist", "radio_station_name", "info_url", "artist_url", "audio_source_url", "radio_station_url", "buy_this_url", "isrc_number", "catalog_number", "original_artist", "copyright", "report_datetime", "report_location", "report_organization", "subject", "contributor", "language", "file_exists", "soundcloud_id", "soundcloud_error_code", "soundcloud_error_msg", "soundcloud_link_to_file", "soundcloud_upload_time", "replay_gain", "owner_id", "cuein", "cueout", "silan_check", "hidden", "is_scheduled", "is_playlist", "filesize", "description" FROM "cc_files" WHERE "id" = $1
```
Is it possible to migrate the database from Airtime 2.5 to Libretime 3 ? Import only the datas as the schema.xml seems to have changed ?

thks

**Comment by Robbt** [comment]
If you look at the zend-php.log you should see a specific error that can hint at where the database is failing. The controller should automatically upgrade the database.

**Comment by Robbt** [comment]
It looks like the various Airtime 2.5 updates aren't being applied via applications/controllers/upgrade_sql

**Comment by Robbt** [comment]
You could manually apply the changes or we could try to figure out why it isn't automatically applying them in your instance.

**Comment by b01xy** [comment]
I had some php function disabled, so I retried with all the php function enabled

If I drop the database and remove airtime.conf and finish the install, there are many errors while importing the old database : 
```
psql:airtimeserver4-backup:8579906: invalid command \.
psql:airtimeserver4-backup:8579913: ERROR:  syntax error at or near "stream"
LINE 1: stream.mp3 01:00:00 5 2016-02-11 09:29:11 2016-02-11 09:29:1...
        ^
psql:airtimeserver4-backup:8692292: ERROR:  insert or update on table "cc_webstream_metadata" violates foreign key constraint "cc_schedule_inst_fkey"
DETAIL:  Key (instance_id)=(2) is not present in table "cc_schedule".
 112384

      1

      1

psql:airtimeserver4-backup:8692321: ERROR:  multiple primary keys for table "cc_block" are not allowed
psql:airtimeserver4-backup:8692329: ERROR:  multiple primary keys for table "cc_blockcontents" are not allowed
psql:airtimeserver4-backup:8692337: ERROR:  multiple primary keys for table "cc_blockcriteria" are not allowed
psql:airtimeserver4-backup:8692345: ERROR:  multiple primary keys for table "cc_country" are not allowed
psql:airtimeserver4-backup:8692353: ERROR:  multiple primary keys for table "cc_files" are not allowed
psql:airtimeserver4-backup:8692361: ERROR:  multiple primary keys for table "cc_listener_count" are not allowed
psql:airtimeserver4-backup:8692369: ERROR:  multiple primary keys for table "cc_live_log" are not allowed
ALTER TABLE
```
If I remove airtime.conf, import first the old database and finish the installation : 

```
sudo tail -f /var/log/airtime/zendphp.log
Next PropelException: Unable to execute SELECT statement [SELECT podcast_episodes.id, podcast_episodes.file_id, podcast_episodes.podcast_id, podcast_episodes.publication_date, podcast_episodes.download_url, podcast_episodes.episode_guid, podcast_episodes.episode_title, podcast_episodes.episode_description, cc_files.id, cc_files.name, cc_files.mime, cc_files.ftype, cc_files.directory, cc_files.filepath, cc_files.import_status, cc_files.currentlyaccessing, cc_files.editedby, cc_files.mtime, cc_files.utime, cc_files.lptime, cc_files.md5, cc_files.track_title, cc_files.artist_name, cc_files.bit_rate, cc_files.sample_rate, cc_files.format, cc_files.length, cc_files.album_title, cc_files.genre, cc_files.comments, cc_files.year, cc_files.track_number, cc_files.channels, cc_files.url, cc_files.bpm, cc_files.rating, cc_files.encoded_by, cc_files.disc_number, cc_files.mood, cc_files.label, cc_files.composer, cc_files.encoder, cc_files.checksum, cc_files.lyrics, cc_files.orchestra, cc_files.conductor, cc_files.lyricist, cc_files.original_lyricist, cc_files.radio_station_name, cc_files.info_url, cc_files.artist_url, cc_files.audio_source_url, cc_files.radio_station_url, cc_files.buy_this_url, cc_files.isrc_number, cc_files.catalog_number, cc_files.original_artist, cc_files.copyright, cc_files.report_datetime, cc_files.report_location, cc_files.report_organization, cc_files.subject, cc_files.contributor, cc_files.language, cc_files.file_exists, cc_files.soundcloud_id, cc_files.soundcloud_error_code, cc_files.soundcloud_error_msg, cc_files.soundcloud_link_to_file, cc_files.soundcloud_upload_time, cc_files.replay_gain, cc_files.owner_id, cc_files.cuein, cc_files.cueout, cc_files.silan_check, cc_files.hidden, cc_files.is_scheduled, cc_files.is_playlist, cc_files.filesize, cc_files.description FROM podcast_episodes LEFT JOIN cc_files ON (podcast_episodes.file_id=cc_files.id) WHERE podcast_episodes.podcast_id=:p1 ORDER BY podcast_episodes.publication_date DESC] [wrapped: SQLSTATE[42703]: Undefined column: 7 ERROR:  column podcast_episodes.episode_title does not exist
LINE 1: ...odes.download_url, podcast_episodes.episode_guid, podcast_ep...
                                                             ^] in /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php:1389
Stack trace:
#0 /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php(1227): ModelCriteria->doSelect(Object(PropelPDO))
#1 /usr/share/airtime/php/airtime_mvc/application/services/PodcastEpisodeService.php(349): ModelCriteria->find()
#2 /usr/share/airtime/php/airtime_mvc/application/controllers/IndexController.php(62): Application_Service_PodcastEpisodeService->getPodcastEpisodes(1, 0, 0, 'podcast_episode...', 'DESC')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): IndexController->indexAction()
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#10 {main}
2019-03-10T17:16:18+01:00 INFO (6): air.p-node.org Notifying RabbitMQ to send message to pypo
```

thks for your help

**Comment by b01xy** [comment]
I rechecked, the airtime version is Airtime 2.5.1

**Comment by Robbt** [comment]
Looks like in the second case where you import and then install you just aren't getting the latest database fixes. Maybe try manually applying them and see if you have better luck. I might have messed up when I pushed the database upgrade version past what we have released. I need to test it and see.

**Comment by b01xy** [comment]
Manual upgrade : 

```
sudo -u postgres dropdb airtime
sudo -u postgres psql -f /home/pnode/airtimeserver4-backup
sudo -u postgres psql -f airtime_2.5.2/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.3/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.5/upgrade.sql airtime
 DELETE 1
 INSERT 0 1
 psql:airtime_2.5.5/upgrade.sql:4: ERROR:  column "image_path" of relation "cc_show" already exists
 psql:airtime_2.5.5/upgrade.sql:5: ERROR:  column "description" of relation "cc_show_instances" already exists
sudo -u postgres psql -f airtime_2.5.9/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.10/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.12/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.13/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.14/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.15/upgrade.sql airtime
sudo -u postgres psql -f airtime_2.5.16/upgrade.sql airtime
sudo -u postgres psql -f airtime_3.0.0-alpha/upgrade.sql airtime
sudo -u postgres psql -f airtime_3.0.0-alpha.1/upgrade.sql airtime
sudo -u postgres psql -f airtime_3.0.0-alpha.6/upgrade.sql airtime
sudo -u postgres psql -c "SELECT * FROM cc_music_dirs;" airtime
```
which worked, a few problems of permission 
` airtime@airtime ERROR:  permission denied for relation celery_tasks`
so hardcore way ...
```
 sudo -u postgres psql airtime
 airtime=# GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO airtime;
 airtime=# GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to airtime;
 airtime=# GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to airtime;
then postgresql log seems ok but libretime is not accessible : Oops! Something went wrong!
```

in  
```
service airtime-liquidsoap status
● airtime-liquidsoap.service - Airtime Liquidsoap Service
   Loaded: loaded (/etc/systemd/system/airtime-liquidsoap.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-03-11 00:21:50 UTC; 1s ago
...
Mar 11 00:21:51 libretime airtime-liquidsoap[25399]:   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
Mar 11 00:21:51 libretime airtime-liquidsoap[25399]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Mar 11 00:21:51 libretime airtime-liquidsoap[25399]: HTTPError: HTTP Error 500: Internal Server Error

```

In /var/log/airtime/pypo-liquidsoap/ls_script.log
```
2019/03/11 01:14:57 [clock.wallclock_main:2] Error when starting dummy: Address already in use in bind()!
2019/03/11 01:14:57 [clock.wallclock_main:3] Raised by primitive operation at file "tools/harbor.ml", line 696, characters 14-30
2019/03/11 01:14:57 [clock.wallclock_main:3] Called from file "tools/harbor.ml", line 723, characters 20-46
2019/03/11 01:14:57 [clock.wallclock_main:3] Called from file "tools/harbor.ml", line 733, characters 18-39
2019/03/11 01:14:57 [clock.wallclock_main:3] Called from file "sources/harbor_input.ml", line 173, characters 8-72
2019/03/11 01:14:57 [dummy:1] Got ill-balanced activations (from dummy)!
2019/03/11 01:14:57 [clock:2] Error when leaving output dummy: File "source.ml", line 403, characters 10-16: Assertion failed!
```
as we are migrating from a server to anaother, the imported setttings in libretime may involve conflicts (mountpoint on an already occupied icecast), so maybe the import of the db succeeded and now something else is happening ?

**Comment by Robbt** [comment]
So is the server accessible now ? I believe the bind error has to do with something already being open on the port. It maybe the stream setting ports. If you can access the website then the database is probably OK and this is another problem.

**Comment by b01xy** [comment]
After a few more tests, I could import the manually updated database (dump from airtime 2.5.1) into libretime db

- if I don't drop the freshly installed libretime db before importing, it works (calendar, webstreams) but libretime doesn't see the tracks wich are at the same place /srv/airtime/stor/
- if I drop the freshly installed libretime db before importing, the server doesn't work with again this kind of error 
`Error when starting dab(dot)mp3: Address already in use in bind()!`

I tried to redirect streams which could conflict to the icecast server of the container, without success till now

at the end i'll be good to document the process :)

**Comment by Robbt** [comment]
Yeah, the tracks themselves need to be imported into the database. I'm not sure what is going on with the bind()

**Comment by b01xy** [comment]
Ok, I now manage to access to Libretime after a fresh new install and an import of the old manually updated database in the new schema of libretime.
After this import, I see that there is nothing in cc_files table, I'll try to export data only from this table in the old db and re-import it in libretime db. As I'm not very familiar with postgresql I need to check the commands.

thks
b

**Comment by Robbt** [comment]
Ok, I'm going to try installing a sample Airtime install via deb file and then see if I can replicate the issue, if I can then it should be easy enough to fix.

**Comment by Robbt** [comment]
Ok I have confirmed that this indeed it is impossible to upgrade directly from airtime 2.5.1 to LibreTime because of an error with the upgrades.

Here is the exact log that occurs. It looks like it is trying to apply a 2.5.4 upgrade script which doesn't exist.

```
2019-03-27T07:59:28-04:00 INFO (6): localhost localhost:8080: 2.5.4 Upgrade: Promoted user admin to be a Super Admin.
2019-03-27T07:59:30-04:00 INFO (6): localhost You must explicitly start the session with Zend_Session::start() when session options are set to strict.
2019-03-27T07:59:30-04:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - Unable to execute SELECT statement [SELECT podcast_episodes.id, podcast_episodes.file_id, podcast_episodes.podcast_id, podcast_episodes.publication_date, podcast_episodes.download_url, podcast_episodes.episode_guid, podcast_episodes.episode_title, podcast_episodes.episode_description, cc_files.id, cc_files.name, cc_files.mime, cc_files.ftype, cc_files.directory, cc_files.filepath, cc_files.import_status, cc_files.currentlyaccessing, cc_files.editedby, cc_files.mtime, cc_files.utime, cc_files.lptime, cc_files.md5, cc_files.track_title, cc_files.artist_name, cc_files.bit_rate, cc_files.sample_rate, cc_files.format, cc_files.length, cc_files.album_title, cc_files.genre, cc_files.comments, cc_files.year, cc_files.track_number, cc_files.channels, cc_files.url, cc_files.bpm, cc_files.rating, cc_files.encoded_by, cc_files.disc_number, cc_files.mood, cc_files.label, cc_files.composer, cc_files.encoder, cc_files.checksum, cc_files.lyrics, cc_files.orchestra, cc_files.conductor, cc_files.lyricist, cc_files.original_lyricist, cc_files.radio_station_name, cc_files.info_url, cc_files.artist_url, cc_files.audio_source_url, cc_files.radio_station_url, cc_files.buy_this_url, cc_files.isrc_number, cc_files.catalog_number, cc_files.original_artist, cc_files.copyright, cc_files.report_datetime, cc_files.report_location, cc_files.report_organization, cc_files.subject, cc_files.contributor, cc_files.language, cc_files.file_exists, cc_files.soundcloud_id, cc_files.soundcloud_error_code, cc_files.soundcloud_error_msg, cc_files.soundcloud_link_to_file, cc_files.soundcloud_upload_time, cc_files.replay_gain, cc_files.owner_id, cc_files.cuein, cc_files.cueout, cc_files.silan_check, cc_files.hidden, cc_files.is_scheduled, cc_files.is_playlist, cc_files.filesize, cc_files.description FROM podcast_episodes LEFT JOIN cc_files ON (podcast_episodes.file_id=cc_files.id) WHERE podcast_episodes.podcast_id=:p1 ORDER BY podcast_episodes.publication_date DESC] [wrapped: SQLSTATE[42703]: Undefined column: 7 ERROR:  column podcast_episodes.episode_title does not exist
LINE 1: ...odes.download_url, podcast_episodes.episode_guid, podcast_ep...
                                                             ^]
2019-03-27T07:59:30-04:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php(1227): ModelCriteria->doSelect(Object(PropelPDO))
#1 /usr/share/airtime/php/airtime_mvc/application/services/PodcastEpisodeService.php(349): ModelCriteria->find()
#2 /usr/share/airtime/php/airtime_mvc/application/controllers/IndexController.php(62): Application_Service_PodcastEpisodeService->getPodcastEpisodes(1, 0, 0, 'podcast_episode...', 'DESC')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): IndexController->indexAction()
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#10 {main}
2019-03-27T07:59:30-04:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column podcast_episodes.episode_title does not exist
LINE 1: ...odes.download_url, podcast_episodes.episode_guid, podcast_ep...
                                                             ^' in /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php:1386
Stack trace:
#0 /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php(1386): PDOStatement->execute()
#1 /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php(1227): ModelCriteria->doSelect(Object(PropelPDO))
#2 /usr/share/airtime/php/airtime_mvc/application/services/PodcastEpisodeService.php(349): ModelCriteria->find()
#3 /usr/share/airtime/php/airtime_mvc/application/controllers/IndexController.php(62): Application_Service_PodcastEpisodeService->getPodcastEpisodes(1, 0, 0, 'podcast_episode...', 'DESC')
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): IndexController->indexAction()
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#6 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#8 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#9 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#10 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#11 {main}

Next exception 'PropelException' with message 'Unable to execute SELECT statement [SELECT podcast_episodes.id, podcast_episodes.file_id, podcast_episodes.podcast_id, podcast_episodes.publication_date, podcast_episodes.download_url, podcast_episodes.episode_guid, podcast_episodes.episode_title, podcast_episodes.episode_description, cc_files.id, cc_files.name, cc_files.mime, cc_files.ftype, cc_files.directory, cc_files.filepath, cc_files.import_status, cc_files.currentlyaccessing, cc_files.editedby, cc_files.mtime, cc_files.utime, cc_files.lptime, cc_files.md5, cc_files.track_title, cc_files.artist_name, cc_files.bit_rate, cc_files.sample_rate, cc_files.format, cc_files.length, cc_files.album_title, cc_files.genre, cc_files.comments, cc_files.year, cc_files.track_number, cc_files.channels, cc_files.url, cc_files.bpm, cc_files.rating, cc_files.encoded_by, cc_files.disc_number, cc_files.mood, cc_files.label, cc_files.composer, cc_files.encoder, cc_files.checksum, cc_files.lyrics, cc_files.orchestra, cc_files.conductor, cc_files.lyricist, cc_files.original_lyricist, cc_files.radio_station_name, cc_files.info_url, cc_files.artist_url, cc_files.audio_source_url, cc_files.radio_station_url, cc_files.buy_this_url, cc_files.isrc_number, cc_files.catalog_number, cc_files.original_artist, cc_files.copyright, cc_files.report_datetime, cc_files.report_location, cc_files.report_organization, cc_files.subject, cc_files.contributor, cc_files.language, cc_files.file_exists, cc_files.soundcloud_id, cc_files.soundcloud_error_code, cc_files.soundcloud_error_msg, cc_files.soundcloud_link_to_file, cc_files.soundcloud_upload_time, cc_files.replay_gain, cc_files.owner_id, cc_files.cuein, cc_files.cueout, cc_files.silan_check, cc_files.hidden, cc_files.is_scheduled, cc_files.is_playlist, cc_files.filesize, cc_files.description FROM podcast_episodes LEFT JOIN cc_files ON (podcast_episodes.file_id=cc_files.id) WHERE podcast_episodes.podcast_id=:p1 ORDER BY podcast_episodes.publication_date DESC] [wrapped: SQLSTATE[42703]: Undefined column: 7 ERROR:  column podcast_episodes.episode_title does not exist
LINE 1: ...odes.download_url, podcast_episodes.episode_guid, podcast_ep...
                                                             ^]' in /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php:1389
Stack trace:
#0 /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/query/ModelCriteria.php(1227): ModelCriteria->doSelect(Object(PropelPDO))
#1 /usr/share/airtime/php/airtime_mvc/application/services/PodcastEpisodeService.php(349): ModelCriteria->find()
#2 /usr/share/airtime/php/airtime_mvc/application/controllers/IndexController.php(62): Application_Service_PodcastEpisodeService->getPodcastEpisodes(1, 0, 0, 'podcast_episode...', 'DESC')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): IndexController->indexAction()
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#10 {main}
```

**Comment by Robbt** [comment]
So I think the issue is actually with the schema version being set to 3.0.0-alpha.7 and me not adding alpha.8 & alpha.9 to the application/upgrade/Upgrades.php - so they aren't automatically being applied.

So I think that the only reason you ran into all of this upgrade errors is because of the problem I introduced by jumping the versions up without properly coding it. Otherwise I think that the upgrade scripts would have worked. For instance I know that the changes in the database occurred as expected up to .8 & .9

The question then becomes more of a meta release and whether we should roll back the changes to .alpha.7 since we haven't released that version yet officially and anyone who is testing the latest version would have had to apply the database changes for .8 & .9 manually at this point.
