### ISSUE TITLE
PHP unit tests fail using PHP >=7.2

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#779]
**Describe the bug**
When running the PHP unit tests using PHP 7.2 or PHP 7.3, they fail due to the following error:

```
PHP Fatal error:  Uncaught Zend_Session_Exception: Session must be started before any output has been sent to the browser; output started in /home/travis/build/LibreTime/libretime/vendor/phpunit/phpunit/src/Util/Getopt.php/38 in /home/travis/build/LibreTime/libretime/vendor/zf1s/zend-session/library/Zend/Session.php:456
Stack trace:
#0 /home/travis/build/LibreTime/libretime/airtime_mvc/tests/application/bootstrap.php(82): Zend_Session::start()
#1 /home/travis/build/LibreTime/libretime/vendor/phpunit/phpunit/src/Util/Fileloader.php(56): include_once('/home/travis/bu...')
#2 /home/travis/build/LibreTime/libretime/vendor/phpunit/phpunit/src/Util/Fileloader.php(38): PHPUnit_Util_Fileloader::load('/home/travis/bu...')
#3 /home/travis/build/LibreTime/libretime/vendor/phpunit/phpunit/src/TextUI/Command.php(779): PHPUnit_Util_Fileloader::checkAndLoad('/home/travis/bu...')
#4 /home/travis/build/LibreTime/libretime/vendor/phpunit/phpunit/src/TextUI/Command.php(598): PHPUnit_TextUI_Command->handleBootstrap('/home/travis/bu...')
#5 /home/ in /home/travis/build/LibreTime/libretime/vendor/zf1s/zend-session/library/Zend/Session.php on line 456
```

For full logs, look at the [latest build](https://travis-ci.org/LibreTime/libretime/builds/510342041) for master on Travis CI.

**Expected behavior**
The tests pass

**LibreTime version:**
master

**Installation method:**
 - Method: Travis CI

**Comment by Robbt** [comment]
I found someone who had the same problem and put together a fix - https://discourse.zendframework.com/t/zend-session-error-with-phpunit-and-php-7-2-but-not-7-1/712/2

**Comment by jooola** [comment]
This can be closed right ?
