### ISSUE TITLE
Request on rest endpoint wihtout api_key raises a HTTP 500

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#883]
**Describe the bug**
Making a Get request on a rest media endpoint without an API_KEY raises a 500 http error, Should be 401.

**To Reproduce**
1. Run wget on a /rest/media/{number} endpoint to trigger a exception.

**Expected behavior**
Should return a 401 error (unauthorized)

**LibreTime version:**
Current master @ commit 4e99021d7

**Installation method:**
 - OS: Debian Buster
 - Method: install script + apt install silan
 - Details: Script came from master in the git repo

**Additional context**
Some logs :
```
2019-10-04T07:06:38+02:00 ERR (3): schedule.radio.org [ErrorController.php:26 - errorAction()] - Incorrect API key
2019-10-04T07:06:38+02:00 ERR (3): schedule.radio.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
2019-10-04T07:06:38+02:00 ERR (3): schedule.radio.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Exception: Incorrect API key in /usr/share/airtime/php/airtime_mvc/application/controllers/plugins/Acl_plugin.php:140
Stack trace:
#0 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
```

**Comment by Robbt** [comment]
Thanks for reporting this. Feel free to try to incorporate a fix. Our API is more alpha than the rest of the program so an issue like this isn't suprising.
