### ISSUE TITLE
Missing phtml scripts after install

### ISSUE THREAD

**Issue by donwildman** [LibreTime/libretime#989]
I've just completed a new installation on a clean install of Ubuntu 18.04, I'm getting this error in the zend logs:

```
2020-03-27T09:41:56+00:00 ERR (3): lockdown2020.co.za [ErrorController.php:26 - errorAction()] - script 'showbuilder/builder-feed.phtml' not found in path (/usr/share/airtime/php/airtime_mvc/application/views/scripts/)
2020-03-27T09:41:56+00:00 ERR (3): lockdown2020.co.za [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/zf1s/zend-view/library/Zend/View/Abstract.php(886): Zend_View_Abstract->_script('showbuilder/bui...')
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('showbuilder/bui...')
#2 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('showbuilder/bui...', NULL)
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('builderFeedActi...')
#7 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#10 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#11 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#12 {main}
```

At the same time I'm also getting this:
```
2020-03-27T03:24:39+00:00 ERR (3): lockdown2020.co.za [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Exception: Incorrect API key in /usr/share/airtime/php/airtime_mvc/application/controllers/plugins/Acl_plugin.php:140
Stack trace:
#0 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
```

Any help in tracking down Zend errors will be much appreciated...

**To Reproduce**
1. Clean install of Ubuntu 18.04 on DigitalOcean
2. Create sudo user
3. Pull from Github
4. run sudo ./install -fiap
5. Browse to FQDN 
6. Complete setup using FQDN not IP
7. Start services
8. Open site, check logs.

**Expected behavior**
All API calls should work correctly

**LibreTime version:**
3.0.0-alpha.8

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04 LTS (Xenial] 
 - Method:  `./install` 

**Client (please complete the following information if applicable):**
 - OS: Mint 19
 - Browser Chrome
 - Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by Robbt** [comment]
Did you ever resolve this ? I saw you posted on the discourse forum that you solved some issues you were running into by modifying Icecast config and putting the proper domain, not sure if it was related to this issue.
