### ISSUE TITLE
unwanted stop of services liquidsoap, playout, analyzer

### ISSUE THREAD

**Issue by Jaadoo13** [LibreTime/libretime#996]
![Bildschirmfoto 2020-04-14 um 13 57 57](https://user-images.githubusercontent.com/63636492/79222549-04255a00-7e58-11ea-9895-0ad214ea4e4c.png)
**Describe the bug**
unwanted stop of services liquidsoap, playout, analyzer
dont fount out, why...

**To Reproduce**
i startet all services and all works great.
but from nowhere, after few hours, few services stops by it self
the i restart the services, and all works great again.
Where in the logs i can find the problem?

**Expected behavior**
how can it work without stopping?

**LibreTime version:**
3.0.0~alpha.8

**Installation method:**
 - ubuntu 18.04

**Comment by Robbt** [comment]
In order to see what is crashing we will need to look at /var/log/airtime and the various logs around the time that they crash. See if you find any relevant messages in there as it will provide clues as to what is occurring. It is odd that all of the services crash vs. just one of them and that suggests something in the OS that might be causing the issue like running out of memory etc. Check your system messages to see if there is anything in there. Let me know if you need more pointers for the specific files etc.

**Comment by samkitk** [comment]
I have the same issue + including the LibreTime Media analyser too

**Comment by paddatrapper** [comment]
@samkitk:

> In order to see what is crashing we will need to look at /var/log/airtime and the various logs around the time that they crash. See if you find any relevant messages in there as it will provide clues as to what is occurring. It is odd that all of the services crash vs. just one of them and that suggests something in the OS that might be causing the issue like running out of memory etc. Check your system messages to see if there is anything in there. Let me know if you need more pointers for the specific files etc.

**Comment by tomachinz** [comment]
```
2021-06-23 00:21:34,711 [message_listener] [ERROR]  Analyzer pipeline exception:                                                                                                            │
│2021-06-23 00:21:34,713 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/within.mp3","storage_backend":"file","import_directory":"\\/srv\\/│
│2021-06-23 00:21:34,793 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:34,830 [cuepoint_analyzer] [WARNI]  list index out of range                                                                                                                │
│2021-06-23 00:21:35,453 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/Wow.wav","storage_backend":"file","import_directory":"\\/srv\\/air│
│2021-06-23 00:21:36,339 [replaygain_analyzer] [WARNI]  'NoneType' object has no attribute 'group'                                                                                           │
│2021-06-23 00:21:36,452 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:36,454 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/WhoIsHe.wav","storage_backend":"file","import_directory":"\\/srv\\│
│2021-06-23 00:21:38,167 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:39,674 [replaygain_analyzer] [WARNI]  'NoneType' object has no attribute 'group'                                                                                           │
│2021-06-23 00:21:39,764 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/YelFlam-JstDrums.wav","storage_backend":"file","import_directory":│
│2021-06-23 00:21:40,043 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:40,724 [replaygain_analyzer] [WARNI]  'NoneType' object has no attribute 'group'                                                                                           │
│2021-06-23 00:21:40,812 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/\\u2605 Justin Martin - Ruff Stuff (Eats Everything Remix) \\u2605│
│2021-06-23 00:21:40,947 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:43,640 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/young ones song.wav","storage_backend":"file","import_directory":"│
│2021-06-23 00:21:43,829 [cuepoint_analyzer] [WARNI]  Silan cue in time 6.851698 too big, ignoring.                                                                                          │
│2021-06-23 00:21:43,960 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 00:21:44,376 [replaygain_analyzer] [WARNI]  'NoneType' object has no attribute 'group'                                                                                           │
│2021-06-23 00:21:44,455 [playability_analyzer] [WARNI]  Command '['liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/airtime/stor/organize/young ones s│
│2021-06-23 00:21:44,455 [analyzer_pipeline] [ERROR]
2021-06-23 00:21:44,455 [analyzer_pipeline] [ERROR]                                                                                                                                         │
│Traceback (most recent call last):                                                                                                                                                          │
│  File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer-0.1-py3.6.egg/airtime_analyzer/playability_analyzer.py", line 34, in analyze                                              │
│    subprocess.check_output(command, stderr=subprocess.STDOUT, close_fds=True)                                                                                                              │
│  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output                                                                                                                        │
│    **kwargs).stdout                                                                                                                                                                        │
│  File "/usr/lib/python3.6/subprocess.py", line 438, in run                                                                                                                                 │
│    output=stdout, stderr=stderr)                                                                                                                                                           │
│subprocess.CalledProcessError: Command '['liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', '/srv/airtime/stor/organize/young ones song.wav']' returned non-z│
│                                                                                                                                                                                            │
│During handling of the above exception, another exception occurred:                                                                                                                         │
│                                                                                                                                                                                            │
│Traceback (most recent call last):                                                                                                                                                          │
│  File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer-0.1-py3.6.egg/airtime_analyzer/analyzer_pipeline.py", line 93, in run_analysis                                            │
│    metadata = PlayabilityAnalyzer.analyze(audio_file_path, metadata)                                                                                                                       │
│  File "/usr/local/lib/python3.6/dist-packages/libretime_analyzer-0.1-py3.6.egg/airtime_analyzer/playability_analyzer.py", line 46, in analyze                                              │
│    raise UnplayableFileError()                                                                                                                                                             │
│airtime_analyzer.playability_analyzer.UnplayableFileError                                                                                                                                   │
│2021-06-23 00:21:44,456 [message_listener] [ERROR]  Analyzer pipeline exception:                                                                                                            │
│2021-06-23 00:21:44,508 [status_reporter] [INFO ]  HTTP request sent successfully.                                                                                                          │
│2021-06-23 13:56:28,343 [message_listener] [ERROR]  Connection to message queue failed.                                                                                                     │
│2021-06-23 13:56:28,343 [message_listener] [ERROR]                                                                                                                                          │
│2021-06-23 13:56:28,343 [message_listener] [INFO ]  Retrying in 5 seconds...                                                                                                                │
│2021-06-23 13:56:33,352 [message_listener] [ERROR]  Connection to message queue failed.                                                                                                     │
│2021-06-23 13:56:33,352 [message_listener] [ERROR]                                                                                                                                          │
│2021-06-23 13:56:33,352 [message_listener] [INFO ]  Retrying in 5 seconds...                                                                                                                │
│2021-06-23 13:56:38,364 [message_listener] [INFO ]   Listening for messages...                                                                                                              │
│2021-06-23 14:17:54,650 [message_listener] [ERROR]  Connection to message queue failed.                                                                                                     │
│2021-06-23 14:17:54,773 [message_listener] [ERROR]                                                                                                                                          │
│2021-06-23 14:17:54,773 [message_listener] [INFO ]  Retrying in 5 seconds...                                                                                                                │
│2021-06-23 14:17:59,783 [message_listener] [INFO ]   Listening for messages...                                                                                                              │
│2021-06-23 15:18:55,140 [message_listener] [ERROR]  Connection to message queue failed.                                                                                                     │
│2021-06-23 15:18:55,158 [message_listener] [ERROR]
```

I believe I triggered it by deleting files out of the back-end, like via ssh. My bad.  Here is the time:

```
2021-06-19 18:24:43,957 [message_listener] [INFO ]   - Received 'b'{"tmp_file_path":"\\/srv\\/airtime\\/stor\\/organize\\/MissionImpossible.mp4","storage_backend":"file","import_directory"│
│2021-06-19 18:24:44,229 [cuepoint_analyzer] [WARNI]  ['silan', '-b', '-F', '0.99', '-f', 'JSON', '-t', '1.0', '/srv/airtime/stor/organize/MissionImpossible.mp4'] b"ad_open_ffmpeg(): ffmpeg│
│2021-06-19 18:24:45,189 [replaygain_analyzer] [WARNI]  ['replaygain', '-d', '/srv/airtime/stor/organize/MissionImpossible.mp4'] /srv/airtime/stor/organize/MissionImpossible.mp4: Did not un│
│Checking for Replay Gain information ...                                                                                                                                                    │
│  /srv/airtime/stor/organize/MissionImpossible.mp4:                                                                                                                                         │
│ 1                                                                                                                                                                                          │
│2021-06-19 18:24:45,333 [status_reporter] [INFO ]  HTTP request sent successfully.
     
root@hpstudio:/etc/airtime# ls -la   /srv/airtime/stor/organize/MissionImpossible.mp4
ls: cannot access '/srv/airtime/stor/organize/MissionImpossible.mp4': No such file or directory

```

That logfile output is from lnav I think it might have mangled it a bit.
